### ISSUE TITLE
Any plans for text outlines?

### ISSUE THREAD

**Issue by nerdoswmp** [scanny/python-pptx#1005]
Are there any plans to include outlines/borders on text elements? Ty in advance

**Comment by MartinPacker** [comment]
I was thinking about this the other day...

... I couldn't find a way to do it in the Powerpoint app on Mac. I need that to see the XML that it generates.

The XML would be key to it being a part of python-pptx. In my case I'm not a developer of python-pptx so any code I supply would be an extension.

So, how would you put a box around text using Powerpoint itself?

**Comment by nerdoswmp** [comment]
@MartinPacker in PowerPoint you can add an outline to the text through Shape Format > WordArt Styles (once you select the text itself), which will add the following tags to the text:
```
<a:solidFill>
  <a:schemeClr val="accent1">
    <a:lumMod val="75000"/>
  </a:schemeClr>
</a:solidFill>
```
As far as I can tell that's the only thing that changes if you add an outline to text

**Comment by scanny** [comment]
No current plans for WordArt support.

**Comment by nerdoswmp** [comment]
Alright, thank you for the response!

**Comment by MartinPacker** [comment]
Noting @scanny's answer. But I assume the above XML applies to a run. I hope to experiment. Maybe I can rustle up some python that injects the necessary. Unfortunately I'm snowed under right now.

**Comment by MartinPacker** [comment]
This snippet suggests `solidFill` is a child of a `rPr` which is a child of a `r` element. Now whether the rest of what you posted works is another matter. But it looks feasible to experiment.

```
<a:p>
  <a:pPr algn="ctr"/>
  <a:r>
    <a:rPr lang="en-US" dirty="0" smtClean="0">
      <a:solidFill>
        <a:schemeClr val="tx1"/>
      </a:solidFill>
    </a:rPr>
    <a:t>This is in a shape</a:t>
  </a:r>
  <a:endParaRPr lang="en-US" dirty="0"/>
    <a:solidFill>
      <a:schemeClr val="tx1"/>
    </a:solidFill>
  </a:endParaRPr>
</a:p>
```

**Comment by nerdoswmp** [comment]
> This snippet suggests `solidFill` is a child of a `rPr` which is a child of a `r` element. Now whether the rest of what you posted works is another matter. But it looks feasible to experiment.
> 
> ```
> <a:p>
>   <a:pPr algn="ctr"/>
>   <a:r>
>     <a:rPr lang="en-US" dirty="0" smtClean="0">
>       <a:solidFill>
>         <a:schemeClr val="tx1"/>
>       </a:solidFill>
>     </a:rPr>
>     <a:t>This is in a shape</a:t>
>   </a:r>
>   <a:endParaRPr lang="en-US" dirty="0"/>
>     <a:solidFill>
>       <a:schemeClr val="tx1"/>
>     </a:solidFill>
>   </a:endParaRPr>
> </a:p>
> ```

Oh for sure, doesn't look like it's something that is impossible to take a crack at doing, from what I tested it really just looks like it adds those 2/3 extra tags, maybe someday I'll try it myself but for now I'll continue my development WordArt-less haha

Sorry for the late reply also
