### ISSUE TITLE
PackageNot FoundError

### ISSUE THREAD

**Issue by Clifflily** [scanny/python-pptx#1007]
I just create a simple pptx like this:
ppt = Presentation()
slide = ppt.slides.add_slide(ppt.slide_layouts[0])
ppt.save('test_presentation.pptx')

but appeared  such error:
pptx.exc.PackageNotFoundError: Package not found at 'C:\SoftWare\Python\Lib\site-packages\pptx\templates\default.pptx'

I uninstalled/installed pptx , even created a default.pptx and placed it to this dir  which couldn't resolve the issue. Do you have any idea for that?

**Comment by MartinPacker** [comment]
I can't solve your problem but would observe you're usually better off basing the presentation off one of your own, rather than the default one.

**Comment by Clifflily** [comment]
I used my own one, but similar issue:
source = Presentation(source_ppt)
pptx.exc.PackageNotFoundError: Package not found at 'C:\iCode\iPython\PPTHandler\source.pptx'

**Comment by scanny** [comment]
That error can only appear when opening a file, not when saving it. So your description is off somehow.

This means the file is not a Zip archive or there is just no file by that name at that path.

This can happen if you try to open a legacy `.ppt` file which uses a different and incompatible format.

**Comment by Clifflily** [comment]
Yes,you are right. My file is not a Zip archive, its extension name is .pptx , though. It is not a valid .pptx. Thanks you comments very much!
