### ISSUE TITLE
Text Properties is changing Automatically

### ISSUE THREAD

**Issue by KalyanM45** [scanny/python-pptx#1010]
I applied different formats (color and size) to the first and second lines of text in a single cell in a table (Say (0,1)). However, after uploading it to cloud storage like OneDrive, the formatting changes automatically. The original formatting is visible in the preview tab and remains intact when I download the file.

Could this be an issue with cloud encoding, or should I add LOC (Lines of Code) to handle the formatting issue?

**Comment by scanny** [comment]
`python-pptx` will not update a thumbnail image associated with a file. That's generated by PowerPoint or whatever other client you're using.

However the actual changes visible when you open the file should be preserved.

Have a closer look at the before and after and see if you can narrow down what changes when.

But python-docx does not produce auto-mutating files. Not sure what LOC are in this context or how that relates.
