### ISSUE TITLE
from markdown to text_frame

### ISSUE THREAD

**Issue by designamx** [scanny/python-pptx#1027]
hi team,

I have some content provided by an external source in markdown format (it could be html or any other format), it would be painful to add this content into a text frame since it contains mixed formats see attachment

is there a way to just add the content in a spacial format such as markdown, html or xml?
<img width="839" alt="image" src="https://github.com/user-attachments/assets/ac4a8580-1d1e-40c1-b570-7686d89ae5af">

**Comment by scanny** [comment]
@MartinPacker is this something `md2pptx` can help with?

**Comment by MartinPacker** [comment]
Thank you, @scanny. I thought that, too. But I was a little leery of advertising it in your issues.

There might be work to do to condition the Markdown - or add some metadata to the front of the deck - to create a nice presentation.

My assumption is that the Markdown is regularly generated or provided and automating turning it into a .pptx is a time / hassle saver.

In any case you can get md2pptx from [here](https://github.com/MartinPacker/md2pptx). Something that might help wrangle the Markdown - for example including files and using variables is my other project [mdpre](https://github.com/MartinPacker/mdpre).

Of course md2pptx requires python-pptx and a suitably high level of Python 3.

@designamx, if you find bugs or have requirements of md2pptx please open Issues.
