### ISSUE TITLE
feature: Support for slide notes

### ISSUE THREAD

**Issue by PeterMinin** [scanny/python-pptx#122]
Seems like slide notes are not supported and there has been no corresponding issue.

**Comment by slewisma** [comment]
Just found python-pptx and was pretty happy to find it solved the first part of what I needed: a way to get the text from the slides in a presentation. I need the slide notes too though so just dropping a note here to reinforce this is needed.

**Comment by rajashekar91** [comment]
Can we access PPT Slide Notes from Python Script?

**Comment by rday** [comment]
I've been accessing the notes slides in an application I have. I just haven't had time to come up with a method of doing this which would work well as a contribution.

Check out this gist: https://gist.github.com/3205bf5aab78623c5ee5.git

You'll need to be using a recent version of python-pptx (0.5.6 or later). Basically, I'm wrapping a slide object from the presentation. Then I can access the notes using that wrapped slide object.

I'd like to get this integrated if possible. But there are a lot of missing features and probably wouldn't work as expected. Let me know your mileage though. Maybe we can get this to a working state.

**Comment by rajashekar91** [comment]
Hey. Thanks for your response.
What I am trying to do is to retrieve some specific fields from the Notes of ppt slide using python.

 I have gone through the link you specified but I am just wondering how to use those functions for my task. Could you give me some input regarding this.

**Comment by rday** [comment]
Once you have the notes_slide object, you can iterate through the shapes like any other object

```python
slide = self.presentation.slides[1]
notes_slide = SlideWrapper(slide).notes_page()

for shape in notes_slide.shapes.__iter__():
    if shape.has_text_frame:
        for p in shape.text_frame.paragraphs:
            for run in p.runs:
                yield extract_fields_from_run(run)
```

One thing I've noticed about the notes slides is that the runs aren't necessarily contiguous pieces of text. Even if the formatting doesn't change, you may have a specific piece of text broken over several runs. So

`Field 1, Field 2, Field 3, Field 4`

Maybe be broken up into 2 or 3 runs without you knowing. For my particular task I ended up writing a parser that had to keep a state so I knew when I was done reading data. Then I iterated through all the paragraphs and runs until I had what I needed.

Does that help any?

**Comment by rajashekar91** [comment]
Hi.. I am facing Compilation Errors for the below two lines like unsolved reference

from pptx.parts.slide import  _SlidePlaceholders, _SlideShapeTree
from pptx.shapes.shape import BaseShape

I am using python-pptx-0.5.7

Why is this happening?

**Comment by rday** [comment]
I remember this error now. I'm using 0.5.6 at the moment(working). There was something with the 'sldImg' XML type that I just couldn't get working under 0.5.7. The 0.5.7 import code is:

```python
from pptx.util import lazyproperty
from pptx.parts.slide import BaseSlide, Slide, _SlidePlaceholders
from pptx.shapes.shapetree import SlideShapeTree as _SlideShapeTree
from pptx.opc.constants import RELATIONSHIP_TYPE as RT
from pptx.enum.shapes import PP_PLACEHOLDER_TYPE
from pptx.oxml.xmlchemy import BaseOxmlElement, OneAndOnlyOne, ZeroOrOne
from pptx.oxml import parse_xml
from pptx.oxml.ns import nsdecls
from pptx.opc.constants import CONTENT_TYPE as CT
from pptx.oxml import register_element_cls
from pptx import content_type_to_part_class_map
from pptx.opc.package import PartFactory
```

The test program is:

```python
from pptx import Presentation
pres = Presentation('test.pptx')
slide = pres.slides[1]
notes_slide = SlideWrapper(slide).notes_page()
for r in notes_slide.get_slide_runs():
    print(r.text)
```

I keep getting the following error:

```python
  File "/home/rday/Development/TestEnv/lib/python3.4/site-packages/pptx/enum/base.py", line 189, in from_xml
    return cls._xml_to_member[xml_val]
KeyError: 'sldImg'
```

You most likely have a tag in your notes slide similar to:

```<p:nvPr><p:ph type="sldImg"/></p:nvPr>```

which is breaking that parsing. I hadn't progressed past this error during development. I used 0.5.6 and had to keep moving forward to get a feature released.

The solution (I think) lies in pptx.enum.shapes.PP_PLACEHOLDER_TYPE. There needs to be a new XmlMappedEnumMember 'sldImg'. I tried briefly to monkey patch that module, but had no success. Now I'm quite interested again.

@scanny any thoughts here? I figured I'd ask before I start diving down this rabbit hole once more.

**Comment by rday** [comment]
Just to follow up on the thought:

If you add

```python
        XmlMappedEnumMember(
            'SLIDE_NUMBER', 18, 'sldImg', 'Slide Image'
        ),
```

to the __members__ attribute (it's a tuple) of the PP_PLACEHOLDER_TYPE class in the pptx.enum.shapes module, then you can successfully read the notes slides using 0.5.7.

**Comment by rajashekar91** [comment]
Hello. Thank you very much.

I have added the above line in the members attribute of PP_PLACEHOLDER_TYPE class, and its compiling fine.
But I am unable to print notes from my ppt.

for r in notes_slide.get_slide_runs():
    print(r.text)

Does the above one works to print notes from ppt?

**Comment by rday** [comment]
I've updated the Gist as well but neglected to mention that. Sorry! Please replace your get_slide_runs() method with the following:

```python
    def get_slide_runs(self):
        for shape in self.shapes:
            if shape.has_text_frame and shape.is_placeholder:
                for p in shape.text_frame.paragraphs:
                    for run in p.runs:
                        yield run
```
I've removed the type check, and simply look to see if the shape has a text_frame. I bet thats why no notes were printing.

**Comment by rajashekar91** [comment]
Yes.. This is working well.
I am able to print the Notes.

Thank you very much..

**Comment by rday** [comment]
:+1: let me know if you hit any bugs. We can try to move this into production.

**Comment by rajashekar91** [comment]
Sure..
Suppose if there is no notes present in the slide of ppt, then I am facing the following error.

raise KeyError(tmpl % reltype)
KeyError: "no relationship of type 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/notesSlide' in collection"

**Comment by buzzm** [comment]
Hello!   Big fan of this module; completely changes the dynamics of prezo materials construction and ongoing maintenance!
Would like to add a +1 for notes especially the ability to add them to a prezo with no notes (i.e. avoiding the garden variety KeyError problems)

**Comment by inl1ne** [comment]
I added support for note writing to a fork at https://github.com/inl1ne/python-pptx. It's heavily based on rday's gist, but I did need to rewrite the creation code--I suspect that rday's intent was to read notes, not write them. There's also some trickiness to adding a new writeable class derived from Slide that I might be able to fix with a bit of refactoring.

I'm planning to submit this as a pull request once I get some time to write tests and such. In the meantime, I'll leave the fork up in case anyone else finds it helpful.

**Comment by danielzfranklin** [comment]
I just want to say that I find this issue critical and will likely not be using this library until this gets fixed. I need the ability to change notes in the presentation.

**Comment by lelap** [comment]
I'm experiencing the same as @rajashekar91 – seems like that when slide has no notes written, but somehow a notesSlide##.xml file for that slide was created in the .pptx, the script is fine with the blank note. But when there is no notesSlide##.xml file for the slide, this error occurs:
*KeyError: "no relationship of type 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/notesSlide' in collection"*

**Comment by scanny** [comment]
This is a legitimate exception. Not all slides will have a notes slide associated with them. You should catch the exception and do the right thing for your use case when the notes slide doesn't exist. In this case it might be useful to add to the @rday script a function that encapsulates this exception handling and returns None when no notes slide is present. The SlideWrapper.notes_slide() method there assumes that None is returned from Part.part_related_by() where it actually raises an exception for the "no such part" condition.

**Comment by rday** [comment]
I will update my gist when I get back this weekend. I may be able to help with the tests for @inl1ne's code as well. I think the tests are why he hasn't issued a PR yet.

**Comment by rday** [comment]
I've updated my gist based on @inl1ne's branch. I'll make a real effort to
help write these tests. We'll get notes soon enough :)

**Comment by vjain419** [comment]
Any update which will have this feature?

**Comment by scanny** [comment]
I haven't seen any work on this lately, so no, no update.

**Comment by vjain419** [comment]
is it possible to add support, it is nice feature to have. @rday has provided some wrapper class.

I will try to use @rday wrapper class see if it works but I vote for this feature.

**Comment by vjain419** [comment]
I tried using @rday  wrapper class and its give me an error. can anybody please help

I think notes_slide object is missing but i tried to 

slide = prs['PPA'].slides.add_slide(prs['PPA'].slide_layouts[3])
note_slides = notes_slide.SlideWrapper(slide).notes_page()
for r in note_slides.get_slide_runs():
print(r.text)

Traceback (most recent call last): File "generator.py", line 1380, in <module> note_slides = notes_slide.SlideWrapper(slide_).notes_page() File "notes_slide.py", line 94, in __getattr__ return self._slide.__getattribute__(attr) AttributeError: 'Slide' object has no attribute 'notes_page'

**Comment by rday** [comment]
Hi @vjain419, thanks for the tweet, I didn't see any emails from Github on this issue.

This gist is only tested on 0.5.6, which could be a possible source of problems.

More importantly, the wrapper doesn't work when adding slides. The notes slide must already exist in the PPTX you are working with.

It looks like the notes slide in this example is being created dynamically, so it will probably break.

This was a stumbling block for me, and time got in the way, so it remains unfinished.

**Comment by vjain419** [comment]
@rday Thanks for your response.

is it possible to spend some time and quick fix or workaround :+1:  i would really appriciate as I used python-pptx for all scription which i was developing since last 3 months and I need notes page support to add some information which i cant cover in mage slide.

**Comment by scanny** [comment]
This was added in the new release, v0.6.2.

**Comment by shreyaaa4** [comment]
Hey, 
I'm having some data in a table shape and along with that I have added a shape rectangle.
Now, I want to apply conditions on data in table and then want to write corresponding to that data in rectangle. Like this, there will be conditions on multiple data and some write up in rectangle respectively.

Is it possible to apply conditions on text within shape?
