### ISSUE TITLE
page setup function and slide insert function

### ISSUE THREAD

**Issue by shelper** [scanny/python-pptx#129]
I could not find the function for setting up the page size, 
e.g. the default page size of each slide is 10x7.5.
it seems there is no way to change it using the module. 
could the author please to check if it is possible to add something like 
prs = Presentation(slide_size, orientation)
also, it would be nice if the user can add index or unique name for each slide so that when needed the user can easily insert a page before certain slide by index or slide name

**Comment by scanny** [comment]
@shelper - I'm not sure what release it came in on exactly, but this is in the library now as `Presentation.slide_width` and `Presentation.slide_height`.
