### ISSUE TITLE
importing ChartData

### ISSUE THREAD

**Issue by nagordon** [scanny/python-pptx#145]
when instantiating ChartData (https://python-pptx.readthedocs.org/en/latest/user/charts.html), I had to import it first  
```python
from pptx.chart.data import ChartData
```
 Is this an error in the examples?

**Comment by scanny** [comment]
Yep, good catch Neal. I'll add the import line in the docs there. It will appear in the next release. Thanks :)

**Comment by scanny** [comment]
Fixed; will push with next release.
