### ISSUE TITLE
Feature Request: support applying saved theme to individual slides? 

### ISSUE THREAD

**Issue by linzhong** [scanny/python-pptx#146]

**Comment by scanny** [comment]
Hi @linzhong, can you describe your use case for us?

**Comment by linzhong** [comment]
Sure,

I would like to create a powerpoint file using your libraray. We have some
format themes already defined, so instead of recreate all the format in the
code, I would like to apply the corresponding theme settings to the slides
that I produce. (Just like in the powerpoint application, choose the
corresponding theme and apply to the selected slide)

Ideally, I would like to be able to create some template slides and just
insert certain data into the slide templates, I don't see this is supported
from what I learned in the document so far. The template support may be too
much to ask. But if I can apply the theme to the generated slides, it will
work in my scenario as well.

Thanks,
Lin

On Fri, Feb 20, 2015 at 1:49 PM, Steve Canny <notifications@github.com>
wrote:

> Hi @linzhong <https://github.com/linzhong>, can you describe your use
> case for us?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scanny/python-pptx/issues/146#issuecomment-75325397>.
>



-- 
*Lin Zhong  *

---

Applause gets ​​Three Straight Years as one of Forbes’ Most Promising
Companies <http://www.applause.com/awards>

**Comment by scanny** [comment]
As far as the themes go, the approach would be to create a starting .pptx file, a "template" of sorts, that you use as the starting point for the presentation you generate.
http://python-pptx.readthedocs.org/en/latest/user/presentations.html

In that starting .pptx file you would include your customized themes. You can do this by creating a presentation that uses all the themes you would like to have available and then deleting all the slides (but not the slide masters or slide layouts). You will be left with an empty presentation having multiple slide masters, each of which has its own set of slide layouts.

Then you pick the particular layout you want to generate each slide, perhaps something like this:

```python
from pptx import Presentation
prs = Presentation('my-template.pptx')
slide_layout = prs.slide_masters[2].slide_layouts[3]
slide = prs.slides.add_slide(slide_layout)
```

You'll need to know in advance what the (master_idx, layout_idx) combination is to get the theme/layout combination you're after as they are only accessible by index at the moment.

Does that give you what you need?

**Comment by linzhong** [comment]
Thanks a lot, Steve.

This indeed serve the need, I read the page you refer to earlier and knew
that I can open existing slide. But I didn't realize that I can retrieve
the layout of existing one to create the new one. Thanks a lot for pointing
it out. This is great! :)

Lin

On Fri, Feb 20, 2015 at 4:03 PM, Steve Canny <notifications@github.com>
wrote:

> As far as the themes go, the approach would be to create a starting .pptx
> file, a "template" of sorts, that you use as the starting point for the
> presentation you generate.
> http://python-pptx.readthedocs.org/en/latest/user/presentations.html
>
> In that starting .pptx file you would include your customized themes. You
> can do this by creating a presentation that uses all the themes you would
> like to have available and then deleting all the slides (but not the slide
> masters or slide layouts). You will be left with an empty presentation
> having multiple slide masters, each of which has its own set of slide
> layouts.
>
> Then you pick the particular layout you want to generate each slide,
> perhaps something like this:
>
> from pptx import Presentation
> prs = Presentation('my-template.pptx')
> slide_layout = prs.slide_masters[2].slide_layouts[3]
> slide = prs.slides.add_slide(slide_layout)
>
> You'll need to know in advance what the (master_idx, layout_idx)
> combination is to get the theme/layout combination you're after as they are
> only accessible by index at the moment.
>
> Does that give you what you need?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scanny/python-pptx/issues/146#issuecomment-75342055>.
>



-- 
*Lin Zhong  *

---

Applause gets ​​Three Straight Years as one of Forbes’ Most Promising
Companies <http://www.applause.com/awards>

**Comment by linzhong** [comment]
Steve,

I manage to add the slide with the template fine. Could you please point me
to the document on how to delete the slides?

From your document (
http://python-pptx.readthedocs.org/en/latest/user/slides.html), it says
that the support for this feature is in the backlog. Does this feature
become available now, or when do you expect it to be available?

Thanks,
Lin

On Mon, Feb 23, 2015 at 11:04 AM, Lin Zhong <lzhong@applause.com> wrote:

> Thanks a lot, Steve.
>
> This indeed serve the need, I read the page you refer to earlier and knew
> that I can open existing slide. But I didn't realize that I can retrieve
> the layout of existing one to create the new one. Thanks a lot for pointing
> it out. This is great! :)
>
> Lin
>
> On Fri, Feb 20, 2015 at 4:03 PM, Steve Canny <notifications@github.com>
> wrote:
>
>> As far as the themes go, the approach would be to create a starting .pptx
>> file, a "template" of sorts, that you use as the starting point for the
>> presentation you generate.
>> http://python-pptx.readthedocs.org/en/latest/user/presentations.html
>>
>> In that starting .pptx file you would include your customized themes. You
>> can do this by creating a presentation that uses all the themes you would
>> like to have available and then deleting all the slides (but not the slide
>> masters or slide layouts). You will be left with an empty presentation
>> having multiple slide masters, each of which has its own set of slide
>> layouts.
>>
>> Then you pick the particular layout you want to generate each slide,
>> perhaps something like this:
>>
>> from pptx import Presentation
>> prs = Presentation('my-template.pptx')
>> slide_layout = prs.slide_masters[2].slide_layouts[3]
>> slide = prs.slides.add_slide(slide_layout)
>>
>> You'll need to know in advance what the (master_idx, layout_idx)
>> combination is to get the theme/layout combination you're after as they are
>> only accessible by index at the moment.
>>
>> Does that give you what you need?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/scanny/python-pptx/issues/146#issuecomment-75342055>.
>>
>
>
>
> --
> *Lin Zhong  *
>
> ---
>
> Applause gets ​​Three Straight Years as one of Forbes’ Most Promising
> Companies <http://www.applause.com/awards>
>



-- 
*Lin Zhong  *

---

Applause gets ​​Three Straight Years as one of Forbes’ Most Promising
Companies <http://www.applause.com/awards>

**Comment by linzhong** [comment]
FYI,

If I open the template and use the template layout to add slide to a bland
new presentation, I will get an error. The error require repair operation
when open the new slide, though the repair result looks correct.

template = Presentation(TEMPLATE_PATH)
prs = Presentation()
#title slide
slide_layout = template.slide_masters[0].slide_layouts[0]
slide = prs.slides.add_slide(slide_layout)

...


On Mon, Feb 23, 2015 at 3:19 PM, Lin Zhong <lzhong@applause.com> wrote:

> Steve,
>
> I manage to add the slide with the template fine. Could you please point
> me to the document on how to delete the slides?
>
> From your document (
> http://python-pptx.readthedocs.org/en/latest/user/slides.html), it says
> that the support for this feature is in the backlog. Does this feature
> become available now, or when do you expect it to be available?
>
> Thanks,
> Lin
>
> On Mon, Feb 23, 2015 at 11:04 AM, Lin Zhong <lzhong@applause.com> wrote:
>
>> Thanks a lot, Steve.
>>
>> This indeed serve the need, I read the page you refer to earlier and knew
>> that I can open existing slide. But I didn't realize that I can retrieve
>> the layout of existing one to create the new one. Thanks a lot for pointing
>> it out. This is great! :)
>>
>> Lin
>>
>> On Fri, Feb 20, 2015 at 4:03 PM, Steve Canny <notifications@github.com>
>> wrote:
>>
>>> As far as the themes go, the approach would be to create a starting
>>> .pptx file, a "template" of sorts, that you use as the starting point for
>>> the presentation you generate.
>>> http://python-pptx.readthedocs.org/en/latest/user/presentations.html
>>>
>>> In that starting .pptx file you would include your customized themes.
>>> You can do this by creating a presentation that uses all the themes you
>>> would like to have available and then deleting all the slides (but not the
>>> slide masters or slide layouts). You will be left with an empty
>>> presentation having multiple slide masters, each of which has its own set
>>> of slide layouts.
>>>
>>> Then you pick the particular layout you want to generate each slide,
>>> perhaps something like this:
>>>
>>> from pptx import Presentation
>>> prs = Presentation('my-template.pptx')
>>> slide_layout = prs.slide_masters[2].slide_layouts[3]
>>> slide = prs.slides.add_slide(slide_layout)
>>>
>>> You'll need to know in advance what the (master_idx, layout_idx)
>>> combination is to get the theme/layout combination you're after as they are
>>> only accessible by index at the moment.
>>>
>>> Does that give you what you need?
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/scanny/python-pptx/issues/146#issuecomment-75342055>
>>> .
>>>
>>
>>
>>
>> --
>> *Lin Zhong  *
>>
>> ---
>>
>> Applause gets ​​Three Straight Years as one of Forbes’ Most Promising
>> Companies <http://www.applause.com/awards>
>>
>
>
>
> --
> *Lin Zhong  *
>
> ---
>
> Applause gets ​​Three Straight Years as one of Forbes’ Most Promising
> Companies <http://www.applause.com/awards>
>



-- 
*Lin Zhong  *

---

Applause gets ​​Three Straight Years as one of Forbes’ Most Promising
Companies <http://www.applause.com/awards>

**Comment by linzhong** [comment]
Sorry, Never mind,

Read your email again, and found my misunderstanding. You mean delete the
slide directly from template, not from the code.

Please ignore my earlier questions.

Thanks,
Lin

On Mon, Feb 23, 2015 at 3:28 PM, Lin Zhong <lzhong@applause.com> wrote:

> FYI,
>
> If I open the template and use the template layout to add slide to a bland
> new presentation, I will get an error. The error require repair operation
> when open the new slide, though the repair result looks correct.
>
> template = Presentation(TEMPLATE_PATH)
> prs = Presentation()
> #title slide
> slide_layout = template.slide_masters[0].slide_layouts[0]
> slide = prs.slides.add_slide(slide_layout)
>
> ...
>
>
> On Mon, Feb 23, 2015 at 3:19 PM, Lin Zhong <lzhong@applause.com> wrote:
>
>> Steve,
>>
>> I manage to add the slide with the template fine. Could you please point
>> me to the document on how to delete the slides?
>>
>> From your document (
>> http://python-pptx.readthedocs.org/en/latest/user/slides.html), it says
>> that the support for this feature is in the backlog. Does this feature
>> become available now, or when do you expect it to be available?
>>
>> Thanks,
>> Lin
>>
>> On Mon, Feb 23, 2015 at 11:04 AM, Lin Zhong <lzhong@applause.com> wrote:
>>
>>> Thanks a lot, Steve.
>>>
>>> This indeed serve the need, I read the page you refer to earlier and
>>> knew that I can open existing slide. But I didn't realize that I can
>>> retrieve the layout of existing one to create the new one. Thanks a lot for
>>> pointing it out. This is great! :)
>>>
>>> Lin
>>>
>>> On Fri, Feb 20, 2015 at 4:03 PM, Steve Canny <notifications@github.com>
>>> wrote:
>>>
>>>> As far as the themes go, the approach would be to create a starting
>>>> .pptx file, a "template" of sorts, that you use as the starting point for
>>>> the presentation you generate.
>>>> http://python-pptx.readthedocs.org/en/latest/user/presentations.html
>>>>
>>>> In that starting .pptx file you would include your customized themes.
>>>> You can do this by creating a presentation that uses all the themes you
>>>> would like to have available and then deleting all the slides (but not the
>>>> slide masters or slide layouts). You will be left with an empty
>>>> presentation having multiple slide masters, each of which has its own set
>>>> of slide layouts.
>>>>
>>>> Then you pick the particular layout you want to generate each slide,
>>>> perhaps something like this:
>>>>
>>>> from pptx import Presentation
>>>> prs = Presentation('my-template.pptx')
>>>> slide_layout = prs.slide_masters[2].slide_layouts[3]
>>>> slide = prs.slides.add_slide(slide_layout)
>>>>
>>>> You'll need to know in advance what the (master_idx, layout_idx)
>>>> combination is to get the theme/layout combination you're after as they are
>>>> only accessible by index at the moment.
>>>>
>>>> Does that give you what you need?
>>>>
>>>> —
>>>> Reply to this email directly or view it on GitHub
>>>> <https://github.com/scanny/python-pptx/issues/146#issuecomment-75342055>
>>>> .
>>>>
>>>
>>>
>>>
>>> --
>>> *Lin Zhong  *
>>>
>>> ---
>>>
>>> Applause gets ​​Three Straight Years as one of Forbes’ Most Promising
>>> Companies <http://www.applause.com/awards>
>>>
>>
>>
>>
>> --
>> *Lin Zhong  *
>>
>> ---
>>
>> Applause gets ​​Three Straight Years as one of Forbes’ Most Promising
>> Companies <http://www.applause.com/awards>
>>
>
>
>
> --
> *Lin Zhong  *
>
> ---
>
> Applause gets ​​Three Straight Years as one of Forbes’ Most Promising
> Companies <http://www.applause.com/awards>
>



-- 
*Lin Zhong  *

---

Applause gets ​​Three Straight Years as one of Forbes’ Most Promising
Companies <http://www.applause.com/awards>

**Comment by scanny** [comment]
Yes. The key thing here is what slide masters and slide layouts you have available to you at run time.

When you add the slides having a different theme, their slide master and slide layouts are automatically added to the file too. You just don't see them unless you go looking for them in the Slide Master view. Once that's done, you get rid of the slides you added so you can start with an empty presentation. Deleting the slides does *not* remove the new masters and layouts. Once they're in they're there to stay unless you delete them manually. All this is done "by hand" using PowerPoint, just to get your template file configured correctly.

There are other ways to do it--any method that gets the masters and layouts in there is fine--but this way is probably the quickest.

What you're really looking for is how the starting presentation looks in Slide Master view. In regular Slide view mode, it should be empty when you're done. Slide Master view is also where you can figure out what the index of a particular master or layout is; just remember to start counting at 0 instead of 1.

Note there is at least one other part involved, the theme{n}.xml files. Those specify the palette and fonts used by the master and layouts for that theme, and perhaps a few other details. Those get added automatically by this process. I just mention them here for anyone who might take a more direct approach :)

**Comment by linzhong** [comment]
This are awesome tips. Thanks!

On Mon, Feb 23, 2015 at 4:34 PM, Steve Canny <notifications@github.com>
wrote:

> Yes. The key thing here is what slide masters and slide layouts you have
> available to you at run time.
>
> When you add the slides having a different theme, their slide master and
> slide layouts are automatically added to the file too. You just don't see
> them unless you go looking for them in the Slide Master view. Once that's
> done, you get rid of the slides you added so you can start with an empty
> presentation. Deleting the slides does *not* remove the new masters and
> layouts. Once they're in they're there to stay unless you delete them
> manually. All this is done "by hand" using PowerPoint, just to get your
> template file configured correctly.
>
> There are other ways to do it--any method that gets the masters and
> layouts in there is fine--but this way is probably the quickest.
>
> What you're really looking for is how the starting presentation looks in
> Slide Master view. In regular Slide view mode, it should be empty when
> you're done. Slide Master view is also where you can figure out what the
> index of a particular master or layout is; just remember to start counting
> at 0 instead of 1.
>
> Note there is at least one other part involved, the theme{n}.xml files.
> Those specify the palette and fonts used by the master and layouts for that
> theme, and perhaps a few other details. Those get added automatically by
> this process. I just mention them here for anyone who might take a more
> direct approach :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scanny/python-pptx/issues/146#issuecomment-75673910>.
>



-- 
*Lin Zhong  *

---

Applause gets ​​Three Straight Years as one of Forbes’ Most Promising
Companies <http://www.applause.com/awards>
