### ISSUE TITLE
Text size not resizing shape

### ISSUE THREAD

**Issue by moritzmoritz** [scanny/python-pptx#147]
Hey guys,

what am I doing wrong:

```
shape = shapes.add_shape(
    MSO_SHAPE.RECTANGLE, x, y, width, height
)

text_frame = shape.text_frame
text_frame.auto_size = MSO_AUTO_SIZE.SHAPE_TO_FIT_TEXT
text_frame.text = 'A loooooooong text'

```
I want to resize the shape that it fits to the text inside.

After setting the text the shape.height does not change :( ... anyone can help me out here? 
Thanks!

**Comment by scanny** [comment]
Shape resizing depends on the PowerPoint rendering engine, so only happens at run-time unfortunately.

If you click into the shape I think you'll see it adjust to fit.

LibreOffice seems to update shape size automatically during start-up but PowerPoint doesn't.

Adding this feature would be error-prone and expensive, essentially duplicating that aspect of the rendering engine by trial and error without the right tools to do it available in Python.

We do have an experimental feature in there to do the opposite, that is "shrink text to fit":
http://python-pptx.readthedocs.org/en/latest/api/text.html#pptx.text.text.TextFrame.fit_text

That was a sponsored feature, which is probably about what it would take to get this one done.

**Comment by chkruege** [comment]
is there an update to this issue?

i basically want to do the same: resizing the shape to fit the text. the reason is that i want to give a background-color.

**Comment by MartinPacker** [comment]
So, is there a workaround involving opening Powerpoint and AUTOMATICALLY triggering the resize? I happen to be on Mac but wonder about Windows, too. (For me I guess I just use some AppleScript to open it and save it again, right?)

Today, as part of MY code that calls python-pptx, I have an AppleScript that throws away the first page. So I suppose this is just an extension to that, if not the self same script.

**Comment by asima-azmat** [comment]
I have this same issue. Has there been an upate?

**Comment by chaebinkim25** [comment]
I coud use VBA macro like this. only works for the titles. 

```visual basic
Sub AutoSizeTitles()
    Dim sld As Slide
    Dim shp As Shape

    For Each sld In ActivePresentation.Slides
        For Each shp In sld.Shapes
            If shp.Type = msoPlaceholder Then
                If shp.PlaceholderFormat.Type = ppPlaceholderTitle Then
                    shp.TextFrame.AutoSize = ppAutoSizeShapeToFitText
                End If
            End If
        Next shp
    Next sld
End Sub
```
