### ISSUE TITLE
feature: ChartData supports None value for a missing data point

### ISSUE THREAD

**Issue by Sylvanuss** [scanny/python-pptx#149]
was: Corrupted file when updating chart data using replace_data method

Hi,

When updating chart's data through the replace_data method. Python's "None" is translated into two differents ways between the XSLX data sheet and the XML chart's file :
- to an empty string, in the xslx file (located in "embeddings" subfolder).
- to the "None" string in the tag c:v of the XML's chart (located in "chart" subfolder).
Producing a corrupted file leading to chart related slide loss, when opening the PPTX.

I think the method "_val_pt_xml" from chart/data.py should handle data types in the same way Workbook.write does.

Sorry for my english.

Regards.

**Comment by scanny** [comment]
Hi @Sylvanuss, I agree. It's sensible to allow missing values and in any case ChartData should do the right thing when encountering non-numeric values. I'll leave this open as a feature request to enhance the charting sub-package to accommodate this.

**Comment by scanny** [comment]
This was added in the v0.6.0 release, uploaded to PyPI today.
