### ISSUE TITLE
Any support on multiple chart in one slide in the near future?

### ISSUE THREAD

**Issue by linzhong** [scanny/python-pptx#152]
Hi, Steve, 

I would like to generate a slide with some side by side charts together with some explanation notes for the chart. From your document, looks like you do not support it so far. Do you have any plan to support multiple charts in the near future? Or is there any work around that I can potentially use to accomplish this request? 

Thanks,
Lin

**Comment by scanny** [comment]
Hi Lin, I'm not sure I've ever actually tried it, but I don't see why it shouldn't work. What leads you to believe it isn't supported?

**Comment by linzhong** [comment]
Hi, Steve,

It turns out to be my poor interpretation of your help file. I got the
impression from
http://python-pptx.readthedocs.org/en/latest/user/charts.html, where it
says that "Most charts only have a single plot and python-pptxdoesn’t yet
support creating multi-plot charts, but you can access multiple plots on a
chart that already has them."

I misunderstood the plot concept with chart from above statement earlier. I
have tried it later and pptx does support multiple charts in one slide.
Sorry that I forgot to delete my original questions,

Lin



On Tue, Mar 17, 2015 at 9:15 PM, Steve Canny <notifications@github.com>
wrote:

> Hi Lin, I'm not sure I've ever actually tried it, but I don't see why it
> shouldn't work. What leads you to believe it isn't supported?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scanny/python-pptx/issues/152#issuecomment-82732499>.
>



-- 
*Lin Zhong  *

---

Applause gets ​​Three Straight Years as one of Forbes’ Most Promising
Companies <http://www.applause.com/awards>

**Comment by scanny** [comment]
No worries Lin, the plot vs. chart distinction is a subtle and potentially confusing one. In many contexts (but not this one :), *plot* and *chart* are synonyms.

Just for anyone who encounters this on search, python-pptx supports multiple charts on a single slide. What it doesn't support yet is having more than one "chart type" in a single chart. The classic example would be a *single* chart having a line plot in the foreground, superimposed over a column chart in the background. This is what is termed a "multi-plot" chart in the python-pptx documentation.

**Comment by sabya14** [comment]
Can you share a way through which we can put two charts in a single row side by side?
For now, I am using a table, with a single row having two columns and inserting two charts there.
But this breaks my purpose because the end user is ultimately interacting with a table

**Comment by scanny** [comment]
Just put them side by side. There's nothing stopping you placing more than one chart on a single slide. If you want the template to determine their locations, use two chart placeholders side by side.
