### ISSUE TITLE
feature: generate TexPoint objects? 

### ISSUE THREAD

**Issue by hkarl** [scanny/python-pptx#156]
Hi, 

wonderful tool! I'm currently using it to turn emacs org-mode files into powerpoint slides. (Roughly inspired by org-mode's export to latex beamer classes.)  

Main stumbling block are wonderful use case: would it be possible to create texpoint objects in ppt? That way, all latex formulas could be nicely turned into texpoint and typeset correctly. http://texpoint.necula.org/ - it looks like an abandoned project, but it still works fine. 

thanks a lot, 

Holger

**Comment by nilswagner** [comment]
+1

**Comment by scanny** [comment]
TexPoint is not open-source, so couldn't be incorporated in the build. I expect you'd have to work out some sort of external integration for it. I'm open to reopening this if someone has ideas how it could be done, or perhaps accomplished using a different library. I'd personally love to have Latex in PowerPoint and I'm sure the scientific and engineering user base would too.
