### ISSUE TITLE
Squiggle issue

### ISSUE THREAD

**Issue by joereddington** [scanny/python-pptx#157]
Sorry for the continued bug reports - at least this one isn't blocking :)  Also there's an outside chance I'm learning enough about the codebase to put together pull requests.... 

Anyway.  Given this file: https://www.dropbox.com/s/grjxey1roley4ig/Presentation1.pptx?dl=0  (specifically the illustration under 'foggy') and the following code. 
```
#!/usr/bin/python
from pptx import Presentation
from pptx.enum.shapes import MSO_SHAPE_TYPE

def slide_title_placeholder(slide):
	"""from https://github.com/scanny/python-pptx/issues/153#issuecomment-84475019"""
	for shape in slide.shapes:
		if not shape.is_placeholder:
			continue
		if shape.placeholder_format.idx == 0:
			return shape
		return None

def make_title(label):
    return label.lower().strip().replace(" ","_")


prs = Presentation("testSuite/bugs/Presentation1.pptx")
for slide in prs.slides:
    title=slide_title_placeholder(slide)
    print "%s" % make_title(title.text)
```
I get the error. 
```
Josephs-MacBook-Pro$./reduce.py 

Traceback (most recent call last):
  File "./reduce.py", line 24, in <module>
    print "%s" % make_title(title.text)
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by scanny** [comment]
As I mentioned in the the other issue where I gave you the slide_title_placeholder() code, you need to test for `None` as a legitimate return value from `slide_title_placeholder()`. Not all slides have a title placeholder, notably a slide created from the "Blank Slide" slide layout will not have one. Also the title placeholder can be deleted, which will have the same effect.
https://github.com/scanny/python-pptx/issues/153#issuecomment-84475019

**Comment by joereddington** [comment]
Damnit - the more convinced I am that something is a bug the less likely it
is... sigh...

On 30 March 2015 at 22:09, Steve Canny <notifications@github.com> wrote:

> As I mentioned in the the other issue where I gave you the
> slide_title_placeholder() code, you need to test for None as a legitimate
> return value from slide_title_placeholder(). Not all slides have a title
> placeholder, notably a slide created from the "Blank Slide" slide layout
> will not have one. Also the title placeholder can be deleted, which will
> have the same effect.
> #153 (comment)
> <https://github.com/scanny/python-pptx/issues/153#issuecomment-84475019>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scanny/python-pptx/issues/157#issuecomment-87832183>.
>



-- 

Dr Joe Reddington
joereddington.com
