### ISSUE TITLE
docs: update documentation to reflect CategoryPoints and Marker

### ISSUE THREAD

**Issue by linzhong** [scanny/python-pptx#158]
Is there any way that I can change the default pie and bar chart color theme and make it different color and solid filling? 

Thanks,

**Comment by scanny** [comment]
The color used for the data points in a chart series is determined by the theme of the presentation. It is not defined directly in the chart unless it is set explicitly to override the theme color.

The first series receives the *Accent 1* color, the second receives *Accent 2*, and so on. When the six accent colors are exhausted, a variant of each color (initially a lighter tint) is used in the same sequence.

So the most straightforward method of changing chart colors is to change the theme color palette of the starting presentation, (i.e. template .pptx file).

**Comment by linzhong** [comment]
Thanks for clarification and the tips. It is very helpful!

On Wed, Apr 1, 2015 at 10:00 PM, Steve Canny <notifications@github.com>
wrote:

> The color used for the data points in a chart series is determined by the
> theme of the presentation. It is not defined directly in the chart unless
> it is set explicitly to override the theme color.
>
> The first series receives the *Accent 1* color, the second receives *Accent
> 2*, and so on. When the six accent colors are exhausted, a variant of
> each color (initially a lighter tint) is used in the same sequence.
>
> So the most straightforward method of changing chart colors is to change
> the theme color palette of the starting presentation, (i.e. template .pptx
> file).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scanny/python-pptx/issues/158#issuecomment-88735570>.
>



-- 
*Lin Zhong  *

---

Applause gets ​​Three Straight Years as one of Forbes’ Most Promising
Companies <http://www.applause.com/awards>

**Comment by scanny** [comment]
Glad to hear it :)

It is also possible to explicitly set the fill color on some chart types. Look for a `.fill` property on the `Series` object, such as this one for a `BarSeries` (used on bar and column charts):
http://python-pptx.readthedocs.org/en/latest/api/chart.html#pptx.chart.series.BarSeries.fill

Also, this short section in the documentation discusses  series color:
http://python-pptx.readthedocs.org/en/latest/user/charts.html#about-colors

**Comment by linzhong** [comment]
Is this only for bar charts? I don't find one for Pie charts series. Or is
BarSeries also apply for pie chart as well?


On Thu, Apr 2, 2015 at 1:58 PM, Steve Canny <notifications@github.com>
wrote:

> Glad to hear it :)
>
> It is also possible to explicitly set the fill color on some chart types.
> Look for a .fill property on the Series object, such as this one for a
> BarSeries (used on bar and column charts):
>
> http://python-pptx.readthedocs.org/en/latest/api/chart.html#pptx.chart.series.BarSeries.fill
>
> Also, this short section in the documentation discusses series color:
> http://python-pptx.readthedocs.org/en/latest/user/charts.html#about-colors
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scanny/python-pptx/issues/158#issuecomment-89042985>.
>



-- 
*Lin Zhong  *

---

Applause gets ​​Three Straight Years as one of Forbes’ Most Promising
Companies <http://www.applause.com/awards>

**Comment by scanny** [comment]
Pie charts are actually a special case. They can be thought of as having a single series.

In any case, you're right, there is no fill property implemented for Pie charts yet. When there is, it will have to be on individual points, not on the series, since each data point in the single pie series will need a contrasting color.

**Comment by linzhong** [comment]
I see.

Thanks,

On Thu, Apr 2, 2015 at 3:26 PM, Steve Canny <notifications@github.com>
wrote:

> Pie charts are actually a special case. They can be thought of as having a
> single series.
>
> In any case, you're right, there is no fill property implemented for Pie
> charts yet. When there is, it will have to be on individual points, not on
> the series, since each data point in the single pie series will need a
> contrasting color.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scanny/python-pptx/issues/158#issuecomment-89063612>.
>



-- 
*Lin Zhong  *

---

Applause gets ​​Three Straight Years as one of Forbes’ Most Promising
Companies <http://www.applause.com/awards>

**Comment by bengtberg** [comment]
I'm still puzzled by the hints that indicidual coloring IS possible. I've seen some of the shading.elm tricks for python-docx, they are way above my pythonic capacity even though I have managed to make it work for coloring fields in docx tables. 

For me, template-provided coloring doesn't cut it. I need to visualize reports on data originating from another system where data is associated with colors. It will be confusing if the number of G records are visualized with Green in the mother system, but with blue in my reports. 

So, being able to color the pie sector corresponding to G to green would be truly great. Suggestions appreciated. 

`    slide = prs.slides.add_slide(prs.slide_layouts[layout])
    slide.shapes.title.text = header + ' (' + count_type + ')'

    # Fetch the data 
    chart_data = ChartData()
    categoriesList = answerCodes
    numericList = []
    total = 0

    for i in categoriesList:
        numericList.append(snapShot.gTemplateGlobalAnswerStatistics['oaq'][i])

    # Make and place the pie chart
    chart_data.categories = ['G', 'R', 'P', 'B']
    chart_data.add_series("OAQ Answer Codes", [23, 43, 11, 31])
    x, y, cx, cy = Inches(1), Inches(1), Inches(7), Inches(4)
    chart_AllData = slide.shapes.add_chart(XL_CHART_TYPE.PIE, x, y, cx, cy, chart_data).chart

    print(chart_AllData)
    # Define look&feel
    chart_AllData.has_legend = True
    chart_AllData.legend.include_in_layout = True
    chart_AllData.legend.font.color.rgb = RGBColor(0,0,0)
    chart_AllData.plots[0].has_data_labels = True
    data_labels_AllData = chart_AllData.plots[0].data_labels
    data_labels_AllData.number_format = count_type
    data_labels_AllData.position = XL_LABEL_POSITION.OUTSIDE_END
    data_labels_AllData.font.color.rgb = RGBColor(0,0,0)

`

**Comment by scanny** [comment]
I think the access you would be looking for would be something like this:

```python
pie_plot = chart.plots[0]
pie_slices = pie_plot.series[0].points
for slice in pie_slices:
    fill = slice.marker.format.fill
    fill.solid()
    fill.fore_color.rgb = RGBColor(mycolor)
```

And it looks like the code is there, although not quite properly represented in the documentation.

Why don't you give this a try and see if it works. Let us know how you go and we'll get the documentation updated.

**Comment by bengtberg** [comment]
OK, just setting ALL colors to FFFFFF to just validate that colors are set. 

`    x, y, cx, cy = Inches(1), Inches(1), Inches(7), Inches(4)
    chart_AllData = slide.shapes.add_chart(XL_CHART_TYPE.PIE, x, y, cx, cy, chart_data).chart

    print(chart_AllData)
    '''
    fill = shape.fill
    fill.solid()
    fill.fore_color.rgb = RGBColor(255, 0, 0)
    '''
    pie_plot = chart_AllData.plots[0]
    pie_slices = pie_plot.series[0].points
    for slice in pie_slices:
        fill = slice.marker.format.fill
        fill.solid()
        fill.fore_color.rgb = RGBColor('#FFFFFF')
`

got the following error message: 

`Traceback (most recent call last):
  File "/Users/bengtberg/Documents/CCP Powerpoint Reporter/pptx_reporter.py", line 174, in <module>
    pie_chart_page(prs, currentSnapshot, ['G', 'B', 'P', 'R'], 7, 'number', 'All Answer Codes')
  File "/Users/bengtberg/Documents/CCP Powerpoint Reporter/pptx_reporter.py", line 74, in pie_chart_page
    pie_slices = pie_plot.series[0].points
AttributeError: 'PieSeries' object has no attribute 'points'
>>> `

**Comment by bengtberg** [comment]
...and never mind the ''' stuff above, that's just remains from some previous tests :-)

**Comment by scanny** [comment]
What version of `python-pptx` are you running? These features were added relatively recently and there shouldn't usually be any reason to run on anything but the latest.

**Comment by bengtberg** [comment]
Latest, greatest, I believe. pip looks happy when trying to install again. 

Bengt-Bergs-MacBook-Pro:Gen4_Reporter bengtberg$ pip3.5 install python-pptx
Requirement already satisfied: python-pptx in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages
Requirement already satisfied: lxml>=3.1.0 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from python-pptx)
Requirement already satisfied: Pillow>=2.6.1 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from python-pptx)
Requirement already satisfied: XlsxWriter>=0.5.7 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from python-pptx)

**Comment by scanny** [comment]
what does `pip freeze` have to say as far as version is concerned.

**Comment by bengtberg** [comment]
Thanks, you might have nailed it. python-pptx==0.5.8
Strange that it doesn't upgrade over pip?

**Comment by scanny** [comment]
`pip` only upgrades if you tell it to.

**Comment by scanny** [comment]
or if you provide a particular revision spec, like `>0.5.0`.

**Comment by bengtberg** [comment]
Thanks, Steve. I recognize this git is NOT a newbie python tutorial place, so I highly appreciate your help with these issues. Whenever you come to Stockholm, let me buy you a beer :-) 

Still, it now executes nicely... but the pie chart looks as ever. 

    chart_data.categories = ['G', 'R', 'P', 'B']
    chart_data.add_series("OAQ Answer Codes", [23, 109, 33, 41])
    
    x, y, cx, cy = Inches(1), Inches(1), Inches(7), Inches(4)
    chart_AllData = slide.shapes.add_chart(XL_CHART_TYPE.PIE, x, y, cx, cy, chart_data).chart

    pie_plot = chart_AllData.plots[0]
    pie_slices = pie_plot.series[0].points
    for slice in pie_slices:
        fill = slice.marker.format.fill
        fill.solid()
        fill.fore_color.rgb = RGBColor(0xff , 0xff , 0xff)

**Comment by scanny** [comment]
Ok, well it looks like pie charts don't use the marker to set the slice color. We'll have to have a closer look at the XML. What I recommend is to make a single slide presentation with a single pie chart in it, and then change the colors of the individual slices to something easy to identify, like pure red, green, and blue.

Then we need to look at the XML. I recommend `opc-diag` and using that with a command line like this:

```bash
$ opc browse my-test.pptx chart1.xml
```

If you paste the results in here I'll have a look.

**Comment by bengtberg** [comment]
Right now I will go to bed - midnight in Sweden now. But I'll be back :-)

**Comment by scanny** [comment]
Ok, I just took a quick look, try this instead:

```python
for slice in pie_slices:
    fill = slice.format.fill
    fill.solid()
    fill.fore_color.rgb = RGBColor(0xff , 0xff , 0xff)
```

Looks like the Pie chart structures doesn't use the `.marker` attribute and just considers the whole point to be the slice.

**Comment by bengtberg** [comment]
OK, HERE'S THE DEAL. 

I will reach over to you on LinkedIn, and you will accept my invitation. Then, whenever you're in Stockholm, I'll buy you a couple of beers or whetever. Offer stands indefinetly. 

This worked splendidly!

**Comment by bengtberg** [comment]
Couldn't find you. Well, this is me. 
https://www.linkedin.com/in/bengt-berg-7191366
