### ISSUE TITLE
Error while installing python-pptx

### ISSUE THREAD

**Issue by oisaadat** [scanny/python-pptx#161]
I was trying to install python-pptx on my Python 3.4 and I got the following error:

error: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).
I used pip to start the install and I am using a Windows 7 x64 machine.  Does anyone know how to resolve this issue?
pip install python-pptx

**Comment by scanny** [comment]
You need to install the lxml package and perhaps Pillow separately on Windows. The error you're getting is when it's looking for a C compiler. Search for 'lxml binary installer'

http://www.lfd.uci.edu/~gohlke/pythonlibs/

**Comment by oisaadat** [comment]
Thank you
