### ISSUE TITLE
Space at top of text_frame

### ISSUE THREAD

**Issue by apiszcz** [scanny/python-pptx#162]
When creating text box I am seeing a large vertical white space at the top of each text box. I tried setting _margin_top=0 but with no success, the space persists, it almost seems like a 20 or 24 point empty line or newline.. Is there a way to remove this gap or extra line at the beginning of a text frame. Example picture attached. Thank you.

![capture](https://cloud.githubusercontent.com/assets/1430861/7217093/ce54a274-e5e5-11e4-87e4-1fde497bad66.JPG)

**Comment by apiszcz** [comment]
The space at the top of the paragraph is an 18 pt Calibri blank line

**Comment by hoopes** [comment]
Hi,

This has gotten me once or twice, maybe it's your issue.

When you have a textframe, it always has a paragraph by default. I suppose this is where the text goes if you do 

    tf.text = 'some text'

 So if you add a paragraph to the frame, now you're on the second one.

I often do:


    textframe.clear()
    p = textframe.paragraphs[0]
    p.text = 'whatever'
    ...etc...

That might be your phantom line.

**Comment by apiszcz** [comment]
Thank you for the reply. I tried the clear(). and my code fragment looks
very similar, still seeing the Calibri 18 point item. I also checked
space_before, etc which are set to None. It may also just be the spacing
for the textframe? When I paste the text frame into MS WORD there is no
extra space.
​

**Comment by scanny** [comment]
This is covered in the documentation here:
http://python-pptx.readthedocs.org/en/latest/user/text.html#accessing-paragraphs

**Comment by anix-anirban** [comment]
I am facing the same issue. `text_box.text_frame.clear( )` doesn't remove that space (of font size 18) in the beginning. But, if I add a text by `text_frame.text = 'TEST'`, the text is appearing instead of the space. Unfortunately I cannot format that text (color, alignment, font size, etc.). Formatting is possible only on paragraphs (`text_frame.add_paragraph( ).text('paragraph text')`. Please help with a solution to remove that space. TIA.

**Comment by marco-racanelli** [comment]
I managed to solve it by not adding `p = tf.add_paragraph()`.

Instead, for the first paragraph I simply did `p = tf.paragraphs[0]`. Even without the `tf.clear()`.
Therefore what @hoopes suggested here worked well for me.
