### ISSUE TITLE
feature: Picture.crop_x setters

### ISSUE THREAD

**Issue by oisaadat** [scanny/python-pptx#163]
I tried to crop an image in python pptx by executing the following commands:

```
    pic = slide.shapes.add_picture(img_path, left, top, height=height)
    pic.crop_left(0.1)
```

However, I got the following error:
'float' object is not callable

Then, I tried the following
pic.crop_left = 0.1

but I got the following error
AttributeError: can't set attribute

Is it possible to crop images by using crop_left or can I only use it to see if the image is cropped.  Fr example, when executing pic.crop_left, I do see that the value is 0

**Comment by scanny** [comment]
crop_left is currently read-only.

**Comment by diwu1989** [comment]
why dont you just use PILLOW and process the cropping on the source image directly?

**Comment by hchen06** [comment]
is it possible to remove/delete cropped area after powerpoint_scaling_cropping?
I know I can use get_image in python-pptx, but, how to call the PILLOW function with image objects of python-pptx?

**Comment by jbmcgavock** [comment]
Are the pic.crop features meant to be changed?

**Comment by scanny** [comment]
@jbmcgavock Not getting your question. Can you elaborate?

**Comment by jbmcgavock** [comment]
I am having a hard time getting the pic.crop_bottom to work.  
I have tried pic.crop_bottom(0.50) and pic.crop_bottom = 0.5 with both returning errors.
I also tried setattr function without any success.  Can you please provide guidance on the proper usage.
Thanks.

**Comment by scanny** [comment]
The crop properties are all read-only so far.

**Comment by Avocado1234** [comment]
Any predictions of when crop feature will be active?  Thanks.

**Comment by scanny** [comment]
Picture crop setters were added in release 0.6.9 on Wed May 9, 2018.
