### ISSUE TITLE
Feature Clarification: reading hyperlinks

### ISSUE THREAD

**Issue by joereddington** [scanny/python-pptx#164]
In the file https://www.dropbox.com/s/az0zsl67ilykjjg/example.pptx?dl=0  - there are two shapes with hyperlinks: one to a slide and one to a URL.  Can either be **read** by python-pptx?   It's a little unclear between http://python-pptx.readthedocs.org/en/latest/dev/analysis/features/txt-hyperlink.html and https://groups.google.com/forum/#!topic/python-pptx/et-q2xbb9GI if the code is in the repo? 

(Also, if there is a hacky way to just read a slide link, that would be fine) 

Thanks.

**Comment by scanny** [comment]
Hi Joe, as I recall, this feature is somewhere in partial implementation status, probably most suitable for writing a hyperlink rather than reading.

A Run object has a read-only `hyperlink` property that provides a _Hyperlink object. _Hyperlink.address will be None if there is no actual hyperlink (hlinkClick element) present. So you should be able to detect hyperlinks by testing the address property. If you get something it will be the address, at least in the case of a URL. Not sure exactly what you get if it's an internal link to a different slide.

So something like this air code I imagine:

```python
shape = ... shape you want to look in
for paragraph in shape.text_frame.paragraphs:
    for run in paragraph.runs:
        hyperlink = run.hyperlink
        if hyperlink.address is not None:
            print(hyperlink.address)
```

Let us know how you go and where it falls short if it does, you can probably get further by going down to the lxml layer from hyperlink to get more. Once you have some partially working code we can help point you in the right direction.

**Comment by joereddington** [comment]
Hi, 

I did some checking - I'm actually looking for hyperlinks on the shapes rather than the text boxes (I genuinely didn't know that the text boxes could be links...) and my rough code: 
'''
   for shape in slide.shapes:
        hyperlink = shape.hyperlink
        if hyperlink.address is not None:
            print(hyperlink.address)
'''
tells me that there shapes lack the same attribute - does this mean that python-pptx doesn't support them? Will be very sad if so... :(

**Comment by joereddington** [comment]
So I've explored a little more, part of this will be a bug report (which I can happily spin out into its own issue) 

Given the code
```
#!/usr/bin/python
from pptx import Presentation

prs = Presentation("testSuite/example.pptx")

for slide in prs.slides:
    for shape in slide.shapes:
        try:
            text = ""
            for paragraph in shape.text_frame.paragraphs:
                for run in paragraph.runs:
                    text += run.text.encode('ascii',
                                            'ignore')
                    hyperlink = run.hyperlink
                    if hyperlink.address is not None:
                        print("Address", hyperlink.address)
            print text
        except NotImplementedError:
            pass
```

and the presentation : https://www.dropbox.com/s/kyzyzr1vgaceye0/example.pptx?dl=0
The urls that are part of *text* rather than a *shape* are identified correctly. As long as they are URLS! If they are are hyperlinks to another part of the file we have 

``` 
Traceback (most recent call last):
  File "./grab_text.py", line 120, in <module>
    if hyperlink.address is not None:
  File "/Library/Python/2.7/site-packages/python_pptx-0.5.7-py2.7.egg/pptx/text/text.py", line 415, in address
    return self.part.target_ref(self._hlinkClick.rId)
  File "/Library/Python/2.7/site-packages/python_pptx-0.5.7-py2.7.egg/pptx/opc/package.py", line 320, in target_ref
    rel = self.rels[rId]
KeyError: ''
```
Because the rId is blank at that point.  

For debugging purposes, I altered the target_ref function as follows 

```
def target_ref(self, rId):                                                   
315       try:                                                                       
316         """                                                                      
317         Return URL contained in target ref of relationship identified by         
318         *rId*.                                                                   
319         """                                                                      
320         rel = self.rels[rId]                                                     
321         print "Dictionary"                                                       
322         for key in self.rels:                                                    
323            print key, 'corresponds to', self.rels[key].target_ref                
324         return rel.target_ref                                                    
325       except KeyError:                                                           
326         return "No to look up with"   
```
Obviously it now swallows the exception just to keep me moving, but it also prints out the content of the dictionary: 
```
Dictionary
rId5 corresponds to http://google.com
rId4 corresponds to https://www.dropbox.com/home
rId3 corresponds to http://joereddington
rId2 corresponds to slide1.xml
rId1 corresponds to ../slideLayouts/slideLayout6.xml
```
Which shows that the hyperlinks to slides are definitely in there, as are the hyperlinks from shapes.  

So, the thing I'm now curious about is: is the 'Keyerror' issue a bug? Also - given I think I can hack my way to the rels link information, is there a way of say, getting the xml that corrasponds to a shape so I can hack my way to the link? 

Thanks in advance - I'm aware we're both dealing with this sort of thing in our spare time :) 

J

**Comment by joereddington** [comment]
Hi Mark, can I bump this a little bit? I'm aware you are busy with other things at the moment but I wanted to try and stay on the radar...

**Comment by scanny** [comment]
Added in v0.5.8.
