### ISSUE TITLE
Copy data from xlsx file to chart

### ISSUE THREAD

**Issue by cacrespo** [scanny/python-pptx#166]
Hi;
I have a chart with colours and specific format in a PowerPoint document. 
Is any way to copy range from a xlsx file and paste in cell 1,1 of chart??

thanks a lot!

Carlos
ps: sorry for my english

**Comment by scanny** [comment]
I can't make out what outcome you're trying to achieve. Can you provide more details and an example?

The .xlsx "file" embedded in a PowerPoint file is accessible. I'm not sure what you mean by "cell 1, 1 of chart". Charts don't have cells as far as I know.

**Comment by cacrespo** [comment]
The .xlsx is a file in my disk.
When I open a chart, I have an excel worksheet. I want to copy from an excel file and paste in the graph.

Muchas gracias por la respuesta. Espero que se entienda. Más tarde escribo con detalle.
Saludos,

Carlos
-----Original Message-----

**Comment by scanny** [comment]
Assuming you got this worked, so closing for now. This sort of support question is probably best posted on StackOverflow and using the `python-pptx` tag.
