### ISSUE TITLE
IndexError: slide layout index out of range

### ISSUE THREAD

**Issue by geracen** [scanny/python-pptx#167]
Hi,

I have a slide deck with 10 slide layouts and 1 slide master.

Strange thing is I cannot access the slide_layouts as they appear in Powerpoint.

>from pptx import Presentation
>from pptx.enum.chart import XL_CHART_TYPE
>from pptx.util import Inches
>from pptx.chart.data import ChartData
>
>prs = Presentation('deck.pptx')
>slide = prs.slides.add_slide(prs.slide_masters[0].slide_layouts[8])
>
>for shape in slide.shapes:
>   print('%s' % shape.shape_type)

I get IndexError: slide layout index out of range

Any ideas? I guess there is something so obvious I'm missing here.

**Comment by scanny** [comment]
The index error is coming from the line:

    slide = prs.slides.add_slide(prs.slide_masters[0].slide_layouts[8])

I expect you'll find you have a different number of masters/layouts than you think.

I would start by checking the len of each:

```python
print(len(prs.slide_masters))
for slide_master in prs.slide_masters:
    print(len(slide_master.slide_layouts))
```
