### ISSUE TITLE
feature/bug:  add_picture/from_file probably should not seek(0)

### ISSUE THREAD

**Issue by buzzm** [scanny/python-pptx#170]
image.py: 169 has this
```
            # assume image_file is a file-like object                                    
            image_file.seek(0)                                                          
            blob = image_file.read()
            filename = None
```
The problem is not all file-like objects support seek() (as documented in the main python docs).   In particular, URL readers that present file-like objects error out on seek():
````
    r = urllib2.urlopen("http://whatever")
    pic = shapes.add_picture(r, 0, 0)
````
Is there a strong reason to seek(0)?   Seems like the caller should be responsible for positioning the stream to be read() by from_file, no?

**Comment by diwu1989** [comment]
if someone is sending in a file-like object that is already fully read, then it should be the caller's responsibility to reset the reader

**Comment by scanny** [comment]
seek(0) removed in version 0.5.8.
