### ISSUE TITLE
Open existing pptx file

### ISSUE THREAD

**Issue by sobolewska** [scanny/python-pptx#173]
python-pptx 0.5.7
Python 2.7.8

Currently using
```
f = open('C:\some_folder\my_file.pptx')
prs = Presentation(f)
f.close()
```
gives error: File is not a zip file

using
```
prs = Presentation('C:\\some_folder\\my_file.pptx')
```
gives error: Package not found at 'C:\some_folder\my_file.pptx'

full stack traces below:
```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\IPython\core\interactiveshell.py", line 3035, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-78857122896f>", line 2, in <module>
    prs = Presentation(f)
  File "C:\Python27\lib\site-packages\pptx\api.py", line 26, in __init__
    self._package = Package.open(pkg_file)
  File "C:\Python27\lib\site-packages\pptx\package.py", line 44, in open
    return super(Package, cls).open(pkg_file)
  File "C:\Python27\lib\site-packages\pptx\opc\package.py", line 122, in open
    pkg_reader = PackageReader.from_file(pkg_file)
  File "C:\Python27\lib\site-packages\pptx\opc\pkgreader.py", line 32, in from_file
    phys_reader = PhysPkgReader(pkg_file)
  File "C:\Python27\lib\site-packages\pptx\opc\phys_pkg.py", line 102, in __init__
    self._zipf = ZipFile(pkg_file, 'r')
  File "C:\Python27\lib\zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "C:\Python27\lib\zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
```
```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\IPython\core\interactiveshell.py", line 3035, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-4fbcdf1972de>", line 1, in <module>
    prs = Presentation('C:\\some_folder\\my_file.pptx')
  File "C:\Python27\lib\site-packages\pptx\api.py", line 26, in __init__
    self._package = Package.open(pkg_file)
  File "C:\Python27\lib\site-packages\pptx\package.py", line 44, in open
    return super(Package, cls).open(pkg_file)
  File "C:\Python27\lib\site-packages\pptx\opc\package.py", line 122, in open
    pkg_reader = PackageReader.from_file(pkg_file)
  File "C:\Python27\lib\site-packages\pptx\opc\pkgreader.py", line 32, in from_file
    phys_reader = PhysPkgReader(pkg_file)
  File "C:\Python27\lib\site-packages\pptx\opc\phys_pkg.py", line 32, in __new__
    "Package not found at '%s'" % pkg_file
PackageNotFoundError: Package not found at 'C:\some_folder\my_file.pptx'
```

**Comment by mfellows** [comment]
For the first method, using a file-like object, you need to open the file in binary mode:
```python
f = open(r"C:\some_folder\my_file.pptx", "rb")
prs = Presentation(f)
```

Not sure why the second one (using the file path) failed though - double-check that the file exists?

**Comment by sobolewska** [comment]
Nope, still the same error "File is not a zip file"

**Comment by sobolewska** [comment]
also for the record, in meantime i also made sure to meet requirements: https://github.com/scanny/python-pptx/blob/master/requirements.txt

**Comment by finitecow** [comment]
the second problem is caused by opening too much (>20) Presentation and not close them

**Comment by fakabbir** [comment]
I have the same error and it doesn't resolves via adopting the mentioned solutions.
```
prs = Presentation('C:\\some_folder\\my_file.pptx')
f = open('C:\\some_folder\\my_file.pptx', 'rb')
Presentation(f)
f.close()
```
**still gives error even with non empty ppt.**
`prs = Presentation('C:\\some_folder\\my_file.pptx')`
**gives Package not found erro**r.

**Comment by scanny** [comment]
`Package not found` also occurs when the target file is the old PPT format, the pre-2007 PowerPoint format. If you open one like that with PowerPoint then save as PPTX it normally fixes it.

**Comment by ruiyuanlu** [comment]
I've met the same issues.

**Comment by ruiyuanlu** [comment]
@fakabbir You mean using file handler rather than file path? I met this issue when I simply created pptx files using:
```python
open('test.pptx', 'w').close()
```
and then tried to reopen it using:
```python
prs = Presentation('test.pptx')
```
Under this circumstances, the error is 'Package not found'.
I also tried file handler, which gives error: 'File is not a zip file'.
```python
open('test.pptx', 'w').close()
with open('test.pptx') as f:
    pptx.Presentation(f)
```

Python 3.6
Windows 10
python-pptx 0.6.12

**Comment by scanny** [comment]
@ruiyuanlu An empty file is not a PPTX file. A PPTX file is a zip archive with a prescribed set of contents.

An "empty" PPTX file is simply one that has no slides. It does still however have quite a bit of content, like the slide masters, theme, slide layouts, etc.

`python-pptx` can only operate on PPTX files. Calling `Presentation()` with no parameters causes an internal default template PPTX file to be opened. You can create your own starting template by taking the PPTX file of your choice and deleting all its slides and saving it.

You may want to spend some time with the documentation here that explains these concepts: https://python-pptx.readthedocs.io/en/latest/user/presentations.html

**Comment by AntonioVentilii** [comment]
Presentations(path) is not working for any type of .pptx

**Comment by sangeethavenkatesan** [comment]
I still see the issue, pptx.exc.PackageNotFoundError: Package not found at  {path}/text.pptx'.
text.pptx has one slide with title, which am using it as a theme, program adds new slide. Not sure how to fix this error. Please suggest
