### ISSUE TITLE
Install error (Mac)

### ISSUE THREAD

**Issue by ajfarkas** [scanny/python-pptx#179]
I've tried installing python-pptx with both `pip` and `easy_install`, and both throw the same error:

````
In file included from src/lxml/lxml.etree.c:239:
/tmp/easy_install-GPyF3s/lxml-3.4.4/src/lxml/includes/etree_defs.h:14:10: fatal error: 'libxml/xmlversion.h' file not found
#include "libxml/xmlversion.h"
````
above is `easy_install`, below is `pip`:
````
/private/var/folders/p7/306cr1rx3lv33kvsw_96qgb80000gp/T/pip-build-hpma6h/lxml/src/lxml/includes/etree_defs.h:14:10: fatal error: 'libxml/xmlversion.h' file not found
````
I'm running OS 10.10.5, and Py 3.4.3, for reference. Help!

**Comment by rday** [comment]
If you use brew you can install libxml2
 `brew install libxml2`

My libxml2 package has the xmlversion.h file listed under it.

**Comment by ajfarkas** [comment]
This is tremendously stupid, but I get the same err when trying to install `libxml`.

Thanks for your quick repsonse.

**Comment by scanny** [comment]
You'll need both `libxml2` (note the '2' at the end) and `libxslt` as dependencies for `lxml`. You may want to search on "mac install lxml" and "mac install libxml2 libxslt". Until you get lxml installed correctly, python-pptx won't work. You'll need to get to the point where this line executes from the terminal without an ImportError:

```bash
$ python -c 'import lxml'
```

I had thought that a suitable version of both `libxml2` and `libxslt` came installed by default on OS X but it's been awhile and I can't say I've tried it on 10.10.
