### ISSUE TITLE
Bounty on Feature: $400 for reading links on shapes

### ISSUE THREAD

**Issue by joereddington** [scanny/python-pptx#182]
Hi everybody, 

We've got a small budget to pay for some development on this project - please let me know if you are interested. 

**Background**

We're currently in the middle of building a communications device to help disabled children communicate (You can find out a bit more at this TEDx we did: https://www.youtube.com/watch?v=U0nJN5Tddx0).  We're letting parents and carers build templates in PowerPoint and then we use python-pptx library to convert them into free webapps like this one: http://communikate.joereddington.com/ck15/

It's an amazing little project and it's really changing lives, and the python-pttx library has made it possible.

**What we need** 
We have a small problem though - ideally parents and carers would be able to link each button on the PowerPoint to the relevant page - that would let us have some quite sophisticated behaviours. Unfortunately the python-ppty library doesn't support reading links to slides. (I think Steve said in May that it was 'partially implemented' https://github.com/scanny/python-pptx/issues/164 , and https://groups.google.com/forum/#!topic/python-pptx/et-q2xbb9GI seems to imply it's a pretty easy fix)

We've got a way of getting around it, but it needs some human intervention and that's obviously NOT ideal (although it makes it a lot easy to produce translations).

We've been funded by http://www.nesta.org.uk/project/inclusive-technology-prize and can over some of our development funding as a bounty. We just need to be able to read links from shapes.  Is anyone interested?

Joe

**Comment by scanny** [comment]
Hi Joe,

I think I can swing this for you.

Want to have a quick call so I can understand a bit more about the technical context? Basically walking through how your code will do what it does and narrowing down what bit of the API is missing.

You can reach me directly at stcanny at gmail.com

**Comment by joereddington** [comment]
Hi Steve,

Lovely to hear from you.  A call would be wonderful. My Skype is
joseph.reddington - when would be good for you? I'm around for roughly the
next five hours of today and the same slot Thursday...   would that work?
I'm aware there's a significant time difference...

J

On 6 October 2015 at 15:05, Steve Canny <notifications@github.com> wrote:

> Hi Joe,
>
> I think I can swing this for you.
>
> Want to have a quick call so I can understand a bit more about the
> technical context? Basically walking through how your code will do what it
> does and narrowing down what bit of the API is missing.
>
> You can reach me directly at stcanny at gmail.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scanny/python-pptx/issues/182#issuecomment-145866062>.
>



-- 

Dr Joe Reddington
joereddington.com

**Comment by diwu1989** [comment]
this is related to https://github.com/scanny/python-pptx/issues/61

I need both read + write abilities, we have hacked up code to do write right now, read shouldn't be hard

**Comment by scanny** [comment]
@diwu1989 Can you share your hacked-up code? I'm putting the finishing touches on the read side here and wanted the benefit of seeing what you'd done. I'm considering adding the write side since I'm already in there and it looks like a fairly modest incremental effort.

**Comment by scanny** [comment]
Completed and checked in to develop. Will release with v0.5.8 shortly.
