### ISSUE TITLE
Using Unicode characters in e.g. SliceTitle.text

### ISSUE THREAD

**Issue by asalinasl** [scanny/python-pptx#183]
Hi,

i'm relative new with python-pptx but my issue is quite simple -I guess :-S 
I hope you can help me.

I want to show the diameter symbol in the title of my  slide and with the following code I obtain the question mark '?' instead of the diameter sign.

  from __future__ import print_function
  from pptx import Presentation

  prs = Presentation('my_empty.pptx')
  blank_slide_layout = prs.slide_layouts[2]
  slide = prs.slides.add_slide(blank_slide_layout)
  SliceTitle = slide.shapes.title
  diameter_sign=unichr(8960)
  diameter_sign_for_output=diameter_sign.encode('ascii', 'replace')
  SliceTitle.text ='Pin {}'.format(diameter_sign_for_output) 

What am I doing wrong?

Thanks in advance

Alfredo

**Comment by scanny** [comment]
I think your problem is with getting a Unicode string that contains the character you want, not with getting that string into python-pptx.

I suggest starting with a search on 'python unicode'. I know it's a bit of a confusing subject, at least it was for me when I first encountered it.
