### ISSUE TITLE
How to change the language of a specific text-box (shape)

### ISSUE THREAD

**Issue by wernertoonk** [scanny/python-pptx#187]
Hi,

How to change the language of a shape in a presentation with python-pptx? I can't find any property for shapes.text_frame to set its language...

Kind regards,

Werner

**Comment by scanny** [comment]
There's no API property for this just yet; you'd have to go down to the lxml level I expect.

I don't know off hand how it's set in the XML, but if I wanted to find out I would compare XML from two presentations, one with language set and the other without.

You would want the test presentation to contain as little as possible; say one slide containing only the text box. Create it without setting the language and save. Change the language and save as a different name. Then you can use opcdiag to compare the slide1.xml part.
http://opc-diag.readthedocs.org/en/latest/quickstart.html#use-case-3-diff-a-part-between-two-office-documents

The command would look something like:
```bash
opc diff-item before.pptx after.pptx slide1.xml
```

**Comment by scanny** [comment]
Added Font.language_id with v0.6.0 release uploaded to PyPI today.
