### ISSUE TITLE
text_frame.vertical_anchor not working

### ISSUE THREAD

**Issue by daermonn** [scanny/python-pptx#191]
First, thanks so much for this module, it's a huge help.

**EDIT:** I figured it out about 5 minutes after posting this... Turns out I should have been writing cell.vertical_anchor = 3 instead of cell.text_frame.vertical_anchor = 3. Not sure why it doesn't work on the text_frame, but whatever. Sorry for the unnecessary question, and thanks for all your work!

I'm trying to format a table so that the column headers are centered horizontally and vertically, but the vertical anchoring has no effect. 

I've tried using:
```python
cell.text_frame.vertical_anchor = MSO_VERTICAL_ANCHOR.MIDDLE
cell.text_frame.vertical_anchor = MSO_ANCHOR.MIDDLE
cell.text_frame.vertical_anchor = 3
cell.text_frame.vertical_anchor = MSO_VERTICAL_ANCHOR.BOTTOM
etc.
```

None of these options affect the cell's layout. I even used `print(cell.text_frame.vertical_anchor)` statements to confirm my code was setting the state correctly (and it printed out e.g. MIDDLE (3)), but when I open the actual .pptx file in PowerPoint, the text cell is vertically unaligned, and the Layout buttons all show the alignment as TOP. 

My first assumption is that I'm doing something dumb wrong, but I couldn't figure out what from pouring over the documentation. Any ideas why it's not working? 

Code:
```python
for cell in table.rows[0].cells:
    print(cell.text_frame.paragraphs[0].text) (sanity check)
    cell.text_frame.paragraphs[0].font.size = Pt(12)
    cell.text_frame.paragraphs[0].alignment = PP_ALIGN.CENTER
    cell.text_frame.vertical_anchor = 3 (or MSO_VERTICAL_ANCHOR.MIDDLE, or MSO_ANCHOR.MIDDLE, etc.)
    print(cell.text_frame.vertical_anchor)
```
Font size and .alignment all work perfectly, only having trouble with .vertical_anchor.

Thanks again!

**Comment by scanny** [comment]
Set the vertical anchor on the cell itself, not the text frame of the cell.
