### ISSUE TITLE
How to set slide background color？

### ISSUE THREAD

**Issue by Haujilo** [scanny/python-pptx#193]
See the picture, like the red color. Any code example or documentation?

![1](https://cloud.githubusercontent.com/assets/1232859/12547647/7cb025b2-c38c-11e5-9dcb-f88f7106b2d0.jpg)

**Comment by scanny** [comment]
It's not supported yet in the API. You'd need to go down to the lxml level.

**Comment by Huozic** [comment]
@scanny Thanks!  May be support in the future？

**Comment by scanny** [comment]
No current plans to add it. I've moved on to other projects so there's no active development on this project just at the moment.

**Comment by emilecaron** [comment]
If it can be of some use to anyone, here's how i did it (yolo code, but does the job)
```
        presentation_ml = '{http://schemas.openxmlformats.org/presentationml/2006/main}'
        drawing_ml = '{http://schemas.openxmlformats.org/drawingml/2006/main}'

        bg = Element(f'{presentation_ml}bg')
        bg_pr = SubElement(bg, f'{presentation_ml}bgPr')
        solid_fill = SubElement(bg_pr, f'{drawing_ml}solidFill')
        srgb_clr = SubElement(solid_fill, f'{drawing_ml}srgbClr')
        srgb_clr.attrib['val'] = 'FF0000'
        SubElement(bg_pr, f'{drawing_ml}effectLst')

        slide.element.find(f'{presentation_ml}cSld').insert(0, bg)
```

**Comment by scanny** [comment]
Slide.background and SlideMaster.background were added in release 0.6.9 on Wed May 9, 2018.
