### ISSUE TITLE
How to send image back?

### ISSUE THREAD

**Issue by shalakhin** [scanny/python-pptx#195]
Hi guys!

How to send image back on the slide?

**Comment by shalakhin** [comment]
Already found in one of issues here. 

```
cover_bg = slide.shapes.add_picture(company.cover_background, left, top)
slide.shapes._spTree.remove(cover_bg._element)
slide.shapes._spTree.insert(2, cover_bg._element)
```

**Comment by scanny** [comment]
Are you looking to change the z-order of the picture shape or actually use it as the slide background? These are two different things, each with its own mechanism.

**Comment by shalakhin** [comment]
Ideally I would like to set background image.

**Comment by shalakhin** [comment]
@scanny how can I set background image for slides?

**Comment by rmithun** [comment]
@shalakhin if you need to set the image as background one unclear solution is scaling the picture to the size of slide. like below

left = top = Inches(0)
slide.shapes.add_picture(img_path, left, top, width=prs.slide_width, height=prs.slide_height)

not sure whether this might be helpful to you.

**Comment by zjrn** [comment]
> Are you looking to change the z-order of the picture shape or actually use it as the slide background? These are two different things, each with its own mechanism.

How to use a image as the background of slide please?

**Comment by scanny** [comment]
Duplicate of #366
