### ISSUE TITLE
python-pptx crashes in C++ python Embedded mode.

### ISSUE THREAD

**Issue by Murthi86** [scanny/python-pptx#196]
I am trying to use python-pptx to generate pptx file from python 3.3.2 Embedded in C++ application .
It is working fine for first time and crashes when i try to import  "pptx" for next time.
Here is my code

```
void TestPPTX()
{
std::string code = 
"from pptx import Presentation\n\
prs = Presentation();\n\
prs.save(\"sss.pptx\");\n\
del sys.modules[\"pptx\"];\n\
";	
	Py_InitializeEx(0);
	PyRun_SimpleString(code.c_str());
	Py_Finalize();
	return;
}

void main(int argc, char *argv[])
{
	TestPPTX(); // Works correctly
	TestPPTX();	// crashes
	getch();    
}

```

When i move the Py_Finalize(); to main function it works 

```
void TestPPTX()
{
std::string code = 
"from pptx import Presentation\n\
prs = Presentation();\n\
prs.save(\"sss.pptx\");\n\
del sys.modules[\"pptx\"];\n\
";
	Py_InitializeEx(0);
	PyRun_SimpleString(code.c_str());
	return;
}


void main(int argc, char *argv[])
{
	TestPPTX(); // Works correctly
	TestPPTX();	// Works correctly
	Py_Finalize();
	getch();    
}
```

I want to know any memory leak is there in pptx and how to sort out this issue.

thanks
Srinivas

**Comment by scanny** [comment]
I don't see how this is a question about the library. I would check and see if it has the same behavior with other modules. Off-hand I expect it has something to do with what's allowable in the C++ embedding.

Can't help you I'm afraid.

**Comment by KGShastry** [comment]
Here, Py_Finalize is clearing all memory allocated by python modules. As documented in the manual, random clearing of memory may be causing this crash. Is there any way to clear memory related to pptx module?

**Comment by scanny** [comment]
It does strike me as worth a check to see if this has to do with the lxml library. That's a dependency for python-pptx and is relies on C-modules. There's nothing in python-pptx itself that tries to access memory directly in any way.
