### ISSUE TITLE
ImportError: cannot import name Presentation

### ISSUE THREAD

**Issue by a-reda** [scanny/python-pptx#200]
I installed python-pptx through pip and I tried to use this import "from pptx import Presentation" but I get this error:

ImportError: cannot import name Presentation

**Comment by Majeed-Sahebzadha** [comment]
Seems more like a path config problem than with the pptx library.

**Comment by a-reda** [comment]
Can you please tell me how I can solve this?

**Comment by Majeed-Sahebzadha** [comment]
probably be a better idea to discuss this in python-pptx's google group:

https://groups.google.com/forum/#!forum/python-pptx

**Comment by a-reda** [comment]
Thank you, I created a thread on the google group.
