### ISSUE TITLE
feature: Series.format

### ISSUE THREAD

**Issue by ankitjain87** [scanny/python-pptx#205]
I am using this library, and found there is no support for line series colors, I have three series and for one of line series, it's showing in white color which is not visible because the background is white.

So it will be good if we have some method to change color, just like we have in BarSeries.

**Comment by Majeed-Sahebzadha** [comment]
+1

**Comment by jredd** [comment]
+1 also telling the series what kind of line it is (solid, dashed, etc)

**Comment by scanny** [comment]
Series.format, which provides access to both .line and .fill, is forthcoming in the next release, probably in the next couple days. LineFormat includes width, but not line style yet, so @jredd you might want to +1 that separate feature request or add it if it's not in the list yet.

**Comment by scanny** [comment]
This was added in v0.6.0, just uploaded to PyPI.

**Comment by jredd** [comment]
Is there any documentation on using this new feature?

**Comment by jredd** [comment]
nvm I figured it out through some experimenting...

**Comment by oxy-gendotmobi** [comment]
Indeed documentation would be great to have...
