### ISSUE TITLE
feature: empty (value == None) data points in chart series

### ISSUE THREAD

**Issue by ankitjain87** [scanny/python-pptx#207]
I need to generate a line chart in which one of the data points is missing. I want the line to be rendered with a "gap" that skips over the missing point.

I tried `chart_data.add_series('East',    (24.3, "", 20.2))` but that didn't work.

Attaching an image what I am looking for.
<img width="1088" alt="graph" src="https://cloud.githubusercontent.com/assets/417575/14204201/24a9aa00-f820-11e5-9162-27c2661a6eab.png">

How can I achieve this?

**Comment by scanny** [comment]
Are you able to achieve this when working manually with PowerPoint? If so, what do you do that produces the desired effect?

**Comment by ankitjain87** [comment]
Hi Scanny,

In Powerpoint if I remove a value/point in excel then the line shown discontinued. 

Attaching the same.

<img width="1260" alt="line_chart" src="https://cloud.githubusercontent.com/assets/417575/14223786/f310ec7c-f8a3-11e5-97dc-ad74ca1b8441.png">

You can see I have removed the points for Category3, so in line chart line discontinued at Category3.

This is what I am looking for, is it possible to achieve using python-pptx?

Thanks,
Ankit Jain

**Comment by scanny** [comment]
Got it, thanks @ankitjain87, very helpful details.

We don't support empty (`None`) values in a series yet, but I'll leave this issue open as a feature request for that.

**Comment by ankitjain87** [comment]
Thanks Scanny.

**Comment by scanny** [comment]
Added with v0.6.0 release uploaded to PyPI today.

**Comment by adumitrescu20** [comment]
Hello, What was the fix? I am trying soemthing very similar and python-pptx is treating None as 0.0
