### ISSUE TITLE
Giving labels for X axis.

### ISSUE THREAD

**Issue by rohitstatic** [scanny/python-pptx#208]
Hi,

I am using the pptx library for chart generation. While it has an excellent support for generating value labels for Y axis , the same is missing for x axis. Is there a way to give some one line label for the x axis as well. I am using the following code to get Y axis labels.

value_axis = chart.value_axis
value_axis.maximum_scale = 50.0
value_axis.minor_tick_mark = XL_TICK_MARK.OUTSIDE
value_axis.has_minor_gridlines = True

tick_labels = value_axis.tick_labels
tick_labels.number_format = '0"%"'
tick_labels.font.bold = True
tick_labels.font.size = Pt(14)

**Comment by scanny** [comment]
Can you show an example of what that would look like when you create it "by hand" using PowerPoint? Is that something PowerPoint supports?

**Comment by rohitstatic** [comment]
<img width="962" alt="screen shot 2016-04-02 at 8 38 19 am" src="https://cloud.githubusercontent.com/assets/661792/14224116/7b8cb356-f8ae-11e5-8de7-e88eaefa93eb.png">

Powerpoint supports them in the form of Axis Titles. As shown above I have added two axis titles on the x-axis as "Categorical Values" and on the y axis as "Percentage". How can I achieve this in python-pptx?

**Comment by scanny** [comment]
There's an active pull request here on this, not sure if that's a help to you:
https://github.com/scanny/python-pptx/pull/198

It's not merged in yet, but hopefully will proceed to that in the next while. Encouraging the pull request with a +1 is always a help :)

**Comment by scanny** [comment]
Axis titles have been added in the v0.6.3 release.
