### ISSUE TITLE
Chart documentation out of date

### ISSUE THREAD

**Issue by samzhang111** [scanny/python-pptx#210]
http://python-pptx.readthedocs.io/en/latest/user/charts.html does not include any mention of the stacked charts implemented in #125. I haven't been able to find any documentation of the stacked bar charts outside of the code.

**Comment by jldork** [comment]
+1

**Comment by rokclimb15** [comment]
I think my request isn't merged yet.  I imagine the docs will be added
after merge or perhaps required as part of the merge process (although
nobody has mentioned that yet).

**Comment by scanny** [comment]
Added in v0.6.0
