### ISSUE TITLE
feature: add_picture() supports PDF 

### ISSUE THREAD

**Issue by bsavoie** [scanny/python-pptx#211]
Is there support for inserting .pdf files or other image files that support vector graphics? Sorry if I've missed it, but the docs only have direct references to .png .jpeg, and .gif, and in my testing I've only gotten add_picture() calls to work with .png files. When I try a *.pdf file there is no effect.

**Comment by scanny** [comment]
Not presently. I'll leave this one open as a feature request for this.

**Comment by petebachant** [comment]
I don't think PPTs can include PDFs. There will probably need to be some intermediate process to convert to an image format.

**Comment by bsavoie** [comment]
My current solution is to convert prior to calling python-pptx. This is somewhat annoying because it creates intermediate image files only for this purpose, but for my purposes it isn't a significant inconvenience. 

I'm not sure what's going on under the hood, but you can certainly import pdf files into powerpoint without  rasterizing them. Perhaps they are converted to some other vector format, but they remain vector-based in their behavior (arbitrary resizing without loss of quality).

**Comment by scanny** [comment]
Not to do with the solution per se, but is there a reason you couldn't use in-memory stream objects like 'StringIO' instead of disk files for the intermediate image streams? Or are you doing that step with something other than Python?

**Comment by bsavoie** [comment]
Good point, I should be able to bypass the disk file creation. For my purposes most of the images are generated with matplotlib.

**Comment by scanny** [comment]
@petebachant turns out to be quite right about this. While the PowerPoint application allows a user to insert PDF and EPS images, they are converted to placeable WMF/EMF before being written to the .pptx package. I'm strongly inclined to avoid adding a new dependency to the library, so for the time being folks will be on their own to do the conversion with another available Python library. Closing for now.
