### ISSUE TITLE
Line Charts are broken if only one series is displayed

### ISSUE THREAD

**Issue by Cribac** [scanny/python-pptx#220]
Hi there,
the line charts are broken if I want do display only one series.
Code to test:
```python
from pptx import Presentation
from pptx.chart.data import ChartData
from pptx.enum.chart import XL_CHART_TYPE
from pptx.util import Inches

prs = Presentation()
slide = prs.slides.add_slide(prs.slide_layouts[5])

chart_data = ChartData()
chart_data.categories = ['2010', '2011', '2012', '2013', '2014', '2015']
chart_data.add_series('Q1 Sales', (19.2, 21.4, 16.7, 11.1, 14.4, 10.0))
# chart_data.add_series('Q2 Sales', (17.2, 16.6, 18.7, 22.1, 10.4, 15.0))

x, y, cx, cy = Inches(2), Inches(2), Inches(6), Inches(4.5)
graphic_frame = slide.shapes.add_chart(
    XL_CHART_TYPE.LINE, x, y, cx, cy, chart_data
)

chart = graphic_frame.chart
chart.has_legend = True
chart.legend.include_in_layout = False

prs.save('test.pptx')
```

Outcome in Powerpoint 2013:
![snip1](https://cloud.githubusercontent.com/assets/19753077/16681234/bbe12414-44f3-11e6-9e41-02d83d59d3a8.PNG)

If I add the second series, everything is fine:
![snip2](https://cloud.githubusercontent.com/assets/19753077/16681244/cb6723f2-44f3-11e6-9c0b-165717f25c2d.PNG)

i have no clue what is causing this...

Cheers,
Christian

**Comment by scanny** [comment]
This behavior reflects the Plot.vary_by_categories property. If you set that False the line should be all one color.

```python
    plot = chart.plots[0]
    plot.vary_by_categories = False
```

See this section in the documentation: file://localhost/Users/scanny/Dropbox/src/python-pptx/docs/.build/html/api/chart.html#baseplot-objects

**Comment by Cribac** [comment]
Hi Steve,
thank you very much for the fast reply (and for this library btw.)
I'll try that out.
Thanks, Christian
Am 08.07.2016 19:41 schrieb "Steve Canny" <notifications@github.com>:
