### ISSUE TITLE
group shapes

### ISSUE THREAD

**Issue by nilswagner** [scanny/python-pptx#222]
How can I group several shapes ?

from pptx import Presentation
from pptx.enum.shapes import MSO_SHAPE
from pptx.enum.text import MSO_ANCHOR, MSO_AUTO_SIZE
from pptx.enum.text import PP_ALIGN
from pptx.util import Inches, Mm, Pt
from pptx.dml.color import RGBColor
from pptx.oxml.shapes.groupshape import CT_GroupShape
prs = Presentation()
title_only_slide_layout = prs.slide_layouts[5]
slide = prs.slides.add_slide(title_only_slide_layout)
shapes = slide.shapes
left = top = height = Mm(9.0)
width = Mm(20.0)
for i in range(0,5):
    shape = shapes.add_shape(MSO_SHAPE.RECTANGLE, left,top,width,height)

**Comment by sshadmand** [comment]
Trying to figure out the same thing, but https://github.com/scanny/python-pptx/blob/eaa1e0fd3db28b03a353e116a5c7d2084dd87c26/docs/user/understanding-shapes.rst#id1 looks like it isn't yet supported.

**Comment by scanny** [comment]
There's a [pull request here](https://github.com/scanny/python-pptx/pull/214) that's made some progress in case that's a help.

**Comment by sshadmand** [comment]
Thanks Scanny. It looks like it was closed and not merged. Did a group feature get folded back in somewhere else?

**Comment by scanny** [comment]
Group shape support was added in release 0.6.8 on Apr 18, 2018.
