### ISSUE TITLE
Power Point file renderer

### ISSUE THREAD

**Issue by jmgamboa** [scanny/python-pptx#226]
Hi folks. First time posting in this repo and like seeing all this activity, and enthusiasm with this project. I have browsed yours docs but still have a question. 

Basically, is there a way to download a generated ppt over the wire from a rest app, via a renderer if you have one, IE django rest csv, pdf, json renderers OR is common practice here to create the file, upload it to a file storage, say S3 and have the user download it from there.

**Comment by jredd** [comment]
yes it's doable but you wouldnt technically do the GET for the file as a rest end point. some quick googles looking at Downloadong files from django should yield you the results you want

**Comment by scanny** [comment]
It's common to use `python-pptx` to generate an in-memory .pptx file (e.g. a StringIO object) and then serve that byte stream to service what looks to the end-user like a file download request, all this without ever saving a file to disk.

If you're asking whether there is rendering capability built into `python-pptx`, the answer is no and there's unlikely ever to be. It's largely two separate roles and creating the file is big enough (for my appetite anyway :).

It sounds like maybe there are separate rendering libraries available, which would be a cool option. I hadn't considered that before; something like that could come in handy :)

**Comment by jmgamboa** [comment]
@jredd thanks! I was originally having difficulty finding info on google but the way you phrased it, may be the key to finding better results.

@scanny  thanks for providing me best practice on serving the byte stream / not having to save a file to disk. that was helpful. also glad that I sparked some thoughts on a power point renderer, maybe when my colleague and I are done with our work we can submit a PR to DRF extensions. closing this for now, thanks guys!
