### ISSUE TITLE
xl_chart_type_column_clustered with maximum_scale produces unexpected y axis issue

### ISSUE THREAD

**Issue by thebeancounter** [scanny/python-pptx#229]
when using the following code 

`
chart_data.categories = titles
chart_data.add_series('percentiles', tuple(values))

chart = slide.shapes.add_chart(
    XL_CHART_TYPE.COLUMN_CLUSTERED, x, y, cx, cy, chart_data).chart

v_a = chart.value_axis
v_a.maximum_scale = float(values[8])`

with the following data:

titles [90, 80, 70, 60, 50, 40, 30, 20, 10]
values [271, 887, 1541, 2332, 3188, 4074, 5049, 6299, 19891]

the y axis starts from a negative number 

when i am not using the maximum scale, the y axis starts from 0 as it should.

![image](https://cloud.githubusercontent.com/assets/13833578/18315174/baf1f8b6-751e-11e6-985c-1436e4a8b81e.png)

Thanks!

**Comment by scanny** [comment]
Does the same thing happen when you create a chart like that in PowerPoint by hand?

I note that -109 is 5000 less than 4891, so it's setting 19891 as the top and the other horizontal grid lines 5000 apart.

It strikes me as PowerPoint's idea of the best idea it can figure out to display what you've asked for.

If you want the Y-axis to start at 0, you should tell PowerPoint so using the Axis.minimum_scale property.

I don't see any insubordinate behavior here yet (maybe a little surprising though until you think it through) :)

**Comment by thebeancounter** [comment]
Well when you say it like that it is logical in some way... :-)

But axis minimum scale doesnt do anything abd hence the problem i was
talking about.

Any idea why minimum scale does not work for me here?

בתאריך 12 בספט׳ 2016 23:09,‏ "Steve Canny" <notifications@github.com> כתב:

**Comment by scanny** [comment]
Ah, now that *is* interesting :)

Can you produce a chart that looks the way you want by hand in PowerPoint by setting only those max and min values?

If so, an inspection of the XML is likely to be revealing.

**Comment by thebeancounter** [comment]
well, i will do my best, i never did much with power point itself.
how do i produce the xml for inpection?

shai

**Comment by scanny** [comment]
It's easy from inside python-pptx. The other way is with opc-diag.

From python-pptx you just get the lxml element for the object in question and then use its `.xml` property. So say from an axis object:

```python
print axis._element.xml
```

Using [opc-diag](http://opc-diag.readthedocs.io/en/latest/install.html) would be something like this:

```bash
opc browse my-test-file.pptx chart1.xml
```

But I think in the end you'll find here that `python-pptx` is setting the XML in the intended way, just that PowerPoint interprets the XML in an unexpected way in this case.

But if you can make one by hand that looks the way you want, one can often discover the hidden mechanism at work by comparing the XML of the python-pptx generated .pptx and the one built by hand.

**Comment by scanny** [comment]
@thebeancounter: did you get this working?

**Comment by thebeancounter** [comment]
we decided to plot the graph by creating an image in pyplot and then
pasting it as image in the pptx,
the plotting capabilities are not quite sufficient for what we need right
now.
