### ISSUE TITLE
feature: Chart axis of type datetime

### ISSUE THREAD

**Issue by thebeancounter** [scanny/python-pptx#231]
I am trying to use dates or datetime values as x axis tick_labels, 
when i give datetime.datetime as x values of the data, it treats and presents them as numbers, 
I can't find any documentation about how to do it. 

is there any way?

Thanks.

**Comment by scanny** [comment]
The datetime axis type hasn't been implemented yet.

**Comment by thebeancounter** [comment]
Is there any walk around?
Maybe formating a number as
Xx-xx-xx ?

בתאריך 14 בספט׳ 2016 19:49,‏ "Steve Canny" <notifications@github.com> כתב:

**Comment by scanny** [comment]
Support for date axis was added in the latest release v0.6.2.

**Comment by yopuro** [comment]
Could you please give example for using date axis on x axis using pptx. Thanks!!
