### ISSUE TITLE
Method to duplicate slide?

### ISSUE THREAD

**Issue by lhsu1** [scanny/python-pptx#232]
Hi,

I am trying to create many copies of a preexisting slide with different values filled into a couple of the text boxes. Is there a way to directly copy all of the contents of a slide into a new slide? I was thinking about reading in the attributes of each shape and then recreating the shapes with those arguments, but was wondering if there's a more direct way of doing this.

Thanks!

**Comment by scanny** [comment]
There's some discussion of this here:
https://github.com/scanny/python-pptx/issues/132

**Comment by lhsu1** [comment]
Great thanks!
