### ISSUE TITLE
AttributeError: 'Presentation' object has no attribute 'slide_layouts'

### ISSUE THREAD

**Issue by ngnikhilgoyal** [scanny/python-pptx#240]
I am trying out this library for the first time and following the docs : http://python-pptx.readthedocs.io/en/latest/user/slides.html

When I ran this: 
`SLD_LAYOUT_TITLE_AND_CONTENT = 1

prs = Presentation()
slide_layout = prs.slide_layouts[SLD_LAYOUT_TITLE_AND_CONTENT]
slide = prs.slides.add_slide(slide_layout)`

I got the following error:

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-19-eec908082de9> in <module>()
      2 
      3 prs = Presentation()
----> 4 slide_layout = prs.slide_layouts[SLD_LAYOUT_TITLE_AND_CONTENT]
      5 slide = prs.slides.add_slide(slide_layout)

AttributeError: 'Presentation' object has no attribute 'slide_layouts' `

I am on Mac OsX10 , running Jupyter iPython Notebook, Anaconda installation.

**Comment by scanny** [comment]
Well, the `Presentation` object in python-pptx certainly does have a `slide_layouts` property: https://github.com/scanny/python-pptx/blob/master/pptx/presentation.py#L55

I suggest you look at the type of Presentation and make sure it's what you expect it to be:

```python
print(type(prs))
```

Could be something wrong in the import statement or perhaps you installed someone else's fork or an earlier version.

```python
import pptx
print(pptx.__version__)
```

should return: '0.6.1' or similar, although I expect anything after '0.5.0' should work for most purposes.

**Comment by ngnikhilgoyal** [comment]
Hi scanny , thanks so much. My version is 0.3.2 . I had installed this version : https://anaconda.org/asmeurer/python-pptx

Found the latest version: https://anaconda.org/conda-forge/python-pptx

Will Anaconda keep this updated in the future , I wonder?

**Comment by scanny** [comment]
Dunno. You'd have to inquire with their packaging folks I expect. New releases come out fairly often, at least a few times a year lately, so if you can learn to install yourself directly that might be the best bet. `pip` makes it dead easy, but I'm not familiar with the Anaconda environment so that might make things trickier.
