### ISSUE TITLE
docs: fix 'add_shape()' call

### ISSUE THREAD

**Issue by ngnikhilgoyal** [scanny/python-pptx#241]
Hi again Scanny,

Following the documentation to add auto-shape to a slide : https://python-pptx.readthedocs.io/en/latest/user/autoshapes.html

When I do this: 
from pptx.enum.shapes import MSO_SHAPE

left = top = width = height = Inches(1.0)
shape = slide.add_shape(
    MSO_SHAPE.ROUNDED_RECTANGLE, left, top, width, height
)

I get: 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-55-977e7adbbd7a> in <module>()
     22 from pptx.enum.shapes import MSO_SHAPE
     23 left = top = width = height = Inches(1.0)
---> 24 shape = slide.add_shape(
     25       MSO_SHAPE.ROUNDED_RECTANGLE, left, top, width, height
     26 )

AttributeError: 'Slide' object has no attribute 'add_shape'

I looked at : https://github.com/scanny/python-pptx/blob/master/pptx/slide.py

and couldn't find the property add_shape .

**Comment by scanny** [comment]
Okay, I think this is a typo in the docs. Try:

```python
shape = slide.shapes.add_shape(...)
```

**Comment by scanny** [comment]
Fixed in v0.6.3.
