### ISSUE TITLE
support for cell merge/split to span columns

### ISSUE THREAD

**Issue by adriannye** [scanny/python-pptx#249]
When cells are merged, the first cell has gridSpan set in the _tc element of the XML to an integer of the number of cells spanned, and the spanned cells are still in the XML but they have  hMerge set to 1.   (And probably vMerge set in the case of row span.)

The API could be on the _Cell object.   The microsoft API has Merge and Split methods on the cell, and supports both row span and column span (including both at the same time).  The Merge method argument is the end cell (specified by row and column) of the merged range.   Split takes two arguments, the number of rows and the number of columns to split the cell into.

**Comment by adriannye** [comment]
I started working on this, and there's some code on github in my fork of this repo, but it's not simple because the gridSpan needs to be on the tc element which doesn't have any attributes yet.  Also the tests are complicated by the fact that setting gridSpan affects the hMerge attribute of adjacent cells, but the fixtures at the moment don't create those adjacent cells.  It looks like you could find the adjacent cells use the parent.   I discovered a workaround that will do what I need so I'm going to stop work:
https://groups.google.com/forum/#!topic/python-pptx/cVRP9sSpEjA

**Comment by scanny** [comment]
`_Cell.merge()` as well as a collection of other cell-merging goodies will appear in v0.6.14 to be released circa Sep 23, 2018.
