### ISSUE TITLE
png to placeholder is not clear

### ISSUE THREAD

**Issue by andy2046** [scanny/python-pptx#250]
Hi Steve,

wehen i insert png to placeholder, the picture is not clear in ppt, but the original png is quite good if i manually paste to ppt, any suggestion for this? thx 

`placeholder.insert_picture('my-image.png')`

**Comment by scanny** [comment]
Is it a picture placeholder? What do you mean specifically by "not clear in ppt"?

**Comment by andy2046** [comment]
Hi Steve,
yes, it is a picture placeholder, the png looks quite ok when I download the png in browser, but when i pass it to server and save it to the placeholder, it is fuzzy n blurry

**Comment by scanny** [comment]
Hmm, I'm afraid "fuzzy n blurry" isn't much to go on for diagnosis purposes. Can you attach a screenshot or attach an example?

**Comment by andy2046** [comment]
![picture2](https://cloud.githubusercontent.com/assets/2193706/21445996/d8edbb8a-c8fb-11e6-88e7-2a564c610478.png)
![picture1](https://cloud.githubusercontent.com/assets/2193706/21446001/e0e55a78-c8fb-11e6-9ee5-3a867017c29e.png)

Hi Steve, you can find the png downloaded in browser n in ppt attached,

on client i use` canvas.toDataURL("image/png");` to pass png to server, then on server side i write the png to temp folder and insert to placeholder, 

```
with open(path.join(settings.MEDIA_ROOT, 'temp.png' ), "wb") as fh:
        fh.write(base64.decodestring(img))
slide1.placeholders[14].insert_picture(path.join(settings.MEDIA_ROOT, 'temp.png' ))
```

**Comment by andy2046** [comment]
Hi Steve, any advice on this pls, thx

**Comment by andy2046** [comment]
@scanny

**Comment by scanny** [comment]
Hmm, sorry, somehow my message back got eaten by GitHub or something.

What I had asked in response was:

Can you resend the .pptx file? I don't find it attached.

**Comment by andy2046** [comment]
[my.pptx.txt](https://github.com/scanny/python-pptx/files/698395/my.pptx.txt)
@scanny 
pls remove the .txt then open it as pptx, thx

**Comment by scanny** [comment]
Ok, now I can see what you're describing. The problem is simple. The image being inserted is first of all a raster image (made up of pixels, not lines or vectors). Second, it is small (395px x 440px) relative to the chart placeholder. So the image simply gets graining when it is scaled up.

If you want better results, use a bigger raster image or find a vector format that will work.
