### ISSUE TITLE
powerpoint autoshapes

### ISSUE THREAD

**Issue by gauravrele87** [scanny/python-pptx#251]
Hello,

is there is any way of saving an autoshape as a jpeg file outside or if you know a way to do it? I can see the xml properties of it but I am not sure how to generate the autoshapes after that.

regards,

Gaurav

**Comment by scanny** [comment]
Not to my knowledge. This would require a renderer of some type. It's not inconceivable that someone would write such a thing, but rendering is outside the scope of `python-pptx`.
