### ISSUE TITLE
KeyError: no relationship of type

### ISSUE THREAD

**Issue by rylanchiu** [scanny/python-pptx#252]
I'd like to extract the text content from ppt slides following the document:

    from pptx import Presentation

    prs = Presentation('notes/lec02.ppt')

    # text_runs will be populated with a list of strings,
    # one for each text run in presentation
    text_runs = []

    for slide in prs.slides:
        for shape in slide.shapes:
            if not shape.has_textframe:
                continue
            for paragraph in shape.textframe.paragraphs:
                for run in paragraph.runs:
                    text_runs.append(run.text)

But got such a weird error:

    KeyError                                  Traceback (most recent call last)
    <ipython-input-2-5ce116f22745> in <module>()
          1 from pptx import Presentation
          2 
    ----> 3 prs = Presentation('notes/lec02.ppt')
          4 
          5 # text_runs will be populated with a list of strings,

    /Users/yobichi/bigdata/lib/python3.5/site-packages/pptx/api.py in Presentation(pptx)
         28         pptx = _default_pptx_path()
         29 
    ---> 30     presentation_part = Package.open(pptx).main_document_part
         31 
         32     if not _is_pptx_package(presentation_part):

    /Users/yobichi/bigdata/lib/python3.5/site-packages/pptx/opc/package.py in main_document_part(self)
         98         for a SpreadsheetML package.
         99         """
    --> 100         return self.part_related_by(RT.OFFICE_DOCUMENT)
        101 
        102     def next_partname(self, tmpl):

    /Users/yobichi/bigdata/lib/python3.5/site-packages/pptx/opc/package.py in part_related_by(self, reltype)
        131         if more than one such relationship is found.
        132         """
    --> 133         return self.rels.part_with_reltype(reltype)
        134 
        135     @property

    /Users/yobichi/bigdata/lib/python3.5/site-packages/pptx/opc/package.py in part_with_reltype(self, reltype)
        434         is found.
        435         """
    --> 436         rel = self._get_rel_of_type(reltype)
        437         return rel.target_part
        438 

    /Users/yobichi/bigdata/lib/python3.5/site-packages/pptx/opc/package.py in _get_rel_of_type(self, reltype)
        487         if len(matching) == 0:
        488             tmpl = "no relationship of type '%s' in collection"
    --> 489             raise KeyError(tmpl % reltype)
        490         if len(matching) > 1:
        491             tmpl = "multiple relationships of type '%s' in collection"

    KeyError: "no relationship of type 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument' in collection"
 
Did I do anything wrong? How should I deal with this issue? Thanks!

**Comment by scanny** [comment]
Can you send a sample of the offending presentation? Also, how was it created? It looks like it's missing a key relationship, the one indicating where to start when opening the presentation.

**Comment by rylanchiu** [comment]
[notes.pptx](https://github.com/scanny/python-pptx/files/675148/notes.pptx) @scanny Thanks for your reply. Here is the `ppt` file I used. I can not understand why it can not find where to start when opening the presentation. Shouldn't it be the first page? Thanks!

**Comment by scanny** [comment]
How was this file created? PowerPoint won't open it on my machine (Mac).

**Comment by rylanchiu** [comment]
[notes.ppt.zip](https://github.com/scanny/python-pptx/files/675428/notes.ppt.zip)@scanny how about this one?

**Comment by rylanchiu** [comment]
@scanny And this file should be created with PowerPoint(Mac version). Thanks!

**Comment by scanny** [comment]
@rylanchiu You have not answered my question. How is this file created? It is apparently not with PowerPoint and I don't believe I can help you.

**Comment by rylanchiu** [comment]
@scanny As the file isn't created by me, I am not sure how is it created. As far as I know, there are only two ways of creating a ppt file(I am not sure about it neither). One is created with PowerPoint and the other is created with latex. If you thought it can not be created with PowerPoint, then it may be created with latex...

**Comment by scanny** [comment]
While it has a `.pptx` extension, it is not a valid PowerPoint file. So `python-pptx` is never going to be able to open it.

It contains no slides, so there are no shapes to extract text from.

You can see for yourself exactly what's in the .pptx file you sent if you unzip it. A .pptx file is a zip archive:

```
unzip notes.pptx
```

**Comment by rylanchiu** [comment]
@scanny Did you receive the latest one I sent to you? It has not `.pptx`  extension anymore. Instead the extension is `.ppt` .

**Comment by scanny** [comment]
The `.ppt` extension is for older versions of PowerPoint (earlier than PowerPoint 2007). These files are a binary format that python-pptx does not support.

**Comment by rylanchiu** [comment]
@scanny So what extension is supported by python-pptx?

**Comment by rylanchiu** [comment]
@scanny  The problem is solved, thx.

**Comment by scanny** [comment]
What was the solution? These answers are so everyone can learn, so it's proper etiquette to explain how you solved it for the benefit of others who arrive here later on search.

**Comment by rylanchiu** [comment]
@scanny The solution is quite simple. Just save the `.ppt` file as `.pptx` file. Cause I tried once via directly change the extension. The correct way should be changing it in the PowerPoint.
