### ISSUE TITLE
Duplicating Slides Links to External Images

### ISSUE THREAD

**Issue by tjefferies** [scanny/python-pptx#254]
So I am trying to duplicate slides from one presentation to another and am noticing the images in my source presentation are not making it into my destination presentation.

The code I am using is provided by robintw and zhong2000 to duplicate slides
(see issue #132 and #232):

My source presentation is one slide with an image and a text caption and I am trying to move it to the end of an existing presentation.

I am getting the following warning when I run the code: 
![picture1](https://cloud.githubusercontent.com/assets/24706343/21736330/21a0e956-d42d-11e6-9c24-b63bc7ff869f.png)

When I go to open the destination presentation I get the PowerPoint repair issue mentioned by cjshawMIT (see issue #87) and the destination presentation contains only the captions and none of the images.

**Comment by scanny** [comment]
Do you understand how parts and relationships work in the Open Packaging Convention?

**Comment by tjefferies** [comment]
I can't say that I do... I'm a bit of a noob

**Comment by scanny** [comment]
Better study up on that. Here's a start:
https://en.wikipedia.org/wiki/Open_Packaging_Conventions

**Comment by abinhho** [comment]
Hi,

Im using PHP to open ppt/pptx file but got error at line:

$ppApp = new COM("PowerPoint.Application") or die("Unable to instantiate Word");

$presentation = $ppApp->Presentations->Open(public_path($path), false, false, true); // <---- fail at this line

When I check SID in security audit, I saw SID is null.

Creator Subject:
Security ID:  SYSTEM
Account Name:  SAMPLE-440$
Account Domain:
SAMPLE
Logon ID:  0x3E7

Target Subject:
Security ID:  NULL SID
Account Name:  -
Account Domain:
Logon ID:  0x0

Any help?

Thanks !
