### ISSUE TITLE
Bug: python-pptx fails when included in standalone applications

### ISSUE THREAD

**Issue by pbrod** [scanny/python-pptx#255]
When I include python-pptx in a standalone application made by cx_freeze I get the  following error message:

  File "C:\Python27\lib\site-packages\pptx\enum\base.py", line 61, in _intro_text
    return textwrap.dedent(cls_docstring).strip()
  File "C:\Python27\lib\textwrap.py", line 390, in dedent
    text = _whitespace_only_re.sub('', text)
<type 'exceptions.TypeError'>: expected string or buffer'

The reason for this error is that python sets all docstrings to None when compiling the source code.
Thus we have: "textwrap.dedent(None).strip()"

In order to fix this line 61 in file "C:\Python27\lib\site-packages\pptx\enum\base.py"  should be replaced with:

   return textwrap.dedent(cls_docstring).strip() if cls_docstring else ''

**Comment by scanny** [comment]
Thanks @pbrod, I'll see about getting this into the next release :)

**Comment by pbrod** [comment]
+1

**Comment by scanny** [comment]
Fixed in v0.6.3.
