### ISSUE TITLE
Table cell default font is Pt(18) and leaves 1 space character (and maybe a crlf) along with my resized values

### ISSUE THREAD

**Issue by jimlemons** [scanny/python-pptx#261]
Hi - I'm a newb.  I've been trying to figure out how to add my dataframe data into a ppt table and have gotten stuck on the font stuff.
My data is populating the table with all the df data, but I'm seeing 1 space character in the cell with font = 18, then a wrapped Pt(8) of my data on what appears as a second line of the cell.

Life would be good if I could get rid of the default Pt(18) space character in each cell.  But don't know how.

I'm looping through the rows and columns of the data and inserting data into each cell with following:
            tf = res.table.cell(row+1, col).text_frame
            # tf.text = None
            # tf.text = ""
            p = tf.add_paragraph()
            p.font.size = Pt(8)
            r = p.add_run()
            r.font.size = Pt(8)
            r.text = str(val)

btw - 
res = slide.shapes.add_table(rows+1, cols, left, top, width, height)
I set height to Inches(0.2), but with the extra Pt(18) inserted, it can't reduce the row height.
Any ideas? Thanks

**Comment by scanny** [comment]
A text frame cannot be completely empty. By default, it contains a single paragraph; this is the blank space/line you're seeing.

If you cnange `p = tf.add_paragraph()` to `p = tf.paragraphs[0]`, the leading blank line should disappear.
