### ISSUE TITLE
pptx2pdf

### ISSUE THREAD

**Issue by nilswagner** [scanny/python-pptx#270]
How can I convert a pptx to a pdf within python-pptx ?

There are some external tools, e.g.

libreoffice --headless --invisible --convert-to pdf *.ppt
unoconv -f [format] pdf  filename.ppt

**Comment by scanny** [comment]
Forming a PDF from a .pptx file is a rendering operation and python-pptx does not and will not include a renderer. In my opinion, this is a good role for a separate package.
