### ISSUE TITLE
Export PPTX as PDF

### ISSUE THREAD

**Issue by dirtshell** [scanny/python-pptx#271]
I am using `python-pptx` in my workflow as part of my test suite. One option that I would love to see added is the ability to save PowerPoints as PDFs. Currently I have an rough solution where I start a `subprocess32` with the command

`libreoffice --headless --invisible --convert-to pdf *.pptx`

when LibreOffice is available. But from a cursory glance at the source, it appears it may be possible to export the presentation object as a PDF directly. I could use `unoconv` as well I believe, but it has a much smaller install base than LibreOffice.

I realize this is probably an edge use case, but I figured I would just throw the feature request out there.

**Comment by nilswagner** [comment]
+1

**Comment by scanny** [comment]
Printing is a form of rendering (amongst other things I expect) and the scope of `python-pptx` doesn't include rendering. Extending into the rendering realm is a topic that comes up from time to time, but the short story is I don't see `python-pptx` ever having a renderer.

But that doesn't mean it can't have a handy interface into some other library that provides aspects like that.

If someone works out a smooth workflow between `python-pptx` and a stable package, we can definitely talk about how to integrate them better.
