### ISSUE TITLE
XL_DATA_LABEL_POSITION options don't all work

### ISSUE THREAD

**Issue by mjlawrence83** [scanny/python-pptx#272]
I'm using version 0.6.0 and we're getting pie charts where the data labels are overlapping eachother where the segments are so small.

I'd ideally like to use enum MIXED to give variance in the data label position vertically and horizontally to reduce this problem from happening, however this causes a 'ValueError: MIXED (6) not a member of XL_DATA_LABEL_POSITION enumeration' exception.

I also tried 'ABOVE', 'BELOW', 'INSIDE_BASE', 'RIGHT', and 'LEFT',  which all just caused the resulting pptx to be corrupt.

**Comment by scanny** [comment]
The `MIXED` member of that enumeration is for reading purposes only. Basically if you ask a series what position it's data labels are in and some are above and others are below, it tells you 'MIXED'. It's not meaningful (or permitted) to write that value.

If support is in there for this on pie charts, you can set data label position individually by point. So something like:

```python
pie_chart = shapes.add_chart(...).chart
series = pie_chart.plots[0].series[0]
for point in series.points:
    point.data_label.position = XL_DATA_LABEL_POSITION.ABOVE
```

If you're getting corruption errors I'd like to see the snippet of code that does it. Generally, there shouldn't be a way to produce a corrupt (repair error) file with `python-pptx`.

**Comment by mjlawrence83** [comment]
Hi,

Thank you for the clarification on the MIXED enum....

If I manually set the position individually, it seems to reset all other settings, such as the font size, and the displayed value, instead of a percentage value I'm now getting 'Series 1, <name of value>'......any way around this?

**Comment by scanny** [comment]
Yes, that's a consequence of setting an individual data label property. I'm not sure why PowerPoint doesn't inherit style in this case, but it doesn't seem to. So you either have to set them all the same as a group or set them all individually. I'm sure it made sense to somebody over there at Microsoft when they were developing it, or perhaps they figured it was something that would be used infrequently and only put in the basics.

Were you going to send an example that produces the corruption errors you mentioned? Open source support is a two-way street :)
