### ISSUE TITLE
BaseShape.id property is deprecated and will be removed in a future release. Use .shape_id instead.

### ISSUE THREAD

**Issue by deIndustries** [scanny/python-pptx#279]
> /usr/local/lib/python3.6/site-packages/pptx/shapes/placeholder.py:335: 
> UserWarning: BaseShape.id property is deprecated and will be removed in a future release. Use .shape_id instead.
`id_, name = self.id, self.name`

suggest changing this to: 
`id_, name = self.shape_id, self.name`

**Comment by scanny** [comment]
Yep, good catch, thanks @deIndustries, that'll appear in the next release :)

**Comment by scanny** [comment]
This change appears in release v0.6.6.
