### ISSUE TITLE
issues with brackets

### ISSUE THREAD

**Issue by thebeancounter** [scanny/python-pptx#280]
Hi
 
I am creating a pptx using python pptx with python 2.7

I am adding some text that includes brackets around a word. 

When opening that pptx in libre office it's fine, but when opening it in Microsoft power point the brackets are both opening brackets, i.e ->  (thebeancounter) becomes (thebeancounter( 

Again, only in Microsoft power point, when opening it in LibreOffice everything is acting as expected 

Thanks

**Comment by scanny** [comment]
Please post the minimum code required to reproduce the problem.

**Comment by thebeancounter** [comment]
![example of how it looks in microsoft power point](https://cloud.githubusercontent.com/assets/13833578/25390334/e8b1212e-29db-11e7-9082-921f0e6c7984.png)

minimal working example is:

```
import pptx 
ppt = pptx.Presentation()
txbox = slide.shapes.add_textbox()
tf = txbox.text_frame
tf.clear()
tf.word_wrap = True
p = tf.paragraphs[0]
p.text = "somthing that includes (brackets)" 
p.alignment = PP_ALIGN.CENTER
ppt.save(path)
```

this is read perfectly in libre office but in ms office it produces both "(" brackets instead of one opening and one closing. 

in addition, the text paragraph height is much larger in ms office without any reason when using height with pptx.utils.Inches(int)


Thanks!

**Comment by scanny** [comment]
I'm unable to reproduce this problem.

```python
from pptx import Presentation
from pptx.enum.text import PP_ALIGN
from pptx.util import Inches

prs = Presentation('empty.pptx')
slides = prs.slides
slide = slides.add_slide(prs.slide_layouts[0])

txbox = slide.shapes.add_textbox(Inches(1), Inches(1), Inches(3), Inches(1))
tf = txbox.text_frame
tf.clear()
tf.word_wrap = True
p = tf.paragraphs[0]
p.text = "somthing that includes (brackets)"
p.alignment = PP_ALIGN.CENTER
prs.save('deleteme.pptx')
```

**Comment by thebeancounter** [comment]
Does the code crash, or it goes without the issue stated?

When i open it in LibreOffice it's awesome, and when my co-worker opens it
in ms. office it causes problems, can this be a problem that i caused
because his office is defaulted to Hebrew (right to left language)?

Thanks!

**Comment by scanny** [comment]
I don't know what you mean by code crashing. It runs, produces the output .pptx file, that file opens, and the parentheses display normally.

I think you're left with experimentation as your next diagnostic step. The Hebrew default sounds like a possibility, also the font as I mentioned earlier. In that respect, I would look to see whether the wrong character is being *stored* or just the wrong character is being *displayed*. At least learning that would cut the solution search space in half.

**Comment by thebeancounter** [comment]
will do. thanks!

**Comment by thebeancounter** [comment]
thanks!

the problem was microsoft's right to left configurations!

בתאריך 5 במאי 2017 21:24,‏ "Shai Tal" <shai2go@gmail.com> כתב:
