### ISSUE TITLE
text alignment issues when using runs and break line

### ISSUE THREAD

**Issue by thebeancounter** [scanny/python-pptx#281]
Hi, 

I am using python pptx with python 2.7 on a linux machine. 
I use the following code to print some text to a slide 

```
text = "Max Transport Lag (Mbs) peak_value #1" +"\n" + "2016-05-10 09:33:00" +  "\n" +  "--- \n 2016-05-10 10:14:00"

txbox = slide.shapes.add_textbox(left, top, width, height)
txbox.vertical_anchor = MSO_ANCHOR.MIDDLE

tf = txbox.text_frame
tf.clear()
tf.word_wrap = True
p = tf.paragraphs[0]

run = p.add_run()
run.font.color.rgb = RGBColor(color[0], color[1], color[2])
run.font.size = number_to_points(title_size)
run.text = text
p.alignment = PP_ALIGN.CENTER
```

and only the last line gets centered, i tried everything, how can i center all the rows in the paragraph? 

attached an example for what happens.

How can i fix this? 

Thanks!

![textscreenshot](https://cloud.githubusercontent.com/assets/13833578/25433047/b2a3f908-2a8f-11e7-91ac-444ff50694b9.png)

**Comment by scanny** [comment]
A run is not meant to have line feed characters in it. These are represented in the XML as distinct break (`<a:br>`) elements, in between separate runs.

If you use `paragraph.text = text` instead, those break elements will be inserted automatically for you, each replacing a `\n` character. That will result in three runs in that paragraph, so you'll then you'll have to loop through to set the font characteristics separately for each run. It might be worth trying Paragraph.font and seeing if those settings work there; some do, some don't, e.g.:

```python
paragraph = text_frame.paragraphs[0]
paragraph.text = text
font = paragraph.font
font.color.rgb = RGBColor(...)
etc.
```

**Comment by thebeancounter** [comment]
Cool, thanks. how can one iterate all the runs in the paragraph?

**Comment by scanny** [comment]
Might be time to spend a little more quality time with the documentation :)  
http://python-pptx.readthedocs.org/en/latest/index.html

Runs are in `Paragraph.runs`:

```python
for run in paragraph.runs:
    ... do something with run ...
```

**Comment by thebeancounter** [comment]
Thanks for all the help, you are great!!!
