### ISSUE TITLE
picture cropping

### ISSUE THREAD

**Issue by nileshruikar27** [scanny/python-pptx#282]
I tried to crop the picture using
    img= slide.shapes.add_picture(image_path, left, top, height=ht)
    img.crop_left(0.1)

But it throws error.
i read through other issues and you mentioned that cropping is readonly.

is there any other war for achieving cropping? When can we except crop feature?

**Comment by scanny** [comment]
Picture crop setters were added in release 0.6.9 on Wed May 9, 2018.
