### ISSUE TITLE
possible to play mp3 or ogg sound file on slide transition?

### ISSUE THREAD

**Issue by richiverse** [scanny/python-pptx#289]
thanks!

**Comment by scanny** [comment]
You'll need to say more Rich. So far the answer is yes and no, depending :)

**Comment by richiverse** [comment]
Let's say I have either a local file or mp3 in s3, when I transition to
page 2, it plays the file automatically

**Comment by scanny** [comment]
PowerPoint can do this if I'm not mistaken. This is not the right place for general PowerPoint questions though. This issues list is for suspected bugs and feature requests for the `python-pptx` library. If you're looking for general support I recommend you use StackOverflow and tag your question with 'python-pptx'.
