### ISSUE TITLE
Set column widths in tables

### ISSUE THREAD

**Issue by mitchelljkotler** [scanny/python-pptx#295]
How can I set the column width for tables?  Right now, all columns in a table always have the same width.  I found https://github.com/python-openxml/python-docx/issues/78 from python-docx which looked promising, but this does not seem to work in python-pptx.

Thanks

**Comment by mitchelljkotler** [comment]
Nevermind - in python-pptx you can set the column widths directly, no need to set the cell widths (cells don't support setting their width)

**Comment by anupreet-birr** [comment]
@mitchelljkotler can you please share how to do it?

**Comment by MartinPacker** [comment]
How about this? `shapeWidfth` is the width of the table shape.

```
cols = newTable.columns
        for colno in range(columns):
            cols[colno].width = int(shapeWidth * widths[colno] / widths_total)
```

**Comment by mitchelljkotler** [comment]
@anupreet-birr This was a long time ago!  Unfortunately, I no longer have access to the code as it was for a previous job, and I have not used python-pptx since then.  Hopefully @MartinPacker's solution will help you.
