### ISSUE TITLE
Edit a paragraph with bold and normal text inside a table cell

### ISSUE THREAD

**Issue by AravindAddy** [scanny/python-pptx#297]
How can we write into a table cell (0, 1) - a paragraph with a mixture of bold, italic and normal text ?
Example : 
Aravind
**SE**

Rajan
**ME**

**Comment by scanny** [comment]
What have you tried so far? Have to read the documentation?

**Comment by AravindAddy** [comment]
yes @scanny , I am using multiple runs to do this. But this needs coordinates like top, height, width, and left and this is independent of the table cell. 

def func(text, bold=False):
       tf = slide.shapes.add_textbox(left=Cm(6.2),top=Inches(self.x),width=Cm(9),height=Cm(1))
        ft = tf.text_frame
        ft.clear()
        p = ft.paragraphs[0]
        run = p.add_run()
        run.text = text
        if bold:
               run.font.bold = True
        else:
               run.font.bold = False

Is there any other way I could edit a paragraph inside a table.cell(0,1) ,  with normal, bold and italic texts ?

**Comment by scanny** [comment]
I think you'll have better luck with this sort of question on StackOverflow. This issues list is for suspected bugs and feature requests.

**Comment by AravindAddy** [comment]
Thanks @scanny  It would be great if we could give texts instead of runs like " * python-pptx *  is a great ^module^." and get output in pptx as ,

**python-pptx** is  a great _module_.  

Please consider this a feature request.
