### ISSUE TITLE
"Cannot identify image file" when giving file-like object

### ISSUE THREAD

**Issue by jkornblum** [scanny/python-pptx#301]
I'm trying to add matplotlib plots to a PowerPoint.
I have used this code on python-docx without issue. It doesn't seem to working for python-pptx.

This code doesn't work and gives error `OSError: cannot identify image file <_io.BytesIO object at 0x00000000407A17D8>`
It works fine if I have the file saved to file system and use a string path
```
...
buf = io.BytesIO()
t = list(range(0, 10, 1))
plt.plot(t, t, 'r--', t, [x**2 for x in t], 'bs', t, [x**3 for x in t], 'g^')
plt.savefig(buf, format="png")

slide.placeholders[0].text = 'string1'
slide.placeholders[13].text = 'string2'
slide.placeholders[14].insert_picture(buf)
```
Using this code in python-docx has worked fine on the same machine
```
buff = io.BytesIO()
t = list(range(0, 10, 1))
plt.plot(t, t, 'r--', t, [x**2 for x in t], 'bs', t, [x**3 for x in t], 'g^')
plt.savefig(buff, format="png")
doc.add_picture(buff)
```

Am I misunderstanding something about the API?

**Comment by scanny** [comment]
Hmm, interesting, I wonder if `io.BytesIO` is answering "yes" to `instance(buf, str)`. Are you running Python 3?

I'll bet that's it.

If `python-pptx` thinks the image object you send it is a filename, it tries to open it from the disk, which would produce just the error your seeing I believe. That's why it's an `OSError` and not a `PIL` error of some kind. The offending code would be here: https://github.com/scanny/python-pptx/blob/master/pptx/parts/image.py#L166

although the test is actually delegated to here for Python3: https://github.com/scanny/python-pptx/blob/master/pptx/compat/python3.py#L21

**Comment by scanny** [comment]
Interestingly, `python-docx` seems to use exactly the same test. Not surprising I guess since I wrote them both and borrowed heavily from one to the other where they had things in common.

Anyway, maybe that gives you some hints you can use to explore further. I'd be happy to consider a patch and also to noodle it through with you as you uncover more. Do you have a local fork you can modify for experimentation purposes?

**Comment by jkornblum** [comment]
Okay I think I know what the problem is (I have not forked and tested, I was just comparing docx and pptx libraries and using a Jupyter notebook with PIL).

In python-docx after `is_string` returns False you have this [code](https://github.com/python-openxml/python-docx/blob/master/docx/image/image.py#L39)
```
stream = image_descriptor
stream.seek(0)
blob = stream.read()
filename = None
```
In python-pptx after `is_string` returns False you have this [code](https://github.com/scanny/python-pptx/blob/master/pptx/parts/image.py#L166)
```
# assume image_file is a file-like object
blob = image_file.read()
filename = None
```
I think after I write to the bytestream with matplotlib that the stream position is at the end
```
buff = io.BytesIO()
...
plt.savefig(buff, format="png")
```
 So when you do a `.read()` nothing is being read into `blob` and PIL throws an error when using `PIL.Image.open(blob)`

**Comment by scanny** [comment]
Okay, that might be it. Let us know how you go and we'll work out how to prevent others from having trouble in the future. Calling `.seek(0)` yourself before the `.insert_picture()` call should be an effective test.

I remember there was some brief discussion a couple years back where someone didn't like the `.seek()` call, which is possibly why it doesn't appear in the `python-pptx` version. Apparently not all file-like objects support `seek()`: #170, #180.

Maybe the solution is to add a proviso to the docstring for the add-picture methods or perhaps introspect for a `seek` method before calling it.

**Comment by halfling-rram** [comment]
I faced the same problem on python 3. 
`.seek(0)` before saving resolve it.

**Comment by scanny** [comment]
Added "seek(0) if you can" behavior in release v0.6.12 circa Aug 11, 2018.

**Comment by MarynaLongnickel** [comment]
I still don't understand :< Could someone please help? I'm getting error on second to last line. I've read bunches of tips, but still can't figure it out.
```
@app.route('/predict', methods=["POST"])
def predict():
    message = request.get_json(force=True)  # dict
    encoded = message['image']              # str
    decoded = base64.b64decode(encoded)     # bytes
    with graph.as_default():
        image = Image.open(io.BytesIO(decoded))
        preprocessed_image = preprocess_image(image, target_size(50, 50))
        prediction = model.predict(preprocessed_image).tolist()
```

**Comment by RehanSD** [comment]
I'm having this issue, but adding a .seek(0) doesn't fix the problem. Code:
```python
         img = base64.b64encode(open("cat.png", "rb").read())
        img_tensor = preprocess(Image.open(io.BytesIO(img)))
```
```python
OSError: cannot identify image file <_io.BytesIO object at 0x7fa4b5c45bf8>
```

**Comment by scanny** [comment]
@RehanSD 

Please post support questions on StackOverflow with the 'python-pptx' tag.

Make sure you state what you're trying to accomplish and the full stack trace.

**Comment by RehanSD** [comment]
Sure, sorry about that - it was a weird PIL.Image issue, but I managed to solve it. Will keep this in mind for future reference.

**Comment by RobertoEsp** [comment]
> Sure, sorry about that - it was a weird PIL.Image issue, but I managed to solve it. Will keep this in mind for future reference.

Can you tell us how?
