### ISSUE TITLE
feature: LineFormat.dash_style

### ISSUE THREAD

**Issue by tedwards999** [scanny/python-pptx#320]
Hi
In a line graph we need to be able to change the line style for a specific series to different styles such as: dashed, round dot, square dot etc. It seems that this functionality is available for markers but not for lines in line graphs. I am trying to create a graph with 4 series of which two must be dashed (targets) and two must be solid (actuals).
If there is a way to do this please advise.

**Comment by tedwards999** [comment]
is this something anyone can help with?

**Comment by scanny** [comment]
As it happens this is coming in the next release, should be out within a couple of weeks.

**Comment by scanny** [comment]
This is part of release 0.6.7 published today.

**Comment by tedwards999** [comment]
Thanks Steve.
This is really an excellent product, thank you very much for all your work on this project.

**Comment by scanny** [comment]
It's good of you to say so @tedwards999, you're very welcome :) My thanks go out to the company that sponsored this feature and all those that provide the financial means to continue this package's development to the public benefit :)
