### ISSUE TITLE
feature: Paragraph.add_line_break()

### ISSUE THREAD

**Issue by realtimecarsten** [scanny/python-pptx#322]
I have soft linebreaks in my text - this works very nice with text and newlines.

However, I also have formatting like boldface and italic within one line - so I have to break down the line using runs. 

Now if I have a line with boldface and line breaks on a bullet slide, using newline leads to a new bullet point - which is not what I want.

I understand that the soft breaks are inserted automagically when setting the text - would it be possible to have an explicit function to also set a soft break at the end of a run?

**Comment by scanny** [comment]
Show us the input, code, and screenshot of the output that's giving you a problem. A '\n' character in the text should produce an `<a:br/>` element to be inserted between runs. A run is one thing, a line break (`<a:br/>`) is another. You can't have a line break "inside" a run.

**Comment by realtimecarsten** [comment]
I hope this example shows what I would like to achieve and what the problem is. I would like to have the typesetting like the last bullet (with the italic and non-italic words), but with a soft break after the colon (like in the first two bullets). However, using a run I get an extra bullet instead (bullet 3+4). See also comments in my code.

![text-vs-run-problem](https://user-images.githubusercontent.com/9824166/31718790-6e8270ea-b411-11e7-8054-4584d46ac9b3.png)

A nice way would be if one could add a soft break at the end of the run (here: the one with " something:").

So here's the code for the example:

<pre>
from pptx import Presentation

prs = Presentation()

bullet_layout = prs.slide_layouts[1]
slide = prs.slides.add_slide(bullet_layout)
title_shape = slide.shapes.title
body_shape = slide.shapes.placeholders[1]
title_shape.text = "Example\nNo. 1"

# embedded \n in string with text_frame.text gives you a soft break
body_shape.text_frame.text = "To emphasize something:\nUse italics."

# repeat, just to see it happens also with other paragraphs
p = body_shape.text_frame.add_paragraph()
p.text = "To emphasize something:\nUse italics."
 
# using a run, no soft break, but a new bullet instead
p = body_shape.text_frame.add_paragraph()
r = p.add_run()
r.text = "To emphasize something:\nUse italics."

# and this is an example how I would like to format the text, but with the soft breaks (which I cannot get done)
p = body_shape.text_frame.add_paragraph()
r = p.add_run()
r.text = "To "
r = p.add_run()
r.text = "emphasize" 
r.font.italic = True
r = p.add_run()
r.text = " something: Use "
r = p.add_run()
r.text = "italics."
r.font.italic = True
 
prs.save("softBreak.pptx")
</pre>

**Comment by scanny** [comment]
Hmm, interesting. We'd better have a look at the XML that's being generated.

Way I always do that is with opc_diag. In this case the command would be:

```bash
$ opc browse softBreak.pptx slide1.xml
```

The XML in question should appear close to the bottom of the file, inside a `<p:sp>` element. If you'll paste that whole `p:sp` element in here we'll take a closer look.

**Comment by scanny** [comment]
Actually, you know what, a lot easier way to peek at the XML is this line inserted toward the end of your script:

```python
print(body_shape._sp.xml)
```

If you post that out put here we'll be able to see what's happening.

**Comment by scanny** [comment]
@realtimecarsten Did you get this working?

**Comment by realtimecarsten** [comment]
Sorry scanny... busy with work ... thanks so much for taking care of this.
This is is the output from the print command - is that what you wanted?
```
<p:sp xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <p:nvSpPr>
    <p:cNvPr id="3" name="Content Placeholder 2"/>
    <p:cNvSpPr>
      <a:spLocks noGrp="1"/>
    </p:cNvSpPr>
    <p:nvPr>
      <p:ph idx="1"/>
    </p:nvPr>
  </p:nvSpPr>
  <p:spPr/>
  <p:txBody>
    <a:bodyPr/>
    <a:lstStyle/>
    <a:p>
      <a:r>
        <a:t>To emphasize something:</a:t>
      </a:r>
      <a:br/>
      <a:r>
        <a:t>Use italics.</a:t>
      </a:r>
    </a:p>
    <a:p>
      <a:r>
        <a:t>To emphasize something:</a:t>
      </a:r>
      <a:br/>
      <a:r>
        <a:t>Use italics.</a:t>
      </a:r>
    </a:p>
    <a:p>
      <a:r>
        <a:t>To emphasize something:
Use italics.</a:t>
      </a:r>
    </a:p>
    <a:p>
      <a:r>
        <a:t>To </a:t>
      </a:r>
      <a:r>
        <a:rPr i="1"/>
        <a:t>emphasize</a:t>
      </a:r>
      <a:r>
        <a:t> something: Use </a:t>
      </a:r>
      <a:r>
        <a:rPr i="1"/>
        <a:t>italics.</a:t>
      </a:r>
    </a:p>
  </p:txBody>
</p:sp>

```

**Comment by realtimecarsten** [comment]
Oops - pushed the wrong button. Didn't want to close this yet.

**Comment by scanny** [comment]
Ah, okay, I think I know what's happening now after a brief look through the code.

`Paragraph.text` transforms `'\n'` characters into `<a:br/>` elements, which render as "soft" line breaks. `Run.text` does not have that behavior, and inserts the new-line characters directly into the XML. You can see that in the second-to-last paragraph, where "Use italics" starts abruptly on a new line, not surrounded by element tags.

So it's going to be limited how you can work around that without writing workaround code to manipulate the XML directly. You can insert several runs separated by line feeds and then go back to them using `Paragraph.runs` to manipulate them individually, but you won't be able to format between line breaks.

In your position I think I would have a look at the code for `Paragraph.text` and maybe `Paragraph.add_run()` and use some of the internal `oxml` calls it uses to manipulate the XML. This is where all the action is for that it looks like: https://github.com/scanny/python-pptx/blob/master/pptx/oxml/text.py#L455

You might be able to accomplish what you want just using `paragraph._p.add_br()`. You could call that in-between adding runs to a paragraph when you wanted to insert a soft line break.

I'll leave this issue open as a feature request for `Paragraph.add_line_break()`.

**Comment by scanny** [comment]
Added `_Paragraph.add_line_break()` in release v0.6.12 circa Aug 11 2018.

Note this implementation is simple, inserting a new `<a:br/>` element at the end of the paragraph. Break elements can actually have a full set of run properties, such as font size. So there might be some reason later to make a fuller implementation.

**Comment by gaetanderos** [comment]
Hi,

I'm working on a project and I have the same issue as realtimecarsten. 
But I'm quite not experienced to understand XML.
Could you give an example what I should write in XML to include soft linebreaks in my text?

Thanks a lot.
