### ISSUE TITLE
'zipfile.BadZipFile' error in python 3.6 but not python2

### ISSUE THREAD

**Issue by mariashen** [scanny/python-pptx#326]
This seems to be a similar issue to the one described here: https://github.com/scanny/python-pptx/issues/174

I'm running a virtualenv with Python3.6. This is the error that I get when I see when I try to read in a powerpoint presentation using the ppt.Presentation() method:

```
  File "slidenator.py", line 309, in <module>
    create_charts(presentation_name)
  File "slidenator.py", line 183, in create_charts
    prs = ppt.Presentation(f)
  File "/Users/maria/Desktop/PowerpointPythonProject/python3-version/test/lib/python3.6/site-packages/pptx/api.py", line 30, in Presentation
    presentation_part = Package.open(pptx).main_document_part
  File "/Users/maria/Desktop/PowerpointPythonProject/python3-version/test/lib/python3.6/site-packages/pptx/opc/package.py", line 122, in open
    pkg_reader = PackageReader.from_file(pkg_file)
  File "/Users/maria/Desktop/PowerpointPythonProject/python3-version/test/lib/python3.6/site-packages/pptx/opc/pkgreader.py", line 32, in from_file
    phys_reader = PhysPkgReader(pkg_file)
  File "/Users/maria/Desktop/PowerpointPythonProject/python3-version/test/lib/python3.6/site-packages/pptx/opc/phys_pkg.py", line 102, in __init__
    self._zipf = ZipFile(pkg_file, 'r')
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/zipfile.py", line 1108, in __init__
    self._RealGetContents()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/zipfile.py", line 1175, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

This used to work just fine in Python2. Not sure what the issue could be here. The solution described previously mentioned that there was some issue with argparse, but I'm unclear what that means.

**Comment by mariashen** [comment]
Okay, I took a look inside /pptx/opc/phys_pkg.py and I'm starting to see the issue.

I specified a path to the pptx file I wanted to use as a template. I passed it as a string to Presentation(), which created this printout in phys_pkg.py:

in my main python file:
```
f = '/path/to/pptx/file'
prs = ppt.Presentation(f)
```

Printout from /pptx/opc/phys_pkg.py:
`<_io.TextIOWrapper name='/Users/maria/Desktop/PowerpointPythonProject/python3-version/Presentation1.pptx' mode='r' encoding='UTF-8'>`

However, when I changed my code in my main python file to this:
```
# f = '/path/to/pptx/file' #removed this template
prs = ppt.Presentation() #run without template
```

I got this printout from /pptx/opc/phys_pkg.py:
`/Users/maria/Desktop/PowerpointPythonProject/python3-version/test/lib/python3.6/site-packages/pptx/templates/default.pptx`

Note that the new printout is not in a TextIOWrapper.

This seems to be the difference, but still not sure what's causing this.

**Comment by mariashen** [comment]
I "fixed" this by swapping out the default.pptx file in pptx/templates/default.pptx with my own pptx file.

Still would appreciate any ideas on how to fix the actual problem!

**Comment by scanny** [comment]
What happens when you execute this code with the file path string?

```python
from zipfile import ZipFile

pptx_path = (
    '/Users/maria/Desktop/PowerpointPythonProject/python3-version/Presentati'
    'on1.pptx'
)
zipf = ZipFile(pptx_path, 'r')
```

**Comment by scanny** [comment]
Also, show all the code you used to produce your results, in particular the `print()` statements. Having to guess on the particulars of what produced what output is often wasteful :)

**Comment by mariashen** [comment]
Thanks for the super fast reply!

Here's my output from executing the code snippet you suggested:
`Python 3.6.3 (default, Oct  4 2017, 06:09:05) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from zipfile import ZipFile
>>> 
>>> pptx_path = (
...     '/Users/maria/Desktop/PowerpointPythonProject/python3-version/Presentati'
...     'on1.pptx'
... )
>>> zipf = ZipFile(pptx_path, 'r')
>>> zipf
<zipfile.ZipFile filename='/Users/maria/Desktop/PowerpointPythonProject/python3-version/Presentation1.pptx' mode='r'>
>>> `

Also, apologies for not showing all the code for my print statements!

From my main python file:
`f = '/path/to/pptx/file'
prs = ppt.Presentation(f)`


Here's what I have in /pptx/opc/phys_pkg.py:

`class PhysPkgReader(object):
    """
    Factory for physical package reader objects.
    """
    def __new__(cls, pkg_file):
        # if *pkg_file* is a string, treat it as a path
        print("===========")
        print(pkg_file)
        # pkg_file = '/Users/maria/Desktop/PowerpointPythonProject/python3-version/Presentation1.pptx'
        if is_string(pkg_file):
            print("==========is string!!!!!!!==============")
            if os.path.isdir(pkg_file):
                print("is a directory")
                reader_cls = _DirPkgReader
            elif is_zipfile(pkg_file):
                print("is a zipfile")
                reader_cls = _ZipPkgReader
            else:
                raise PackageNotFoundError(
                    "Package not found at '%s'" % pkg_file
                )
        else:  # assume it's a stream and pass it to Zip reader to sort out
            print("=========assumed stream=======")
            reader_cls = _ZipPkgReader

        return super(PhysPkgReader, cls).__new__(reader_cls)`


Output:
`===========
<_io.TextIOWrapper name='/Users/maria/Desktop/PowerpointPythonProject/python3-version/Presentation1.pptx' mode='r' encoding='UTF-8'>
=========assumed stream=======`

**Comment by scanny** [comment]
So what is the output of `print(pkg_file)` in `PhysPkgReader`? It looks like it's failing the test for `is_string()`.

**Comment by mariashen** [comment]
This is the output of `print(pkg_file)` in `PhysPkgReader`:

`<_io.TextIOWrapper name='/Users/maria/Desktop/PowerpointPythonProject/python3-version/Presentation1.pptx' mode='r' encoding='UTF-8'>`

When I directly set the `pkg_file` variable inside `PhysPkgReader`, it does pass the test as string, but `<_io.TextIOWrapper name='/Users/maria/Desktop/PowerpointPythonProject/python3-version/Presentation1.pptx' mode='r' encoding='UTF-8'>` is still the output. See below:

From `PhysPkgReader`:
```
    def __new__(cls, pkg_file):
        # if *pkg_file* is a string, treat it as a path
        print("===========")
        print(pkg_file)
        pkg_file = '/Users/maria/Desktop/PowerpointPythonProject/python3-version/Presentation1.pptx'
        if is_string(pkg_file):
            print("==========is string!!!!!!!==============")
            if os.path.isdir(pkg_file):
                print("is a directory")
                reader_cls = _DirPkgReader
            elif is_zipfile(pkg_file):
                print("is a zipfile")
                reader_cls = _ZipPkgReader
            else:
                raise PackageNotFoundError(
                    "Package not found at '%s'" % pkg_file
                )
        else:  # assume it's a stream and pass it to Zip reader to sort out
            print("=========assumed stream=======")
            reader_cls = _ZipPkgReader

        return super(PhysPkgReader, cls).__new__(reader_cls)

```
Note that I directly set `pkg_file = '/Users/maria/Desktop/PowerpointPythonProject/python3-version/Presentation1.pptx'`.

This is the output:

```
===========
<_io.TextIOWrapper name='/Users/maria/Desktop/PowerpointPythonProject/python3-version/Presentation1.pptx' mode='r' encoding='UTF-8'>
==========is string!!!!!!!==============
is a zipfile
```

**Comment by scanny** [comment]
What is the actual code that's calling`Presentation()` with the file path? (including imports)

**Comment by mariashen** [comment]
This is the code that's calling Presentation():

```

## import required libraries
import sys
import os
import pandas as pd
import xlsxwriter as excel
import pptx as ppt
import math
import ast

from pptx.chart.data import ChartData
from pptx.enum.chart import XL_CHART_TYPE, XL_LABEL_POSITION, XL_TICK_MARK, XL_LEGEND_POSITION
from pptx.util import Inches, Pt
from pptx.enum.dml import MSO_FILL, MSO_THEME_COLOR
from pptx.enum.shapes import MSO_SHAPE, MSO_SHAPE_TYPE
from pptx.dml.color import RGBColor


from lxml import etree as ET
from lxml.builder import E, ElementMaker

# Own Libraries
import slidenatorhelper as s_helper
import pie
import excel_manipulator
import bar
import line
import bubble
import area
import scatter
import column
import doughnut
import table
import radar
import automated_search
import automated_visibility


# Configure these settings
directory = '/Users/maria/Desktop/PowerpointPythonProject/python3-version/'


def create_charts(presentation_name):
    # Get all chart data
    data = s_helper.create_dictionary_from_excel_sheet(file_name, directory)

    # Open presentation
    f = open(directory+'Presentation1.pptx') #Presentation template is configurable
    prs = ppt.Presentation(f) # <---- This is where things break with Bad Zipfile Error
    f.close()
    sheets = read_specs()
    specs = create_spec_dictionaries(sheets)
...
...
...
   return


if __name__ == "__main__":
    # Once created, you can find the file in directory, under 'sample_bar_charts.pptx'
    file_name = input('Enter File Name --> ')
    print("Cool, making a presentation from file %s." % file_name)
    presentation_name = file_name+".pptx"
    create_charts(presentation_name)
```

**Comment by scanny** [comment]
Ok, that explains it.

You just want to have:

```python
prs = ppt.Presentation(directory+'Presentation1.pptx')
```

There's no need to open the file ahead of time (or close it after). `python-pptx` takes care of all those details for you.

If you did need to open the file for some reason, I believe it needs to be opened in binary write mode (mode='bw' or something like that).

But best just not to get involved in any of that unless you need to.

Also, btw, the `import pptx as ppt` is a little odd. Most folks would just put `from pptx import Presentation`, avoiding the need to use a suffix. If you had some sort of naming collision, you'd want to use `import pptx` by itself and then `pptx.Presentation(...)` to open a new presentation.

**Comment by mariashen** [comment]
That worked :)

It's strange because in Python2 this was my code and it worked:
```
    f = open(directory+'Presentation1.pptx') #Presentation template is configurable
    prs = ppt.Presentation(f)
    f.close()
```

Anyway, thank you so much for your help on this and for pointing out the odd import statement.

Also, thanks for your work on this fantastic library and continuously supporting it. We use it heavily.

**Comment by scanny** [comment]
I think if you changed the `open()` call to `open(directory+'Presentation1.pptx`, 'rb')` then it would work with Python 3.

I can't find the particulars on it with a quick search, but I vaguely remember something about ZipFile requiring a file-like object to be opened in binary mode, where Python 2 didn't for some reason.

Anyway, glad you got it working :)

If your team needs any features added and has a little project budget for that, let me know; I'm a freelance developer and one of my gigs is adding features to the library for folks that need them. A lot of our best stuff (charts, videos, etc.) have come that way :)

**Comment by mariashen** [comment]
Got it! That's great to hear and I'll definitely let my team know! :)
