### ISSUE TITLE
Example missing from documentation for using colorscheme in piechart + barchart

### ISSUE THREAD

**Issue by oxy-gendotmobi** [scanny/python-pptx#330]
Hi,

I cannot find an example nor code evidence on how to set the colors(or colorscheme) for the series fill colors of the 

- piechart (XL_CHART_TYPE.PIE)

- barchart (XL_CHART_TYPE.COLUMN_CLUSTERED) objects.

For example the color of the pie chart outerlines I can change but the fill does not work.
plot.series[0].format.line.color.rgb = RGBColor(255,0,0)

Is it implemented to change the fill of these charts? If so, any examples? :-)

**Comment by scanny** [comment]
What code did you use to change the fill?

**Comment by jamesrkg** [comment]
@oxy-gendotmobi if I follow you correctly, have you tried:

```python
# XL_CHART_TYPE.COLUMN_CLUSTERED
series = chart.series[i]
series.format.fill.solid()
series.format.fill.fore_color.rgb = RGBColor(*rgb_fill)
line = series.format.line
line.fill.solid()
line.color.rgb = RGBColor(*rgb_outline)

# XL_CHART_TYPE.PIE
series = chart.series[x]
point = series.points[y]
fill = point.format.fill
fill.solid()
fill.fore_color.rgb = RGBColor(*rgb_fill)
line = point.format.line
line.fill.solid()
line.color.rgb = RGBColor(*rgb_outline)
```

**Comment by oxy-gendotmobi** [comment]
The PIE chart has points inside the series. That I did not see.
I noticed the series -> points for the bar charts though... :)  via Googling other sites last night. 
I am forcing colors for the barchart like:
```
point = chart.series[0].points[bar_id]  
fill = point.format.fill
fill.solid()
fill.fore_color.rgb = RGBColor(0, 0, 255)
```
 
The example in the above post works. Maybe good to add to the regular documentation.

**Comment by scanny** [comment]
I've elaborated the API documentation to include specific sections for each of the seven implemented series types, including `PieSeries`. This makes explicit the `.points` property which provides access to individual pie "slices" for formatting.

This will appear in the next release.

More user-level documentation would be nice too, I'm open if someone wants to work on that and submit a PR.
