### ISSUE TITLE
shape.Shadow = <shadow_option> Request

### ISSUE THREAD

**Issue by ThomIves** [scanny/python-pptx#331]
Hi Steve,

Thanks again for this great module. I couldn't find where anyone has formally asked for shadow control yet, so I am formally asking ;-)

Thanks,
Thom Ives

**Comment by scanny** [comment]
Hi Thom, this is a duplicate of #130. You can add remarks to that one if you want :)

**Comment by ThomIves** [comment]
Glad it's covered. Sorry - thought I searched enough.


Thom Ives, Call or Text 208.284.4285

**Comment by scanny** [comment]
No worries Thom :)
