### ISSUE TITLE
support for ppt files (not pptx)

### ISSUE THREAD

**Issue by mehdimir** [scanny/python-pptx#334]
Is there any plan to support ppt files (old powerpoint format) in the roadmap?

Thanks!

**Comment by scanny** [comment]
No. The .ppt files (pre-PowerPoint 2007) use a completely different format that is binary and ill-documented (by comparison). It would require almost as much work as what is already in this library to do it, and of course, as time goes by, there is less and less use for it.

If someone did want to do it, I'd be inclined to think a separate library would be the appropriate approach. I suppose that might make it tougher to convert between the two formats, but I'm inclined to consider a converter to be a separate, third job. I can't say that I've thought much about it though.
