### ISSUE TITLE
Alignment of text in a table cell

### ISSUE THREAD

**Issue by MartinPacker** [scanny/python-pptx#340]
It would be really nice to be able to horizontally align text in a table cell. 0.6.7 docs imply this can be done vertically. I would like horizontally - either by column or by cell (as I can confect the former from the latter).

I'm generating Powerpoint from Markdown. Table support has to be rudimentary until this is possible.

**Comment by scanny** [comment]
Horizontal alignment in a table cell is accomplished by setting paragraph alignment (left, center, right) and optionally manipulating the margins. There is no separate horizontal "alignment" property for a table cell. Note that a cell can contain multiple paragraphs, each of which must have alignment set individually.

**Comment by MartinPacker** [comment]
Then the docs (mis)led me to believe there wasn't more than a single piece of plain text you could set a cell to.

Thanks for clearing this up.

I'll experiment.
