### ISSUE TITLE
Add_Picture with Links

### ISSUE THREAD

**Issue by spencerlawrence36** [scanny/python-pptx#344]
Hi, wondering if there is a way add_picture() can support links to images in cloud storage, rather than a local path?  I'm deploying an app that uses pptx and want to be able to store the static files elsewhere.  Currently receiving FileNotFoundError when linking to an image: 

`prs = Presentation('...')
	
blank_slide_layout = prs.slide_layouts[0]
slide = prs.slides.add_slide(blank_slide_layout)

img_path = '...' #link to image in cloud storage, also tried with links to images on public sites

#image placement
left = Inches(0.25)
top = Inches(1.4)
height = Inches(4.06)

pic = slide.shapes.add_picture(img_path, left, top, height=height)`

**Comment by scanny** [comment]
That's something you'd need to provide yourself. You can either resolve the links to a BytesIO object and feed that into `.add_picture()` or you could write an custom file-like object of your own that took a URL on construction and did the downloading on the first call that required the file contents. That object would need to support `read()` I believe, you'd have to trace through the code (or just see what errors you got when you tried it) to see if there are any others, like `seek()` perhaps.

`python-pptx` is a general-purpose library; accordingly it needs to keep itself to the "general" or "common" (as in shared by most users) requirements. This one is more specialized than that and can readily be accommodated by a purpose-built object on your side, what one might call a "CloudFileProxy" object.

**Comment by spencerlawrence36** [comment]
Got it, thanks.
