### ISSUE TITLE
TextFrame.fit_text() -> TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by aluong5** [scanny/python-pptx#345]
There is an issue where if a string without spaces that is in the text frame is too long, a TypeError would be raised. Shouldn't the font size of the text just be decreased until the text fit in the frame?

**Comment by scanny** [comment]
This feature is experimental and will not be the target of any additional effort. Probably the best bet is for you to write your own function to do this job, perhaps using what's there as a starting point.

I'm not sure what PowerPoint does in this scenario. I expect it reduces to some limit and then breaks the line mid-word. In any case, the behavior that's currently there is as sophisticated as we plan to make it.
