### ISSUE TITLE
question: can I use the python-pptx to export the PPT/PPTX as PNG or HTML?

### ISSUE THREAD

**Issue by feikiss** [scanny/python-pptx#348]
Can I use the tool to  export the PPT/PPTX as PNG or HTML? I browsed the User guide and the docs but failed to find the feature :(  . So does python-pptx support the feature?  Thanks!

**Comment by caner** [comment]
It would be a nice feature.

**Comment by scanny** [comment]
No. This feature requires a renderer which `python-pptx` does not and will not have.

If I needed this feature I would look hard at using the Microsoft COM API for it.
