### ISSUE TITLE
change aspect ratio/width of slide

### ISSUE THREAD

**Issue by anekix** [scanny/python-pptx#352]
Is there any we can change the width of overall slide ? ppt generated by python-pptx is square-ish but other slides have a rectangular layout.

**Comment by scanny** [comment]
Aspect ratio is set in template file used as (optional) argument to `Presentation()` call.

There are also `.slide_height` and `.slide_width` properties on the Presentation object, see documentation.

Please use stackoverflow.com with the 'python-pptx' tab in future for support requests.
