### ISSUE TITLE
Problem Inheriting the Presentation Class

### ISSUE THREAD

**Issue by TerryHewitt** [scanny/python-pptx#359]
I would like to inherit the Presentation class, so I have a piece of code like this:

from pptx import Presentation

class  PreEvent(Presentation):
    def __init__(self,CompNO, Year , text='Presentation Evening',  width=None)  
        if template == None:    super().__init__()
        else:    super().__init__(template)

However  when I run it I get,
at the time it parses the line PreEvent(Presentation), not when the class gets instansiated:

exception **unhandled TypeError "function() argument 1 must be code, not str"**

I've Googled the error but can't figure out what to do.

Can anybosy advise a soultion please?

Best wishes
Terry

**Comment by scanny** [comment]
If you look in the code, you'll see that `Presentation` is actually a function https://github.com/scanny/python-pptx/blob/master/pptx/api.py#L20.

The class that ultimately gets constructed is `pptx.presentation.Presentation`. That constructor takes a reference to the presentation part, and might not work properly without it, depending on what calls you make, possibly including `.save()`. So you'll need to have a closer look and see if that's going to work for you.

These classes aren't really designed to be superclasses, so you might want to consider composition instead if you want to build on them somehow.
