### ISSUE TITLE
Add Bullet list using python-pptx

### ISSUE THREAD

**Issue by Puneetsofto** [scanny/python-pptx#364]
I am using the python-pptx library for pptx manipulation. I want to add a bullet list in the pptx document. 

I am using the following snippet to add list item:

    p = text_frame.add_paragraph()
    run = p.add_run()
    p.level = 0
    run.text = "First"

But it does not display bullet points. Please guide.

Quick response will be appreciated.

**Comment by scanny** [comment]
Please use StackOverflow for support questions (using the 'python-pptx' tag). The issues list is reserved for feature requests and suspected bugs.

**Comment by Puneetsofto** [comment]
Hi @scanny 

As suggested, I have asked this question on stackoverflow. Following is the link:

https://stackoverflow.com/questions/49384134/add-bullet-list-using-python-pptx

Can you please look into this?

**Comment by SeanNamEcoation** [comment]
Is there any update on this?
