### ISSUE TITLE
Updating Shape Element XML

### ISSUE THREAD

**Issue by CanePunma** [scanny/python-pptx#365]
I was looking to update the text for Merged Shapes or CT_GroupShape and found that there was no easy way to do this. I have traversed the XML tree of the shape and have updated the text in the tree structure. Although, I do not see a way to update the corresponding ._element.xml object that will result in the change in the original slide. 

```
for sld in prs.slides:
      for shp in sld.shapes:
               new_tree = UpdateXMLFunction(shp._element.xml)

               new_tree = serialize_for_reading(new_tree) ??
               shp._element = new_tree ??

```

It looks like the BaseOxmlElement classes work in sert data into childs. How should we be updated the xml trees for these objects? Or is there an easier to update the text in grouped shape files other than going through the XMLs. Any help would be appreciated, thanks.

**Comment by scanny** [comment]
A group shape cannot have a text frame (and so cannot have text).

**Comment by CanePunma** [comment]
It seems you should be able to edit the texts at <t> </t> for all the shapes within the grouped shape in the XML. Although, is there a way to update the xml tree for the shape like something above?

**Comment by scanny** [comment]
Are you saying set them all to the same text? Or are you asking how to iterate through the shapes in a group?

**Comment by CanePunma** [comment]
Well both, iterate through the shapes then set each of their texts to something different.

**Comment by scanny** [comment]
So your question is really: "How do I iterate the shapes contained in a group shape". Once you have a shape, you set its text just as you would any other shape.

There's no API support for this at the moment, but as luck would have it I'm working on this as we speak. If you install the `spike` branch, you should be able to do the following:

```python
for shape in slide.shapes:
    if shape.shape_type != MSO_SHAPE_TYPE.GROUP:
        continue
    group_shape = shape
    group_shapes = group_shape.shapes
    for shape in group_shapes:
        if not shape.has_text_frame:
            continue
        shape.text = 'foobar'
```

**Comment by CanePunma** [comment]
I got it working with the spike branch, thank you!
