### ISSUE TITLE
Backwards compatibility (Python 2.7) issue in freeform.py

### ISSUE THREAD

**Issue by amsjacks** [scanny/python-pptx#368]
When using 2.7, `convert_to_shape()` throws a `TypeError` complaining about a `long` that needs to be an `int` even when no `long`s are passed-in. Stepping through, this looks to me like the `long` in question is `self._dy`, which is 0 in my case. (`self._dx` is a (non-zero) `int`.)

**Comment by scanny** [comment]
Please provide calling code and actual stack trace.

**Comment by amsjacks** [comment]
Code to reproduce:
`from pptx import Presentation`

`coordinates = [457200, 1600200]`
`points = [(0.0, 29228449251060.95), (8229600.000000001, 29228449251060.95)]`

`prs = Presentation()`
`sl = prs.slide_layouts[1]`
`slide = prs.slides.add_slide(sl)`
`shape_tree = slide.shapes`

`freeform = shape_tree.build_freeform(*points[0])`
`freeform.add_line_segments(points[1:], close = points[0] == points[-1])`
`freeform.convert_to_shape(*coordinates)`

It works in 3.6, but breaks in 2.7.

Stack trace: 
>   File "\pptx\shapes\freeform.py", line 85, in convert_to_shape
>     path = self._start_path(sp)
>   File "\pptx\shapes\freeform.py", line 211, in _start_path
>     path = sp.add_path(w=self._dx, h=self._dy)
>   File "\pptx\oxml\shapes\autoshape.py", line 173, in add_path
>     return pathLst.add_path(w=w, h=h)
>   File "\pptx\oxml\shapes\autoshape.py", line 118, in add_path
>     path.w, path.h = w, h
>   File "\pptx\oxml\xmlchemy.py", line 205, in set_attr_value
>     str_value = self._simple_type.to_xml(value)
>   File "\pptx\oxml\simpletypes.py", line 23, in to_xml
>     cls.validate(value)
>   File "\pptx\oxml\simpletypes.py", line 559, in validate
>     cls.validate_int_in_range(value, 0, 27273042316900)
>   File "\pptx\oxml\simpletypes.py", line 55, in validate_int_in_range
>     cls.validate_int(value)
>   File "\pptx\oxml\simpletypes.py", line 41, in validate_int
>     "value must be <type 'int'>, got %s" % type(value)
> TypeError: value must be <type 'int'>, got <type 'long'>

**Comment by scanny** [comment]
k, got it, thanks.

I've put in the fix in the main code, it will be out with the next release in a month or so.

In the meantime, if you can run a local version, make the `validate_int()` method in `pptx.oxml.simpletypes` line 39 look like this:

```python
@classmethod
def validate_int(cls, value):
    if not isinstance(value, numbers.Integral):
        raise TypeError(
            "value must be an integral type, got %s" % type(value)
        )
```

**Comment by scanny** [comment]
Note that this is happening because the numbers you're using are greater than `sys.maxint` (varies with 32/64-bit versions). So another workaround might be to divide numbers by a power of 10 big enough to bring them under `maxint` but small enough not to distort the actual image produced. On an actual screen there are only about 2500 pixels in any direction, so you should be able to reduce the actual magnitudes by quite a few orders of magnitude without actually changing the shape that gets drawn.

Just in case that's an easier stop-gap option since it doesn't involve code changes.

**Comment by amsjacks** [comment]
Great! Thanks for the quick turnaround and advice on stopgap strategies.
