### ISSUE TITLE
Can't adjust font size of chart title 

### ISSUE THREAD

**Issue by SaturnFromTitan** [scanny/python-pptx#370]
Hello,
I need to adjust the title font size in some charts I created. I try to follow the documentation, but the option doesn't seem to be available: https://python-pptx.readthedocs.io/en/latest/api/chart.html#pptx.chart.chart.ChartTitle

It seems like .format only provides access to fill and line properties, which don't seem useful for the title. Also there are no font property like you have for category/value axis (like used here to adjust the label fonts: https://python-pptx.readthedocs.io/en/latest/user/charts.html).

Is this feature really missing?

Thanks for your help

**Comment by scanny** [comment]
Title text and formatting are adjusted using the text frame, as in any regular shape.
https://python-pptx.readthedocs.io/en/latest/user/text.html
