### ISSUE TITLE
Feature request: Combo Chart - Clustered Column with Line

### ISSUE THREAD

**Issue by pdauer** [scanny/python-pptx#372]
Hello,

is it in planning to support in the near furture clustered column charts with a secondary axis to draw a line for, i.e. a rate of values? See red line in the pic.

![image](https://user-images.githubusercontent.com/7793792/38503579-b9fa95f0-3c12-11e8-9b7c-afff4d6922b7.png)

**Comment by jbq** [comment]
Duplicates #338

**Comment by scanny** [comment]
Thanks @jbq :)
