### ISSUE TITLE
Add Color to shape

### ISSUE THREAD

**Issue by nikhilkabbin** [scanny/python-pptx#38]
I can't seem to find a way to set the shape color.

**Comment by BusLeonard** [comment]
Hey there, I'm enjoying pptx so far. I'm working with gradient fills of shapes. Did this end up getting built out?

**Comment by haystacr** [comment]
Built a star, but can't seem to fill in the body of the star, only the actual turtle pointer itself. Using 3.6.5 but I did see it was possible in 3.6.0. Any ideas?

**Comment by tracyneproski** [comment]
I am copying and pasting this code and continue to get "AttributeError: 'SlideShapes' object has no attribute 'fill'." Any thoughts on why this is happening?

**Comment by scanny** [comment]
Sounds like you're assigning a `SlideShapes` object to `shape` before running that code, perhaps `shape = slide.shapes`, which is confusing an individual shape with the collection it lives in.

That code needs to be run on an individual shape, perhaps something like `shape = slide.shapes[0]`.
