### ISSUE TITLE
How can i copy a slide for a new slide

### ISSUE THREAD

**Issue by coder-pig** [scanny/python-pptx#389]
I want to read slide from a ppt，copy to a new PPT，and keep the anim
Then i wirte code:

```
    pre = Presentation('test.pptx')
    presentation = Presentation('1.pptx')
    pre.slides.add_slide(presentation.slides[14].slide_layout)
    pre.save('test.pptx')
```

when i run the code：

The console print：

![image](https://user-images.githubusercontent.com/6879486/40725290-9ba8af90-6455-11e8-975a-cd2fa4addfdc.png)

when i open the test.pptx，happen this：

![image](https://user-images.githubusercontent.com/6879486/40725260-887e9fc4-6455-11e8-8964-b80fed15b53d.png)

How can fix it？If you know，please tell me，ths~

**Comment by scanny** [comment]
`python-pptx` does not support cross-presentation operations like copying a slide from one presentation to another presentation or using one presentation's slide layout to form a slide in another presentation.

**Comment by OldAAAA** [comment]
Can i copy a slide from a presentation and add it to the same presentation

**Comment by to175** [comment]
Hi, when feature will be available please ? How much to invest to make it ?
