### ISSUE TITLE
feature: DataLabels.show_{label} properties

### ISSUE THREAD

**Issue by jdelight** [scanny/python-pptx#395]
When building a pie chart with a series of 3 values (1, 8, 1). I would expect to see segments with data labels 10%, 80% and 10%.

However, with the code below I see 100%, 800% and 100% when initially opening the new.pptx file. Once I've clicked on a chart style preset it seems to revert to the expected percentages.

```python
from pptx import Presentation
from pptx.chart.data import ChartData
from pptx.enum.chart import XL_CHART_TYPE, XL_LEGEND_POSITION, XL_DATA_LABEL_POSITION
from pptx.util import Inches

prs = Presentation()

slide = prs.slides.add_slide(prs.slide_layouts[0])

chart_data = ChartData()
chart_data.categories = ['cat a', 'cat b', 'cat c']
chart_data.add_series('Series 1', (1, 8, 1))

x, y, cx, cy = Inches(2), Inches(2), Inches(6), Inches(4.5)


chart = slide.shapes.add_chart(
    XL_CHART_TYPE.PIE, x, y, cx, cy, chart_data
).chart

chart.has_legend = True
chart.legend.position = XL_LEGEND_POSITION.BOTTOM
chart.legend.include_in_layout = False

chart.plots[0].has_data_labels = True
data_labels = chart.plots[0].data_labels
data_labels.number_format = '0%'
data_labels.position = XL_DATA_LABEL_POSITION.OUTSIDE_END
prs.save('new.pptx')

```
This is the screenshot for code above

![00b294bb-6568-4ec1-b7b1-95e17a3a6919](https://user-images.githubusercontent.com/1387956/41691380-38b2ce18-74f2-11e8-8fb0-0c54748ba511.png)

Here's the panel I'd like to have access to from python-pptx ... i.e. to change to show percentage
![image](https://user-images.githubusercontent.com/1387956/41691094-b2f2ecdc-74f0-11e8-8f09-5b9360d0a04d.png)

Any thoughts on why the percentage values are multiplied by 10? If i change the panel immediately above to show percentages and values the the correct data labels are shown.

**Comment by jdelight** [comment]
Looks like changing the values in the xml for data labels "fixes" this.
see `/pptx/oxml/chart/datalabel.py`

```python
    @classmethod
    def new_dLbls(cls):
        """Return a newly created "loose" `c:dLbls` element."""
        return parse_xml(
            '<c:dLbls %s>\n'
            '  <c:showLegendKey val="0"/>\n'
            '  <c:showVal val="0"/>\n'
            '  <c:showCatName val="1"/>\n'  # <-- here 
            '  <c:showSerName val="0"/>\n'
            '  <c:showPercent val="1"/>\n'  # <-- here
            '  <c:showBubbleSize val="0"/>\n'
            '  <c:showLeaderLines val="1"/>\n' # <-- this is new, but works
            '</c:dLbls>' % nsdecls('c')
        )
```

Would be great to have access to set these on the data point. Perhaps something like:

```python
data_labels.show_series_name = True
data_labels.show_category_name = True
data_labels.show_value = True
data_labels.show_percentage = True
data_labels.show_leader_lines = True
```

**Comment by scanny** [comment]
Added in release v0.6.16 circa November 9, 2018.

No access to bubble-size or leader-lines, but the other five are in there as e.g. `DataLabels.show_percentage` (read/write boolean).

**Comment by jdelight** [comment]
Fantastic stuff @scanny - thank you!

**Comment by SaiRahul-Draup** [comment]
for doughnut; datalabels.show_category_name = True is not working...
