### ISSUE TITLE
feature: Add table or modify existing table

### ISSUE THREAD

**Issue by mitchhung** [scanny/python-pptx#397]
Hi!

Thanks for your work on this project. I'm hoping to reopen a feature request that you guys started a few years ago.

[Link](https://github.com/scanny/python-pptx/issues/77)

> a) Have a table placeholder shape in my layout, and stuff a table into it - this doesn't seem to be possible as I can't set rows,cols etc on an existing table shape
or b) Create a new table shape using the height,width,left,top etc from a placeholder shape in the layout. This seems to fail as the actual shape in the slide ends up with height,width,top,left all set to 0. The cloned placeholder shape seems to not copy these values into the local shape?

Additionally, would it be possible to modify the dimensions of an existing table (i.e. rows/columns)?

Wondering if there was any work on this that wasn't merged or if a solution could be cobbled together.

Thanks in advance,
Mitch

**Comment by scanny** [comment]
Check out `TablePlaceholder.insert_table()`:  
https://python-pptx.readthedocs.io/en/latest/api/placeholders.html#pptx.shapes.placeholder.TablePlaceholder.insert_table

The inserting row/column feature is pending, but described in another open issue.
