### ISSUE TITLE
ChartData.add_series() displays number_format integer in PPT until data is accessed

### ISSUE THREAD

**Issue by inmanenz** [scanny/python-pptx#401]
Hey all,

First time posting so I apologize if I break any conventions. I am using Chart.replace_data to automatically update data on a chart shape in a powerpoint template and I think I may have found a bug. Below you will see my code.

```{python}
slide=prs.slides[6].shapes
chart_data=ChartData()
chart_data.categories=["CAT1","CAT2","CAT3","CAT4"]
chart_data.add_series("Series Name",(val1,val2,val3,val4), 9)
chart=find_shape_by_name("Chart1").chart
chart.replace_data(chart_data)
```

For some reason once I save and open the powerpoint, the chart in question displays the number_format (in this case 9) for each category. But in powerpoint if you go to view the data in excel, it contains the correct numbers and will adjust the chart accordingly. I'd like to avoid this additional step as the rest of the powerpoint is being populated automatically.

![aafb70f5](https://user-images.githubusercontent.com/13397392/42337755-b4d15c44-8055-11e8-9fb3-0ee252bdfc0d.PNG)

Thanks for your help!

**Comment by scanny** [comment]
I'm not getting your question. Please describe step-by-step what you do, what you get at each step, and how that differs from what you're expecting.

**Comment by DZemens** [comment]
I've observed the same bug with respect to Axis labels. 

If I create a series by using the format string:

`chart_data.add_series("Series Name",(val1,val2,val3,val4), '0%')`

The axis labels appear like 10%, 20%, ... 90%, 100%

If instead I create the series by using the constant values defined in ExcelNumFormats enum (NB: this doesn't appear to be a part of `pptx.enum.chart` even though it's listed in the dox beneath that enum...), then the axis labels all appear like: 9, 9, ... 9, 9

![image](https://user-images.githubusercontent.com/11669299/42355937-b4216170-809d-11e8-881d-aec4343672de.png)


As soon as I right-click the chart and "Edit Data" from PowerPoint, then the labels appear properly.

![image](https://user-images.githubusercontent.com/11669299/42355928-a734baa2-809d-11e8-9076-5d19b8ac94ea.png)

**Comment by inmanenz** [comment]
@DZemens That worked perfect. @scanny does @DZemens post help clear up what I was

**Comment by scanny** [comment]
Okay, looks like the documentation got ahead of the implementation. The numeric built-in number formats appear to not have gotten implemented and probably won't for a while.

I'll tag this ticket to update the documentation at least for the next release and to get those in there next time we're in the neighborhood.

**Comment by scanny** [comment]
Documentation was updated to remove indication of support for Excel built-in formats. All cell formats must be specified by string, e.g. "0.0%".
