### ISSUE TITLE
Take snapshot of each slide

### ISSUE THREAD

**Issue by sharad-paghadal** [scanny/python-pptx#405]
Is there any way to take snapshot of each slide and save as png?

**Comment by DZemens** [comment]
python-pptx is [essentially a wrapper for OpenXML](http://python-pptx.readthedocs.io/en/latest/dev/resources/about_packaging.html), as such, it doesn't interact with a "presentation" the way you are accustomed to thinking about them from the user perspective (i.e., opening a file in the PowerPoint application, etc.) 

"Taking a snapshot" requires accessing, among other things, the presentation/slide object as it appears in UX. This usually means using Interop/COM to access an instance of the PowerPoint.Application class. pptx simply does not handle presentations this way. But you could easily export to image files using win32com, for instance.

This might be helpful:

https://support.microsoft.com/en-us/help/827745/how-to-change-the-export-resolution-of-a-powerpoint-slide

**Comment by zx1986** [comment]
Could python-pptx do this in UNIX like machine?

**Comment by DZemens** [comment]
@zx1986 no, for the same reason outlined in my reply above. (Note: I do not maintain or develop the python-pptx library). This is OS-independent. When working with python-pptx or python-docx, you're working only with the OpenXML representation of the objects, there is simply no "slide" to take a screenshot of, until/unless you open the file in PowerPoint application. You can do that, as mentioned above, with win32com library.
