### ISSUE TITLE
best_fit_font_size unexpected behaviour

### ISSUE THREAD

**Issue by chrboe** [scanny/python-pptx#429]
I'm trying to find out whether or not a text will fit into a shape. What I'm doing is basically creating a rectangle, adding some text to its TextFrame, and using `TextFitter.best_fit_font_size` to find out whether or not the text fits. If the returned font size is smaller than my max size (which also happens to be the font size of the text), I know that the shape is too small to fit the text.

However, the function is not at all behaving like I expected. Here's an example:
<details><summary> Code </summary>

```python
from pptx import Presentation
from pptx.enum.shapes import MSO_SHAPE
from pptx.enum.text import MSO_ANCHOR, PP_ALIGN
from pptx.util import Cm, Pt
from pptx.text.layout import TextFitter
from pptx.text.fonts import FontFiles
from pptx.dml.color import RGBColor

def create_box(slide, left, top, width, height, items):
    box = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, left, top, width, height)
    box.shadow.inherit = False
    box.fill.solid()
    box.fill.fore_color.rgb = box.line.color.rgb = RGBColor(230, 230, 230)
    frame = box.text_frame
    frame.vertical_anchor = MSO_ANCHOR.TOP
    frame.word_wrap = True

    first = True
    for item in items:
        if first:
            p = frame.paragraphs[0]
            p.alignment = PP_ALIGN.LEFT
            first = False
        else:
            p = frame.add_paragraph()

        r = p.add_run()
        r.text = '- ' + item

        r.font.size = Pt(12)
        r.font.color.rgb = RGBColor(0, 0, 0)

    font_file = FontFiles.find('Calibri', False, False)
    fit = TextFitter.best_fit_font_size(frame.text, frame._extents, 12, font_file)
    print('best fit: %d' % fit)

def main():
    prs = Presentation()

    # make widescreen (16:9)
    prs.slide_width = Cm(33.867)
    prs.slide_height = Cm(19.05)

    slide_layout = prs.slide_layouts[6]
    slide = prs.slides.add_slide(slide_layout)

    create_box(slide, Cm(2), Cm(2), Cm(5), Cm(9), ['test'])
    create_box(slide, Cm(8), Cm(2), Cm(5), Cm(2), ['test', 'abc', '123', 'testing', 'some long line that will probably overflow'])

    prs.save("pres.pptx")

if __name__ == "__main__":
    main()
```
</details>

---

This gives the following result in PowerPoint:
![image](https://user-images.githubusercontent.com/1276064/44851653-56a10b00-ac61-11e8-814a-2d226ebbcd2a.png)

It's immediately apparent that the box on the right overflows quite significantly. However, `best_fit_font_size` gives the result `12` every time. I don't know if I'm missing something, but as I see it the second value should definitely be something lower (like 10).

If I raise the `max_size` to something higher (say, 20), the results are equally as confusing. It returns `20` for the leftmost box (this is expected, since the box is clearly big enough to fit that size), but `13` for the rightmost box. This doesn't make any sense, because the algorithm seems to make the font size even bigger than it already is, despite the fact that the container is already way too small in the first place.

Any ideas?

**Comment by scanny** [comment]
I think you're on your own to puzzle through the code on this one. This is an experimental feature that worked for the intended purpose and also convinced us we didn't want to be fooling around with rendering-related features without much more robust font-metrics support in Python.
