### ISSUE TITLE
fix: Series.values accommodates #NA and #DIV/0

### ISSUE THREAD

**Issue by akashsharma03** [scanny/python-pptx#441]
Hi ,

Whenever there is a #NA or #DIV/0  in the series' values, it gives an error when trying to retrieve it through
series.values.

Is there any workaround for this?

**Comment by scanny** [comment]
Please provide a small example .pptx file and the resulting stack trace.

**Comment by akashsharma03** [comment]
Hi Steve,
I figured out the issue. Its because when we try to get the series.values , it returns the values by casting it to float type which gives an error whenever the value is a string and not a valid float literal.
To fix that I had to change pptx code. 
Could Not find a way to handle it.
Here's the line of code : pptx\oxml\chart\series.py , line 227

**Comment by scanny** [comment]
Closing as incomplete. If someone can provide an example file that demonstrates this behavior I'll take another look.

**Comment by Db-pckr** [comment]
@scanny Just encountered the same issue, essentially if a chart has non numeric data within the series (text like #N/A), accessing series values returns the error described by OP.


```
from pptx import Presentation

# Load your presentation
prs = Presentation('your_presentation.pptx')

# Access a specific slide (0 for the first slide)
slide = prs.slides[0]

# Find the chart in the slide (assuming it's the first shape)
chart = slide.shapes[0].chart

# Access the first series
series = chart.series[0].values
```


It's because of the following in the library:


```
class CT_StrVal_NumVal_Composite(BaseOxmlElement):
    """
    ``<c:pt>`` element, can be either CT_StrVal or CT_NumVal complex type.
    Using this class for both, differentiating as needed.
    """

    v = OneAndOnlyOne("c:v")
    idx = RequiredAttribute("idx", XsdUnsignedInt)

    @property
    def value(self):
        """
        The float value of the text in the required ``<c:v>`` child.
        """
        return float(self.v.text)
```


return float() cannot work for non numeric data.

**Comment by MartinPacker** [comment]
If it were to be in a `try` / `except` pair of brackets what would you want the failure case to do?

**Comment by Db-pckr** [comment]
Why not just return self.v.text without wrapping it with float()?
