### ISSUE TITLE
Unable to Create THREE_D_COLUMN_CLUSTERED Charts in ppt

### ISSUE THREAD

**Issue by srinivas946** [scanny/python-pptx#445]
With python pptx i can easily create the 2D charts but when come to 3D Charts i'm unable to do. When i tried to create Chart type as THREE_D_COLUMN_CLUSTERED i'm getting Non Implemented Error(54).
I Want a feature for creating 3D Charts

**Comment by scanny** [comment]
Duplicate of #266.
