### ISSUE TITLE
table: add merge cells feature

### ISSUE THREAD

**Issue by scanny** [scanny/python-pptx#45]
Add feature(s) allowing table cells to be merged.

**Comment by syamajala** [comment]
Any progress on this?

**Comment by mitchelljkotler** [comment]
I'd be interested in this as well

**Comment by smcpherson** [comment]
:+1:  on this

**Comment by smcpherson** [comment]
FWIW, This seems to work for me: https://groups.google.com/forum/#!topic/python-pptx/cVRP9sSpEjA

**Comment by scanny** [comment]
`_Cell.merge()` as well as a collection of other cell-merging goodies will appear in v0.6.14 to be released circa Sep 23, 2018.
