### ISSUE TITLE
Unable to Edit Chart content

### ISSUE THREAD

**Issue by Miguel-Caringal** [scanny/python-pptx#458]
Hi, when I try to edit an existing chart that I made in powerpoint, I get:

```
Traceback (most recent call `last):`
  File "C:\Python27\lib\site-packages\pptx\chart\chart.py", line 178, in replace_data
    self._workbook.update_from_xlsx_blob(chart_data.xlsx_blob)
  File "C:\Python27\lib\site-packages\pptx\parts\chart.py", line 69, in update_from_xlsx_blob
    xlsx_part = self.xlsx_part
  File "C:\Python27\lib\site-packages\pptx\parts\chart.py", line 85, in xlsx_part
    return self._chart_part.related_parts[xlsx_part_rId]
KeyError: 'rId3'
```
Has anyone else run into this problem before? Stackoverflow seems to have a similar question asked but not answered: https://stackoverflow.com/questions/47817819/python-pptx-how-to-update-or-replace-a-chart-series

**Comment by scanny** [comment]
@Miguel-Caringal you should post this question on StackOverflow and be sure to use the 'python-pptx' tag. This issues list isn't the right place for support questions.

Make sure you post your code as well and be sure to mention the provenance of the original pptx file with the chart. This would seem to indicate a corrupted pptx file. If you try this on one you make yourself I expect you won't see such an error.
