### ISSUE TITLE
Click_Actions

### ISSUE THREAD

**Issue by hioutheworld** [scanny/python-pptx#462]
Hi, 
i'm trying to recreate a simple PP_Action. 
The code below built without errors however the click action will not run.  
'shape.click_action.action' returns with NONE(0) after action is being assigned. 
Is there anything wrong with the code? Couldn't find a base example on this. 
Please help.

from pptx import Presentation
from pptx.enum.shapes import MSO_SHAPE
from pptx.util import Cm
from pptx.enum.action import PP_ACTION

prs = Presentation('C:/Template.pptx')
slide = prs.slides.add_slide(prs.slide_layouts[0])
shape = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Cm(-0.05),Cm(0.86),Cm(34),Cm(19))
shape.click_action.action == PP_ACTION.LAST_SLIDE
print(shape.click_action.action)
slide = prs.slides.add_slide(prs.slide_layouts[0])
slide = prs.slides.add_slide(prs.slide_layouts[0])
prs.save('C:/example.pptx')

**Comment by scanny** [comment]
Please post support questions on StackOverflow. Be sure to use the `python-pptx` tag.

https://stackoverflow.com/questions/tagged/python-pptx
