### ISSUE TITLE
wrong font size for doughnut chart title

### ISSUE THREAD

**Issue by qirh** [scanny/python-pptx#464]
Hey! Sorry if this isn't in the correct format, this is my first issue at an open source project, so if there's something I could do better in the future please let me know.

I was trying to read the font size  for a chart title in a doughnut chart using `shape.chart.chart_title.text_frame.paragraphs[0].font.size` and was getting wrong results (getting `18.62` when the actuual size in the slides is `12`).

I looked at the xml and found and found this part

```xml
<a:p>
    <a:pPr>
        <a:defRPr sz="1862" b="0" i="0" u="none" strike="noStrike" kern="1200" spc="0" baseline="0">
        <a:solidFill>
            <a:schemeClr val="tx1">
            <a:lumMod val="65000"/>
            <a:lumOff val="35000"/>
            </a:schemeClr>
        </a:solidFill>
        <a:latin typeface="+mn-lt"/>
        <a:ea typeface="+mn-ea"/>
        <a:cs typeface="+mn-cs"/>
        </a:defRPr>
    </a:pPr>
    <a:r>
        <a:rPr lang="en-US" sz="1200" dirty="0">
        <a:latin typeface="Arial" panose="020B0604020202020204" pitchFamily="34" charset="0"/>
        <a:cs typeface="Arial" panose="020B0604020202020204" pitchFamily="34" charset="0"/>
        </a:rPr>
        <a:t>TITLE</a:t>
    </a:r>
</a:p>
```

`<a:defRPr>` has the size of `18.62` which is why I was getting that number, but the correct size which is `12` is under `<a:rPr>`. Is that a bug or am I misusing the function?

**Comment by scanny** [comment]
Support and informational questions (like this one) are best posted on StackOverflow, using the 'python-pptx' tag. These are generally answered promptly and then are easy to find on search by later folks with the same question.
 
Character formatting (font) is ultimately applied at the run level. So if you wanted to see that it would be `text_frame.paragraphs[0].runs[0].font.size`. You can immediately see the complication, that there is no guarantee a chart title has only a single run and therefore could have multiple font sizes.

But probably the bigger issue is that you've encountered the style hierarchy, which is a fairly complex system of inheritance of properties like font-size. In general, if a property is not specified at a lower level (like `a:rPr`) it is inherited from the next higher level (like `a:defRPr`) and so on up to presentation or built-in defaults, perhaps 5-7 levels. Think of this as the "effective" font-size, the size you see on the screen.

`python-pptx` has no API support for discovering the effective settings for inherited parameters, so if you want those you need to discover the style hierarchy for that particular item and traverse the hierarchy yourself to find the first level at which it is defined.

**Comment by qirh** [comment]
Thanks Steve, I'll make sure to head to SO first in the future.

Is there documentation that you can recommend for openxml, somewhere where I an learn more about xml tags and how they interact with one another.
