### ISSUE TITLE
feature: slide/master background fill

### ISSUE THREAD

**Issue by jhludwig** [scanny/python-pptx#47]
Request: add ability to a) examine and b) change some elements of a theme -- notably the background color.

My method for doing this in Powerpoint 2013 on Windows is to:
    View...Slide Master
    Slide Master....Background...Colors to pick a presentation-wide theme
    Slide Master....Background Styles to shift entire deck to dark or light backgrounds

**Comment by apiszcz** [comment]
Note: You can change the properties of pptx\tempaltes\default.pptx for background color, default font, etc. All new Presentation() calls use the default styles.

**Comment by scanny** [comment]
It's probably easier just to call a custom template file in the Presentation() call, that way you can choose different defaults for different projects and avoid having to patch the installation each time.

`Presentation()` takes a filename as a parameter and opens that file the same way it opens `default.pptx` when provided. If you look at the code you'll see that all `Presentation()` does is check to see if a file path was provided, and if not it substitutes the default.pptx.

**Comment by apiszcz** [comment]
Tried the full path
Presentation(pkg_file=os.path.abspath(r'cfg\pptx\darktheme.pptx'))
no error, but not finding theme, will try file object

**Comment by scanny** [comment]
Slide.background and SlideMaster.background were added in release 0.6.9 on Wed May 9, 2018.
