### ISSUE TITLE
UnicodeEncodeError on Win10, Python 3.6.6

### ISSUE THREAD

**Issue by miek770** [scanny/python-pptx#471]
Hi,

I followed these steps to handle a powerpoint file in Git: [https://www.ficonsulting.com/filabs/MSOfficeGit](https://www.ficonsulting.com/filabs/MSOfficeGit)

When using `git diff` after having modified an MS Office 365 ProPlus powerpoint file, I get the following error:

```
$ git diff
Traceback (most recent call last):
  File "C:/Users/michela.lavoie/gits/formation_etap/formation_etap/pptx-textconv.py", line 19, in <module>
    print(text_runs)
  File "C:\Python36\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u221a' in position 19069: character maps to <undefined>
fatal: unable to read files to diff
```

It appears to be related to #139, but I'm using version 0.6.17 of `python-pptx`, installed from PyPI.

I'm running git bash in mintty 2.6.2 (x86_64-pc-msys).

The offending character '\u221a' appears to be a square root.

Apart from the powerpoint file itself, would you need additional information to point me in the right direction? Should I use another terminal?

Thank you,

Michel

**Comment by miek770** [comment]
Indeed, this worked: `print([run.encode("UTF-8") for run in text_runs])`. Thank you.

**Comment by scanny** [comment]
Glad you got it working :)
