### ISSUE TITLE
Creating slides based on layout, how to obtain the layout's placeholder text

### ISSUE THREAD

**Issue by paulbaumgarten** [scanny/python-pptx#475]
I'm creating a Python program to create a few hundred slides from a datasource. Each record in that datasource will result in about 6 slides. I have created a bunch of layout slides as the template for each record. In the placeholders I created in the layout sides, I placed text such as "{givenName}". My intention was that when creating a slide based on a layout, I would then use Python string templating to merge in the values from each record. Unfortunately I can't seem to figure out how to determine which layout placeholder shape is linked to which shape on the derived slides.

I know that `slide.slide_layout.placeholders` gives me the placeholder shapes that were in the layout, and I can get the text value of each of those easily enough. These text values do contain what I expect. The problem comes, when I iterate through slide.placeholders, I can't seem to find any attribute that tells me which of the slide_layout.placeholders that particular shape is based off. I've tried going several items deep in the various attributes can't can't seem to find the way to link the two bits together.

Looking at shape_id's doesn't seem to help. As an example, in one slide the slide.layout.placeholders have shape_id's of 6, 7, 8, 12 where as the slide.shapes.shape_id's are 3, 4, 5, 2. There doesn't seem to be any attribute that provides the link. I even tried just going in sequential order of iteration but that didn't work correctly either.

I've spent hours experimenting with different options and navigating the api documentation to no avail. Any assistance would be greatly appreciated!

**Comment by scanny** [comment]
I think the documentation page you're looking for is this one:  
https://python-pptx.readthedocs.io/en/latest/user/placeholders-using.html#access-a-placeholder

The idea is that a _layout_ placeholder has a particular _idx_ identifier, in addition to its _id_ value. This identifier is assigned to the `idx` attribute of each placeholder shape "cloned" from that placeholder when a slide is created from it. A particular placeholder is accessed on a slide using the `idx` value as a key (like a dict): `shape_I_am_looking_for = slide.placeholders[idx_for_that_placeholder]`.

The idx value is arbitrarily assigned by PowerPoint when you create the layout, but it is unique and stable. So the idea is to create your layout, interrogate it with python-pptx to identify the `idx` values of its placeholders, then use them for access. It might make sense to make those constants in your code, like `GIVEN_NAME = 11` or something like that.

If I had this design point to do over, I think I'd avoid the dict-style interface and use something like `placeholders.get_by_idx(idx)` instead, but there it is and once figured out it should work reliably.

Let us know how you go.

Btw, please post support questions like these in StackOverflow using the "python-pptx" tag, that way more folks can benefit from the investment in answers.

**Comment by paulbaumgarten** [comment]
Perfect, thank you!
And you're right about the StackOverflow thing, don't know why I didn't post it there. 
Thanks again
