### ISSUE TITLE
How to read the text (or data) of an existing chart？

### ISSUE THREAD

**Issue by 873206010** [scanny/python-pptx#476]
.pptx document lost data connection,regular program does not work. So,I want read important information on the chart。How can do it? Thanks

**Comment by samredway** [comment]
Also have a problem that I can't read all of the text from an existing chart - not sure if this is me just not finding the information or if this functionality is either not implemented or buggy?

I am on latest mac osx. Python 3.7

I have a chart which has labels on the x axis and also has a legend:

<img width="558" alt="Screenshot 2019-05-21 at 05 47 11" src="https://user-images.githubusercontent.com/9790841/58069121-f30e9300-7b8b-11e9-8faa-5489d2eb2b1e.png">

So:

I can get the title with:

`shape.chart.chart.title.text_field.text`

but although:

`shape.chart.has_legend == True`

legend has no text_filed?

Also 

`shape.chart.value_axis.axis_title.has_text_frame == False`

So where is the text for the axis (ie Ferrari and Tesla)?

**Comment by scanny** [comment]
The "Tesla" and "Ferrari" text is the chart categories. Those are available on `chart.plots[0].categories`.
