### ISSUE TITLE
Is it possible to remove all the lines in a graph using this library in creating a clustered bar graph? 

### ISSUE THREAD

**Issue by mackinleyhills** [scanny/python-pptx#483]
<img width="608" alt="screen shot 2019-02-22 at 6 55 14 pm" src="https://user-images.githubusercontent.com/47887723/53238144-804c6380-36d3-11e9-9633-78ee75ef9093.png">

**Comment by scanny** [comment]
Please post support questions on StackOverflow using the `python-pptx` tag. There are several folks who monitor that tag and will see your question. Short answer is yes. I can provide more details if you post on SO where other folks can find the answer later.

**Comment by mackinleyhills** [comment]
i tried to change the color to white for it not to become visible. but should there be an another way?
