### ISSUE TITLE
DeprecationWarning: Using or importing the ABCs from 'collections'

### ISSUE THREAD

**Issue by kjswanson** [scanny/python-pptx#492]
The issue: Deprecation warning: 

```
..../lib/python3.7/site-packages/pptx/dml/fill.py:9: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Sequence
```

This issue was found when running pytest on some code that imports the python-pptx module.

I have searched around to see if others have brought this up. I did not find any other mentions of this issue related to python-pptx, however it is mentioned a lot with other python modules.

ex: scikit learn -> https://github.com/scikit-learn/scikit-learn/issues/11121

Hope this helps for future development, I find this to be a very useful module.

Keep up the good work, Thanks!

**Comment by tirkarthi** [comment]
I think this is fixed by https://github.com/scanny/python-pptx/commit/d5a1957e890870738329b104eb0c57127ebec6b9.

**Comment by scanny** [comment]
Yes, good catch, thanks @tirkarthi :)

I had neglected to retire this issue after those changes.
