### ISSUE TITLE
Control Doughnut Chart Hole Size

### ISSUE THREAD

**Issue by melosfox** [scanny/python-pptx#493]
It would be ideal for me to be able to control the size of the doughnut chart's hole through python. 

If this is already possible, how can it be controlled? 

Thanks!

**Comment by qirh** [comment]
yes it is possible to set the hole size by overwriting the xml.

The xml node you need to change is here
`/c:chartSpace/c:chart/c:plotArea/c:doughnutChart/c:holeSize`


I set it with this line

```
hole_size = 65
chart.element.xpath('/c:chartSpace/c:chart/c:plotArea/c:doughnutChart/c:holeSize')[0].set('val', hole_size)
```

**Comment by melosfox** [comment]
Ah. Thank you. I'm still learning, and I appreciate your help.

I'll direct future questions of this kind to stackoverflow. 

For future reference to those looking for a similar response, I added quotes to the value for it to work: 

`hole_size = '75'
chart.element.xpath('/c:chartSpace/c:chart/c:plotArea/c:doughnutChart/c:holeSize')[0].set('val', hole_size)`
