### ISSUE TITLE
AutoFormated text comin with placeholder instead of being properly encoded.

### ISSUE THREAD

**Issue by ATran31** [scanny/python-pptx#494]
When accessing the `.text` property to read text of a shape, characters that have been autoformatted is coming in as a question mark. For example, the apostrophe in `Anne's` is corrected to `Anne’s` by PowerPoint. The call to `.text` on the shape containing string with this word is is returning `Anne�s`. This is causing problems if you are using some text function or regex looking for a given term.

**Comment by scanny** [comment]
What value do you get for `print(type(shape.text)`?

**Comment by ATran31** [comment]
I am on Python 3.6.8 and `print(type(shape.text))` is  `<class 'str'>`.

**Comment by ATran31** [comment]
So I did some testing and it turns out to be an issue with the console display of my environment and nothing to do with python-pptx. I'm going to close the issue. Sorry.

**Comment by scanny** [comment]
Glad you got it working :)
