### ISSUE TITLE
Unable to copy RGBColor objects

### ISSUE THREAD

**Issue by qirh** [scanny/python-pptx#495]
I'm trying to copy/deepcopy an object that contains RGBColor objects. However RGBColor raises an exception when trying to copy since the class can't be pickled/unpickled
```
from copy import deepcopy
from pptx.dml.color import RGBColor
color = RGBColor(255, 255, 255)
deepcopy(color)
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/saleh/Git/app2/env/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/saleh/Git/app2/env/lib/python3.6/copy.py", line 274, in _reconstruct
    y = func(*args)
  File "/Users/saleh/Git/app2/env/lib/python3.6/copyreg.py", line 88, in __newobj__
    return cls.__new__(cls, *args)
TypeError: __new__() missing 2 required positional arguments: 'g' and 'b'

__new__() missing 2 required positional arguments: 'g' and 'b'
```

I solved it by defining a `__getnewargs__` function for the RGB class. If yall think this is a good addition to python-pptx, I can make a pr for it.
```
class RGBColor(RGBColor):
	# enables copy
	def __getnewargs__(self):
		return (*self, )
```

**Comment by scanny** [comment]
I can't say that "copyability" has been one of the target requirements so far. What do you find that useful for?

**Comment by qirh** [comment]
I needed to deepcopy a dictionary that contained RGBColor objects. My program gives the user the ability to set up general settings that can be applied to all slides. And then gives them another ability to further customize settings on slide by slide basis. Thus I deepcopy the general settings (which include RGBColor objects) so that if a slide has specific customization, it won't affect the general settings.

**Comment by scanny** [comment]
Maybe storing the colors in your settings object as strings like "1bf276" is a better idea, then you can convert those to `RGBColor` objects at application time with something like `RGBColor.from_string()`. That way your configuration object stays pure Python primitives and is guaranteed serializable, pickleable, copiable, etc.

**Comment by qirh** [comment]
Yeah I thought about, but wanted thought about abstracting out the color objects so the function that do the coloring don't have to convert from string. But I see your point. I'll close the issue :)
