### ISSUE TITLE
table row height cannot be evenly spaced

### ISSUE THREAD

**Issue by jackal1988** [scanny/python-pptx#498]
Hi @scanny~ 
As your docs said, I tried the following codes to add table to my silde.
```python
plchlder = slide.placeholders[1]
left, top, width, height = plchlder.left, plchlder.top, plchlder.width, plchlder.height
rows = 9
cols = 3
table = slide.shapes.add_table(rows, cols, left, top, width, height).table
```
I find that if setting `rows=9`, the table size will fit just fine.  

But if setting it, such as `rows=19`, the size of table will expand beyond the  `plchlder `.

I tried to set the `table.rows.height `, but it would not work.
```python
for i in range(rows):
    table.rows[i].height = Inches(0.5)
```
According to my observation,  it seems that the table row height has a minimun size that cannot be breached. Is that true?

Still appreciate your great work on `python-pptx` ~~~

**Comment by scanny** [comment]
Yes, that's pretty much how it works.

**Comment by jackal1988** [comment]
> Yes, that's pretty much how it works.

Thanks for the reply.
I figure it out that it is the font size  that invalidate the row height setting.
