### ISSUE TITLE
How to specify a .potx file when creating a new pptx ? 

### ISSUE THREAD

**Issue by JoshuaAdrianJones** [scanny/python-pptx#503]
Is there a way to specify an existing .potx file when creating a new pptx?

The way to do this is in VBA is something like this: 

```
    set filepath to ppt template
    Dim filepath As String
    templateFilePath = ThisWorkbook.Path & "\template.potx"

    Open PowerPoint and create new presentation
    Set PP = New PowerPoint.Application
    Set PPPres = PP.Presentations.Add
    PP.Visible = True
    PPPres.PageSetup.SlideSize = 2
    PPPres.ApplyTemplate (templateFilePath)

```

Below is the only reference I could find regarding .potx and it makes me think this is not a supported feature?

Presumably this python package is using the underlying VBA objects so this should be possible I think? 

My current use case is controlling powerpoint from Excel VBA and using excel as my data input to build a slide deck. I would like to port this action to python and read the info from a .xlsx or .csv file.

> We’ve called it a template, but in fact it’s just a regular PowerPoint file with all the slides >removed. Actual PowerPoint template files (.potx files) are something a bit different. More on >those later maybe, but you won’t need them to work with python-pptx.
[source](https://python-pptx.readthedocs.io/en/latest/user/presentations.html)

**Comment by JoshuaAdrianJones** [comment]
You can just save your .potx as a .pptx with no slides and it works fine from there.

` prs = Presentation('template.pptx')`

I am a dummy.

**Comment by scanny** [comment]
A `.potx` file is the same as a `.pptx` file excepting the MIME-type (Content-type) of the main presentation part in the package. As far as I can fathom, this is a signal to the PowerPoint app to treat that file a bit differently when it loads, like ignoring any slides it contains I think, but loading in the masters, theme, etc. and creating a new, blank slide. Also I suppose there's the bit about calling the new presentation `Presentation1.pptx` or something and not overwriting the template itself on save.

These are not terrifically important matters when using a library, and although this feature has been requested at least once, no one has ended up wanting it bad enough to sponsor it. All new development in `python-pptx` is essentially sponsored by project teams who just need that one or two new features to handle their use case. Individual users just bask in the glory of open-source and get what's grown to be quite a usable subset of all possible features for free. Individual code contributions turn out to be uneconomical, owing to the industrial-grade nature of the project and the testing and code-discipline rigors that imposes.

That's probably more than you wanted to know about the project internal process, but perhaps explains why some features like this seem to take a long time to appear :)

**Comment by Jesse-jApps** [comment]
As @scanny pointed out, `.potx` is basically the same as a `.pptx`, for those who want to open a `.potx` like `prs = Presentation('Presentation.potx')`, the MIME-type `CT.PML_TEMPLATE_MAIN` needs be added in `def _is_pptx_package(prs_part):` in `pptx/api.py`.

I suppose there is a reason why it is currently not included. If somebody could tell me why that is, I could write a small MR, to at least allow certain other formats to be opened (with warning).

**Comment by muendlein** [comment]
Is there any update on this issue in particular why .potx is not supported as a template?
