### ISSUE TITLE
Datalabels in COLUMN_STACKED chart

### ISSUE THREAD

**Issue by shrenik007** [scanny/python-pptx#505]
I want to append "%" to all of my labels. When I try ```data_labels.number_format="0.0%"```, "%" is added to the all the values but the values gets multiplied by 100. 
![Screenshot from 2019-05-27 15-48-26](https://user-images.githubusercontent.com/16061768/58413646-f5df1b80-8096-11e9-8a3d-cef588d7196d.png)

How can I solve this?

**Comment by scanny** [comment]
Please ask support questions on StackOverflow, using the "python-pptx" tag.
