### ISSUE TITLE
Conditional display of data labels

### ISSUE THREAD

**Issue by shrenik007** [scanny/python-pptx#506]
Can I iterate over Datalabels of each series in the chart?
For example I want to display on those datalabels whose value is above 2 and hide all others.

**Comment by scanny** [comment]
Access to an individual data label is provided by a Point object, like:

```python
point.data_label for point in series.points
```

**Comment by shrenik007** [comment]
But how can I access the original value while iterating over the point .data_label object

**Comment by scanny** [comment]
if you post this question on StackOverflow and show your best-guess-so-far-code to do it I'll have a look. Support questions belong over there. This issues list is for bug-reports (rare) and feature requests.
