### ISSUE TITLE
tox: add Python 3 support

### ISSUE THREAD

**Issue by scanny** [scanny/python-pptx#51]
Add support for Python 3.
- Change PIL dependency to Pillow
- Add Python 3.2, 3.3, and 3.4 environments to tox.ini.

**Comment by innovation-plantation** [comment]
I'm running **Windiws10** and I have **msys2** installed on my machine. 
Installation failed using both **pip** and **pip3** until I did: 
`pacman --sync libxml2`
Then **pip3** continued to fail, but **pip** installation from **CMD** completed without errors and that's what I'm using now. 
Here's the error that **pip3** is throwing:
```
  src/lxml/includes/etree_defs.h:14:10: fatal error: libxml/xmlversion.h: No such file or directory
     14 | #include "libxml/xmlversion.h"
```
It seems you need to to get **pip** to fetch the **xml** libraries...
