### ISSUE TITLE
How to set a table cell to a specific format?

### ISSUE THREAD

**Issue by gamename** [scanny/python-pptx#510]
Hi,

This is a stellar package and I'm using it extensively. The docs are great and I can figure out most everything I've needed.  

But there is one thing I can't figure out .  How do you set a table cell's format to "$#,##0.00" (i.e. US dollar)?  I scanned the documentation and couldn't find any examples.

**Comment by scanny** [comment]
Hi @gamename, support questions go best on StackOverflow, using the `python-pptx` tag which I monitor. That way more folks get to benefit.

Tables in PowerPoint are unlike those in Excel in that they can only contain string values. There's no concept of number there and so no concept of number-format. So if you want to format numbers, you need to do it yourself before writing the cell value.

There is number format in chart-data, which does end up in Excel, but I suppose that's not what you're talking about.
