### ISSUE TITLE
Shape deletion not possible due to parent NoneType

### ISSUE THREAD

**Issue by danplischke** [scanny/python-pptx#522]
Hi, 

I am currently facing an issue in which I am not able to delete a shape in the way suggested in issue #246 because  ._element.getparent() returns None in rare cases (it generally works). I am working off of an existing powerpoint, trying to remove shapes by name.

Is there an alternative method to delete a shape or do I happen to do something wrong? 

` def remove_shape(self, shape):
        shape._element.getparent().remove(shape._element)`

Thank you.

**Comment by scanny** [comment]
A `None` return value from `element.getparent()` indicates that element is the _root_ element, something that would never be true for a shape. So I would look elsewhere in your code for how the root element ends up there.
