### ISSUE TITLE
Changing chart data results in corrupt presentation

### ISSUE THREAD

**Issue by AgeOfMarcus** [scanny/python-pptx#526]
I am trying to change the data in a pie chart but it is causing the presentation to become corrupt. However, I do this for 2 pie charts, and for the first one it works fine.

Pie Charts (the smaller one is fine, that can be changed without issue):
![image](https://user-images.githubusercontent.com/27669378/60358928-90d45980-99a5-11e9-9241-c9b55fce0f54.png)

Code:
```chart = slide.shapes[-2].chart
chart_data = ChartData()

ctg = []

for i in mcdata:

    ctg.append(i+" - "+str(mcdata[i]))

chart_data.categories = tuple(ctg)

chart_data.add_series("",tuple([float(mcdata[i]) for i in mcdata]))

chart.replace_data(chart_data)

**Comment by scanny** [comment]
Please post support questions on StackOverflow using the "python-pptx" tag. Use literals for data instead of variables (like `mcdata`) because we have no way of knowing their contents. Also describe the corruption symptoms, perhaps as simple as "PowerPoint says "can't load, Repair yes/no".

**Comment by rizakha** [comment]
Hi, was this issue ever solved? I ran into the same problem, I checked the XML before and after .replace_data() and found that post .replace_data(), the <c:pieChart> tag is missing, hence why I am getting the repair attempt message...

**Comment by scanny** [comment]
I assume @AgeOfMarcus worked it out because he did not pursue it here. This behavior works for me, so try to produce a minimal reproducible example (https://stackoverflow.com/help/minimal-reproducible-example) and resubmit.
