### ISSUE TITLE
Cannot find objects inserted outside of preexisting placeholders

### ISSUE THREAD

**Issue by MCM-Math** [scanny/python-pptx#531]
When I insert an object into a PowerPoint, but not into a placeholder that is directly from the Slide Master, there doesn't seem to be a way to directly find it, such as in slide.shapes.placeholders.  Is there an equivalent for finding items added through code like shapes.addtable or shapes.add_shape?

**Comment by scanny** [comment]
Please ask support questions on StackOverflow (SO) using the `python-pptx` tag. This issues list is for feature requests and suspected bugs. Support effort is kept low by answering questions like this one on SO where folks can easily find the answer on search. Most questions there get an answer within 24 hours.

**Comment by MCM-Math** [comment]
I've tried to get questions answered on StackOverflow before; I just get downvoted until the thread is locked for "not being specific enough", not including sample code, or just to be rude (just read the threads, a lot of rude people there).  So I ask here, because if there isn't a way yet, I can request one.

**Comment by scanny** [comment]
I think you might need to work a little harder to figure out how to work within SO's guidelines; they're there to make things work for both sides, askers and responders. A question is hard to answer if it's too long, not specific, or doesn't contain code.

`shapes.add_shape()` returns a `Shape` object, which has a `shape_id` (guaranteed unique on that slide), a name (not guaranteed unique), and a position in the list of shapes for that slide:

```python
>>> shape = shapes.add_shape()
>>> shape
<pptx.shapes.Shape object at 0x...>
>>> shape.shape_id
8
>>> shape.name
Rectangle 9
>>> shapes.index(shape)
5
```

You can access it directly from `shapes` by index:

```python
>>> shapes[5] == shape
True
```

If you want to access it by name or shape_id you'll need to iterate through the shapes to find it:

```python
def get_shape_by_id(shapes, shape_id):
    """Return shape in `shapes` having `shape_id`, or None if not found."""
    for shape in shapes:
        if shape.shape_id == shape_id:
            return shape
    return None
```
