### ISSUE TITLE
How to insert image from URL?

### ISSUE THREAD

**Issue by codu** [scanny/python-pptx#535]
I am new to Github and this is my first question.

Is there any way to insert image into Presentation from file URL instead of filepath in my computer? If so how?
I am trying this and getting an error: [Errno 22] Invalid argument: 'https://img-trendyol.mncdn.com/mnresize/415/622/Assets/ProductImages/oa/66/6741004/1/4646032011667_1_org_zoom.jpg'

Thank you very much.

**Comment by scanny** [comment]
No. You'll need to arrange download of the image yourself. Commonly this would be done using a `BytesIO` object (in-memory file) such that you don't leave old files hanging around on the filesystem. Search on "python bytesio from url" to find out more about that.

**Comment by codu** [comment]
thank you scanny. python pptx is an amazing tool.
