### ISSUE TITLE
How can I determine which shapes are connected?

### ISSUE THREAD

**Issue by TylerReedMC** [scanny/python-pptx#542]
Is there a way to determine which two shapes a Connector actually connects?

**Comment by scanny** [comment]
Well, yes and no. The information is in the XML, but there's no API currently to access that directly.

A connector shape has (optional) `stCxn` and `endCxn` elements, mentioned in the schema here (using page search will pinpoint them faster than scanning probably): https://python-pptx.readthedocs.io/en/latest/dev/analysis/shp-connector.html#related-schema-definitions

Each of these take a shape-id and and index, which identify the connected shape and its connection-point index respectively.

This code might give some idea how those are used: https://github.com/scanny/python-pptx/blob/master/pptx/shapes/connector.py#L255

So all the information is in there, but you'll have to dig into the XML to get it. Something like this is a start:

```python
connector = ...
cxnSp = connector._element
print(cxnSp.xml)
```

**Comment by TylerReedMC** [comment]
Thanks for the info!
