### ISSUE TITLE
How to export the group shapes as an combined image by python-pptx?

### ISSUE THREAD

**Issue by flycs99** [scanny/python-pptx#545]
I created a group shape with a picture/image and a textbox with several lines. I want to export the image with the textbox. What should I do? I tried VBA. The pptx needs the macro stored in the pptx self to support the image export and it is not very convenient. I tried the win32com and I still do not know how to operate. I thought the clipboard method would be fine but I do not know how to copy the group shapes into the clipboard by python-pptx. Please help me to solve the problem.

**Comment by scanny** [comment]
What do you mean by "export" in this context?

**Comment by flycs99** [comment]
> What do you mean by "export" in this context?

Like the save as function in powerpoint when we right click on the group shape. By using save as,I will get an image containing the picture and the textbox from the group shape. For example, I insert a picture in one slides and then add a textbox with several lines on the picture. Then, I combine the picture and the textbox as one group. I right click on the group and select **_save as image or picture_** . And then I will get an image with the picture and the textbox. It is very convenient to modify pictures.  I tried the VBA and the codes are listed below. From the codes, I will get the combined pictures. The emf files are too large and need VBA to operate the slides. If the VBA codes could be independent from the PPTX files(not the pptx environment) as files like .txt or other file extensions, the solution is also acceptable.
Sub SaveShape1()
Dim Sld As Slide
Dim Shp As Shape
'On Error Resume Next
For Each Sld In ActivePresentation.Slides
For Each Shp In Sld.Shapes
arr = Shp.Name
sr = Dir("D:\exportPic\", vbDirectory)
If sr <> "" Then
Shp.Export pathName:="D:\exportPic\" & arr & ".emf", Filter:=ppShapeFormatEMF
Else
MkDir "D:\exportPic\"
Shp.Export pathName:="D:\exportPic\" & arr & ".emf", Filter:=ppShapeFormatEMF
End If
Next
Next
End Sub

**Comment by scanny** [comment]
`python-pptx` is not going to be able to help you with that. You're on the right track (if there is one) in trying the VBA route. This functionality depends on the rendering engine built into the PowerPoint client.

**Comment by flycs99** [comment]
> `python-pptx` is not going to be able to help you with that. You're on the right track (if there is one) in trying the VBA route. This functionality depends on the rendering engine built into the PowerPoint client.

Thank you for your help. I will try the PIL to draw what I want on the pictures. ^_^
