### ISSUE TITLE
How does this object GroupShapes get? Thanks!

### ISSUE THREAD

**Issue by yuhal** [scanny/python-pptx#552]
Hi Steve, I tried to get GroupShapes, but couldn't. 
Hope you can help solve the problem, thank you～

Access the slides object using the slides property of Presentation
slides = prs.slides

Return the fourth object in the index through slides
slide = slides[4]

Returns an instance of a slide show that contains a sequence of shape objects that appear on this slide.
shapes = slide.shapes

print shapes.groupshape

Return
AttributeError: 'SlideShapes' object has no attribute 'groupshape'

**Comment by scanny** [comment]
What are you trying to accomplish? There is no `Slide.groupshape` attribute, which you can tell from the API docs here: https://python-pptx.readthedocs.io/en/latest/api/shapes.html

**Comment by scanny** [comment]
If what you're trying to do is identify the group-shapes on a slide, something like this should do the trick:

```python
from pptx.enum.shapes import MSO_SHAPE_TYPE

def group_shapes(slide):
    return [
        shape
        for shape in slide.shapes
        if shape.shape_type == MSO_SHAPE_TYPE.GROUP_SHAPE
    ]
```
