### ISSUE TITLE
Feature suggestion: insert Videos

### ISSUE THREAD

**Issue by mrscarvalho** [scanny/python-pptx#562]
Hi, congrats for the great job!!

For business presentations, a very common task is to include videos embedded in the Powerpoint presentation. Could this be considered in the near future? 

(especially MP4 videos, most common these days, and embedded to allow single file presentation)

Tks & Rgds!

**Comment by scanny** [comment]
`python-pptx` supports videos.  
https://python-pptx.readthedocs.io/en/latest/api/shapes.html#pptx.shapes.shapetree.SlideShapes.add_movie
