### ISSUE TITLE
unable extract slide title containing equation

### ISSUE THREAD

**Issue by Carusu** [scanny/python-pptx#569]
I was trying to extract from a pptx file the slide titles. The method proposed [here ](https://stackoverflow.com/questions/40818692/get-the-title-of-slides-of-pptx-file-using-python)works fine if the title contains only text. However, as soon as the title contains an equation (i.e. generated with the office equation tool), the described method does not work, and instead it gives the following error (let us assume that the slide number is the 26th):

from pptx import Presentation
prs = Presentation('My_Presentation.pptx')
print(prs.slides[26].shapes.text)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: 'SlideShapes' object has no attribute 'text'

(on any other "normal title" slide this works just fine and the result is what I would expect)

Any work around for me would do, even completely ignore the equation part within the title as I have quite a few presentations to parse in this way and I cannot really go manual on this.

I am using Python 3.7

**Comment by scanny** [comment]
Please ask support questions on StackOverflow using the "python-pptx" tag.
