### ISSUE TITLE
I want to split each slide in a presentation.

### ISSUE THREAD

**Issue by bryce0516** [scanny/python-pptx#572]
how to do it?? plz explain for me. i just want to split each slide to each presentation.

**Comment by cxin-william** [comment]
你可以保存多个文件，多个prs，根据你想要的不同幻灯片

**Comment by MartinPacker** [comment]
What do you mean by splitting? How would you control where the split happened? For example "split into a new slide after the 10th bullet, copying the slide's title into the new slide and adding '1/2', 2/2' to the titles".

(No, I don't need this but I think the first step is to refine the problem. And, yes, I know this is an old issue. I don't know if the previous comment is SPAM or not.)
