### ISSUE TITLE
Text Box Columns

### ISSUE THREAD

**Issue by Fredericco72** [scanny/python-pptx#580]
I've been trying to implement splitting a text box into 2 or 3 columns, I've found the tag that sets this value, `numCol=2`, but I'm unsure of the correct way to edit the value?

```
for c in shape.text_frame._element.getchildren():
    if c.tag.split('}')[-1] == 'bodyPr':
        c.set('numCol','2')
```

The above logic works correctly but I feel it's not exact, is there a way that I can search in `shape.text_frame._element` for the element with tag `bodyPr`?

Thanks,

Fred

**Comment by scanny** [comment]
Post a snippet of the XML of a whole text-frame element (without unnecessary details) that includes both the full text-frame element and the bodyPr element and I can tell you an XPath expression that can find it for you (or find out it's not there). Maybe start with `print(shape.text_frame._element.xml)` and pare out the unimportant bits if they're too long.

**Comment by Fredericco72** [comment]
Hi scanny thanks for getting back to me, here is the XML for a shape's text_frame:
```
<p:txBody xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <a:bodyPr rtlCol="0" anchor="ctr"/>
  <a:lstStyle/>
  <a:p>
    <a:pPr algn="ctr"/>
  </a:p>
</p:txBody>
```
the `numCol` tag would live in the second line , i would like to change it to this: `<a:bodyPr rtlCol="0" anchor="ctr" numCol="2"/>`

Thank you for your help!

**Comment by scanny** [comment]
Ok, so `shape.text_frame._element` gives you the `<p:txBody>` element (call that `txBody`) and we can go from there:

```python
txBody = shape.text_frame._element
bodyPrs = txBody.xpath("./a:bodyPr")  # ---xpath always returns a list---
if not bodyPrs:
    # ---you'll need to add one, but we know there's one there so...---
else:
    bodyPr = bodyPrs[0]
bodyPr.set("numCol", "2")  # ---second param is always a str---
```

**Comment by Fredericco72** [comment]
Sorry for the very delayed response! This works perfectly, I'm able to split the text in a text_frame.
