### ISSUE TITLE
Enable Presenter View?

### ISSUE THREAD

**Issue by daniel-tran** [scanny/python-pptx#585]
**How feasible would it be to allow the "Use Presenter View" option to be toggled in python-pptx?** 

Under the Slide Show tab, there's a checkbox to "Use Presenter View" which is only available when the PowerPoint is being used in an environment utilizing multiple displays.

I've searched for this option in the python-pptx documentation, as well as the currently open issues and pull requests, but I couldn't really find anything that indicates that this can be configured.
Perhaps this has been considered or discussed in the past with the decision not to allow for this particular configuration, so any references to such dialogue would be helpful.

**Comment by scanny** [comment]
The first question would be whether that option is transitory or persistent. Like if you set it, save, close, and reload, does it come back? or do you have to select it again.

If it's persistent and it is presentation-specific (not global to a particular computer), it almost certainly is saved in the PPTX file. If not, it's probably stored in application config somewhere or only remembered for the duration of a session.

If you can determine it is persistent, then the next step would be to look for where it is stored in the package (i.e. in which "part" (package file)). My bet would be in app.xml or maybe settings.xml.

**Comment by daniel-tran** [comment]
It seems that Presenter View is a global setting for all PowerPoint files on a particular machine. Which is to say, toggling the option in one presentation effectively carries over onto any subsequently opened presentations, even after a system reboot.

Oddly enough, enabling Presenter View is somewhat dependent on the machine used to run PowerPoint. I've tried toggling this option on a Windows 7 laptop but it fails with a warning about requiring multiple monitors, while enabling Presenter View on a Windows 10 desktop computer (with and without a secondary display) is OK.

Given this as a basic context around Presenter View, I would conclude that Presenter View is _probably_ outside the scope of python-pptx.

**Comment by scanny** [comment]
sounds right to me @daniel-tran
