### ISSUE TITLE
Center align text in a table cell

### ISSUE THREAD

**Issue by mberk06** [scanny/python-pptx#587]
Simple question. How do you center-align text in a table cells. I am using the following code:
             
```
p = cell.text_frame.paragraphs[0] # get paragraph to format text

p.font.size = Pt(10) # format text size of cell

p.alignmnet = PP_ALIGN.CENTER # center align
```

Note that changing the font size works, so it's not a problem with referencing the paragraph. I have also tried setting the alignment to `None` (hoping it would inherit the center align from the PP table) and this did not work.

**Comment by scanny** [comment]
Looks like you misspelled alignment. Please use StackOverflow with the "python-pptx" tag for support questions :)
