### ISSUE TITLE
How to set properties for a textframe

### ISSUE THREAD

**Issue by tooh** [scanny/python-pptx#59]
Sorry to bother you with such a basic question. My programming skills are a bit rusty. :)

I have following code :

```
# Add textframe         
            left = Inches(1.0)
            top = Inches(4.0)
            width = Inches(6.0)
            height = Inches(6.0)

            txBox = slide.shapes.add_textbox(left, top, width, height)
            tf = txBox.textframe

            tf.text = data['Progress']
```

How can I make the textframe to autowrap the text and  give the textframe a black border ?

**Comment by diego-EA** [comment]
Hi all,

I also want to give a textframe a border, but I can't and I will appreciate some advice. I'm using the most recent version python-pptx (Version 0.6.19) and Python 3.8.5 and the solutions mentioned above (https://github.com/scanny/python-pptx/issues/59#issuecomment-29568123) did not work for me. As I can't reach _SubElement_ anymore I tried to adapt the lines above with _OxmlElement_ 

        from pptx.oxml.xmlchemy import OxmlElement

        def _set_rgb_color(pr_elm, rgb):
            try:
                solidFill = pr_elm.solidFill
                solidFill.clear()
            except AttributeError:
                solidFill = OxmlElement(pr_elm, 'a:solidFill')
            srgbClr = OxmlElement(solidFill, 'a:srgbClr')
            srgbClr.set('val', rgb)

        def _set_shape_line_rgb_color(sp, rgb):
            pr_elm = OxmlElement(sp._element.spPr, 'a:ln')
            _set_rgb_color(pr_elm, rgb)

but I get this error and I don't know how to solve that:

    File "main.py", line 14, in <module>
      tool.fill_report()
    File "C:\hilti\hilti_icos\project\tool.py", line 60, in fill_report
      _set_shape_line_rgb_color(tf, 'DD4A0B')
    File "C:\hilti\hilti_icos\project\tool.py", line 47, in _set_shape_line_rgb_color
      pr_elm = OxmlElement(sp._element.spPr, 'a:ln')
    AttributeError: 'CT_TextBody' object has no attribute 'spPr'


Is there already another way to give the textframe a border? If not, can anyone help me to adapt the above-mentioned solution to my environment?

Many thanks in advance!

**Comment by scanny** [comment]
This issue is closed. Please post support questions on StackOverflow using the `python-pptx` tag and we'll see it.
