### ISSUE TITLE
python-pptx pptx file split can do it? I hope you help answer，thanks！

### ISSUE THREAD

**Issue by yuhal** [scanny/python-pptx#610]
Hi steve,
I tried using python-pptx to split a single page ppt, but couldn't find a way.
Can it split a single page ppt?
Hope you can help answer, thank you ~

**Comment by scanny** [comment]
Please post support questions on StackOverflow using the `python-pptx` tag. You'll need to describe what you're trying to accomplish more carefully. In particular, what is a "single-page ppt"? Do you mean a PowerPoint presentation with a single slide? What would splitting mean?
