### ISSUE TITLE
Preserve styling of slide notes?

### ISSUE THREAD

**Issue by jk31** [scanny/python-pptx#616]
Is there a way to preserve the styling of notes in `slide.notes_slide.notes_placeholder.text`?

**Comment by scanny** [comment]
Either yes or no, depending on what you are trying to do. What are you trying to do?

**Comment by jk31** [comment]
Thanks for the quick answer.

By styling I mean **bold** or _italic_.

See https://github.com/jk31/private-powerpoint-notes

**Comment by willkim1** [comment]
If you are trying to read bold or italic, just read the text frame properties, then set them.

https://python-pptx.readthedocs.io/en/latest/api/text.html#font-objects

e.g. 
`readBoldStyle = slide.notes_slide.notes_placeholder.text_frame.paragraphs[0].font.bold`
`readItalicStyle = slide.notes_slide.notes_placeholder.text_frame.paragraphs[0].font.italic`
