### ISSUE TITLE
Secondary Axis missing in Charts

### ISSUE THREAD

**Issue by vijetaiot** [scanny/python-pptx#618]
For column or bar charts, often we end up having **secondary axis** to depict additional features. I tried various ways, but couldn't figure out a way to add Secondary-axis to either a column or bar charts. Is there any possible way or work-around to add this. 
any help would be highly appreciated!

**Comment by Mynkj1996** [comment]
I also want to know how to add a secondary axis in python-pptx. If it's not yet implemented then please let us know the other way or can share his/her code .help would be highly appreciated!

@scanny please help us

**Comment by willkim1** [comment]
This is not implemented yet, but you can add it to build\lib\pptx\chart\axis.py

I suggest just copying the a chart that already has a secondary axis and replacing the values.

**Comment by scanny** [comment]
Duplicate of #141.
