### ISSUE TITLE
pptx.exc.PackageNotFoundError: Package not found at path

### ISSUE THREAD

**Issue by ghost** [scanny/python-pptx#625]
Hello,

I am trying to use the existing theme of presentation, add slide in that presentation by code and save it as new presentation.
prs = Presentation(final_path) -- i gave the absolute path and also tried to give the file as it is since the file is in the same directory. Tested all methods, locating file is not an issue, but I get package not found error. Please suggest
raise PackageNotFoundError("Package not found at '%s'" % pkg_file)
pptx.exc.PackageNotFoundError: Package not found at

Should I add anything in site-packages? what change should i do for the above one to run?

**Comment by willkim1** [comment]
You need to provide working code for someone to help. I suspect it is an error in your add/copy code.

**Comment by sevire** [comment]
Hi - just a hunch.  I had exactly the same problem.  Two things:
- The word package isn't referring to a Python package.  There is a piece of code which deals with different types of object, and if the object is a string it will treat it as a pathname (which is my case and I think yours).  The code refers to the object as a package as a general term for object which may be one of a number of types.
- In my case I was running from an IDE and my pathname has a '~' in it, which refers to the user's home directory.  I suspect that maybe the IDE runs in a different user and so the home directory was different and so was failing to find the file for that reason.  When I replaced with a full pathname it worked.

Just thought I'd share - I realise this use case may be specific to me :-)

**Comment by scanny** [comment]
Looks like the OP was deleted or closed their account, but just for the record then:

.pptx files are zip files organized according to the Open Packaging Convention (OPC). In that parlance, a .pptx file is a "package". So this error in this context is basically saying "Can't find the .pptx file you mentioned."

To be more precise though, if the file is found and it turns out not to be a zip archive, you get the same error.

**Comment by scign** [comment]
I got this error when I tried to open it in python while the file was still open in PowerPoint. Just sharing in case anyone else gets the same issue - check to see if the file is open elsewhere.

**Comment by russau** [comment]
For anyone getting this error.  I got this error because I had the pptx files open on a mac, and Power Point creates files named like `~$presentation.pptx`.  You'll get the `PackageNotFoundError` error if you attempt to create a `Presentation` object from one of these files.
