### ISSUE TITLE
has text in group shape, but not able to extract.

### ISSUE THREAD

**Issue by khush12** [scanny/python-pptx#639]
Hi, I am facing an issue.
Inside ppt file text is present in GROUP shape_type , but while printing shape.has_text_Frame it is printing FALSE.
So how to extract the text?
while printing shape.element for the same group i am getting result like this:
<Element {http://schemas.openxmlformats.org/presentationml/2006/main}grpSp at 0x7f2e601c2f5

Can anyone help me with this?

**Comment by scanny** [comment]
Please ask support questions on StackOverflow using the "python-pptx" tag.

A group shape has no text of its own. Use `group_shape.shapes` to iterate over the shapes inside the group shape. Note that a group shape can contain a group-shape as one or more of it's "sub" shapes.
