### ISSUE TITLE
Possibility to set DateAxis properties related to time units

### ISSUE THREAD

**Issue by shimikano** [scanny/python-pptx#653]
Thank you for this library.

As far as I could see, there is no API to set the DateAxis properties `baseTimeUnit`, `majorUnit`, `majorTimeUnit`, `minorUnit` and `minorTimeUnit`.

Is that right or am I overlooking something?

**Comment by scanny** [comment]
Yes, it looks like those haven't been implemented yet. If you can post the before and after XML for setting those I can probably help you with a few lines of code to accomplish those settings using `lxml` calls.

You can get the axis XML with:

```python
print(axis.xml)
```

If you do a before version right after creating the chart with `python-pptx` and an after version after making those property adjustments "by hand" with PowerPoint, that should reveal just what XML adjustments need to be made.

**Comment by shimikano** [comment]
Thanks for getting back!

As far as I could see, [this line](https://github.com/scanny/python-pptx/blob/b31cf20fe31ff0f3fe0c919111f3562bb58f8b1e/pptx/chart/xmlwriter.py#L401) (and 2 corresponding ones for other chart types) hard-codes the `baseTimeUnit` to `days`.

Here's the DateAxis XML generated by `python-pptx`:

```xml
<c:dateAx>
    <c:axId val="2118791784"/>
    <c:scaling>
        <c:orientation val="minMax"/>
    </c:scaling>
    <c:delete val="0"/>
    <c:axPos val="b"/>
    <c:numFmt formatCode="yyyy\-mm\-dd" sourceLinked="1"/>
    <c:majorTickMark val="out"/>
    <c:minorTickMark val="none"/>
    <c:tickLblPos val="nextTo"/>
    <c:crossAx val="2140495176"/>
    <c:crosses val="autoZero"/>
    <c:auto val="1"/>
    <c:lblOffset val="100"/>
    <c:baseTimeUnit val="days"/>
</c:dateAx>
```

An example where `baseTimeUnit`, 'majorUnit` and `majorTimeUnit` are set reads as follows:
```xml
<c:dateAx>
    <c:axId val="2118791784"/>
    <c:scaling>
        <c:orientation val="minMax"/>
    </c:scaling>
    <c:delete val="0"/>
    <c:axPos val="b"/>
    <c:numFmt formatCode="yyyy\-mm\-dd" sourceLinked="1"/>
    <c:majorTickMark val="out"/>
    <c:minorTickMark val="none"/>
    <c:tickLblPos val="nextTo"/>
    <c:crossAx val="2140495176"/>
    <c:crosses val="autoZero"/>
    <c:auto val="1"/>
    <c:lblOffset val="100"/>
    <c:baseTimeUnit val="months"/>
    <c:majorUnit val="12"/>
    <c:majorTimeUnit val="months"/>
</c:dateAx>
```

**Comment by scanny** [comment]
You can get a reference to the `<c:dateAx>` element with:

```python
dateAx = axis._element
```

Then you should be able to access the `<c:baseTimeUnit>` element like this:

```python
baseTimeUnits = dataAx.xpath("./c:baseTimeUnit")
baseTimeUnit = baseTimeUnits[0] if baseTimeUnits else None
```

and the set the value with:

```python
baseTimeUnit["val"] = "months"
```

Each element here is an `lxml.etree._Element` object and has all the methods of that object. This is why it can be manipulated like this which is pretty much exactly how `python-pptx` itself does that.

**Comment by shimikano** [comment]
Thank you for your help!

I was able to modify the `baseTimeUnit`'s `val` attribute along your lines like this:

```python
axis = category_axis._element
baseTimeUnits = axis.xpath("./c:baseTimeUnit")
baseTimeUnit = baseTimeUnits[0]
baseTimeUnit.attrib["val"] = "months"
```
Would you also let me know how I can easily append a new element, such as `c:majorUnit`?

I tried like this, but got an `Invalid tag name 'c:majorUnit'` error due to the namespaced element name:
```
majorUnit = etree.SubElement(axis, 'c:majorUnit')
```
I guess this is a basic question, but I'd be glad for a few pointers.

**Comment by scanny** [comment]
I think what you're looking for is the `qn()` function, here's an example of it being used: https://github.com/python-openxml/python-docx/issues/55#issuecomment-43914055. `qn()` produces a so-called "Clark" name from a namespace-prefixed tag name.

**Comment by shimikano** [comment]
Thank you very much @scanny. With your help, I managed to create the namespaced element.

For the record, this is what I ended up with:
```python
from pptx.oxml.ns import qn
from pptx.oxml.xmlchemy import etree

axis = category_axis._element
majorTimeUnit = etree.SubElement(axis, qn("c:majorTimeUnit"))
majorTimeUnit.attrib["val"] = "months"
```

Your help is much appreciated. This issue my be closed.

**Comment by scanny** [comment]
Glad you got it working @shimikano :)
