### ISSUE TITLE
colour mapping defined in SlideMaster

### ISSUE THREAD

**Issue by EliasDeVos** [scanny/python-pptx#660]
Hi,

I have a slide with a slide master that has the following tag
`<p:clrMap bg1="lt1" tx1="dk1" bg2="lt2" tx2="dk2" accent1="accent1" accent2="accent2" accent3="accent3"
			  accent4="accent4" accent5="accent5" accent6="accent6" hlink="hlink" folHlink="folHlink"/>`
This maps some theme names to other theme names.
I can fetch the colour from theme, i know lt1 is in my case FFFFF.
But in my ppt slides they use bgt1 all the time which is not present in theme.
Is it possible with this bundle to reach the mapping that bgt1 = lt1 ?
Thanks in advance

**Comment by scanny** [comment]
what is `bgt1`? I don't understand your question.

**Comment by EliasDeVos** [comment]
it's a theme color, i fixed it right now by re-parsing my master_slide xml and fetching it.
I think i have a very edge case power point.
I will close this issue
