### ISSUE TITLE
How to change the color of the gridline in a chart

### ISSUE THREAD

**Issue by wusujuan9999** [scanny/python-pptx#672]
Dear all

does anyone know  how to change the gridline color in  a chart?
I don't find any command in the python-pptx
the commands I Used like below:
graphic_frame = chart.insert_chart(XL_CHART_TYPE.COLUMN_CLUSTERED, chart_data)
graphic_frame.chart.value_axis.has_major_gridlines = True

the color of the major gridlines in output slides is black , I want to change to be gery
Looking forward to your answer!

Thanks!

best
wu

**Comment by scanny** [comment]
```python
chart.value_axis.major_gridlines.format.line.color.rgb = RGBColor(0xCC, 0xCC, 0xCC)
```
