### ISSUE TITLE
How to get the text attribute when reading text from ppt template

### ISSUE THREAD

**Issue by cxin-william** [scanny/python-pptx#683]

**Comment by scanny** [comment]
Please ask support questions on StackOverflow using the "python-docx" tag. This issues list is for suspected bugs and new feature requests. You're going to need to provide more information there about what you're trying to accomplish and what you've tried so far.

**Comment by cxin-william** [comment]
sorry scanny，Thank you very much for your reply
When I do a function, I encounter a problem. First of all, I scan the text in PPT, and then replace some text. In this process, I find that the font has become the default font. How can I keep the font style unchanged
`def fill_text(prs, text_format, data):
  for i in text_format:
    idx, sh_idx, text = i['sl_idx'], i['sh_idx'], i['text']
    p = i['paragraph']
    pgh = prs.slides[idx].shapes[sh_idx].text_frame.paragraphs[p]
    for id, elm in enumerate(pgh._element.content_children):
      if id == 0:
        continue
      pgh._element.remove(elm)
    prs.slides[idx].shapes[sh_idx].text_frame.paragraphs[p].runs[
      0].text = SFormatter().vformat(text, [], data)
  return prs`
