### ISSUE TITLE
feature: Auto-fit text to shape

### ISSUE THREAD

**Issue by scanny** [scanny/python-pptx#69]
Able to set auto-fit behavior of a text frame:
- no auto-size
- resize shape to fit text
- resize text to fit shape

**Comment by jadimabuyu** [comment]
Hi, I want to give this a try. Can you teach me how to do it?

Thank you.

**Comment by soumyand** [comment]
python-pptx while inserting text in predefined pptx template text placeholder i am using below options to fit text in text placeholder.
TP.auto_size = MSO_AUTO_SIZE.TEXT_TO_FIT_SHAPE
TP.word_wrap = True
TP.fit_text()

none of options fit text properly inside placeholder. text is overflowing out of placeholder. when opened ppt manually we have to set autofit text.

**Comment by wenchaoliu-93** [comment]
> * resize shape to fit text

Text overflow has been an issue for me. The resize-text-to-fit-shape functionality doesn't seem to function well. Yes, it's a simply fix by modifying the placeholders, but there's not an easy way to do that for all slides. What I have been doing is selecting and dragging all elements to trivially change their position.
