### ISSUE TITLE
PowerPoint found a problem with content PowerPoint can attempt to repair the presentation.

### ISSUE THREAD

**Issue by ngandolfoh** [scanny/python-pptx#692]
Hi All,

First of all I'd like to say that this library is awesome, truly amazing.

I'm running with an issue - PowerPoint found a problem with content.

What I've been doing is grab a pptx template and format it via {} with all the data the template needs.

The shapes I format are:
- Text boxes
- Tables
- Pie Charts

The code runs fine but when I open the file I got that error.
```
PowerPoint found a problem with content.
PowerPoint can attempt to repair the presentation.
If you trust the source of this presentation, click Repair.
```

Can you help me?
<img width="275" alt="Screen Shot 2021-03-15 at 16 29 07" src="https://user-images.githubusercontent.com/56806443/111210083-91fb4f00-85ab-11eb-823e-5b56dbfa46a9.png">

**Comment by scanny** [comment]
Probably something went wrong with your templating. Maybe try it without the template-filling and see if it works.

`python-pptx` doesn't have any templating features as far as I know, so any problems with that are unlikely to be a mis-behavior of `python-pptx` (which is rare anyway). Since you haven't mentioned anything about the templating code we have no way of saying much more.

**Comment by MartinPacker** [comment]
I would also look for the minimum example that shows the problem.

**Comment by ngandolfoh** [comment]
I founded what was causing the error, I'm replacing the data from a pie chart and that generates that need of repair.

I'm creating pie charts from scratch, but now i'm running into a new problem. How can I access X, Y, CX, CY from an existing chart? Just to create the new ones in the exact position.

**Comment by ngandolfoh** [comment]
This is the code:

`def add_pie_chart(self, slide_index, series_data):
        slide = self.get_slide_by_index(slide_index)
        x, y, cx, cy = Inches(2), Inches(3.25), Inches(3), Inches(2.5)
        chart_data = ChartData()
        chart_data.categories = ['Good', 'Average', 'Poor']
        chart_data.add_series('Series 1', series_data)

        chart = slide.shapes.add_chart(
            XL_CHART_TYPE.PIE, x, y, cx, cy, chart_data).chart

        points = chart.plots[0].series[0].points

        for i in range(len(points)):
            colors = {'good': {'r': 76, 'g': 172, 'b': 162}, 'average': {
                'r': 245, 'g': 184, 'b': 56}, 'poor': {'r': 231, 'g': 91, 'b': 91}}
            if i == 0:
                color = colors['good']
            elif i == 1:
                color = colors['average']
            elif i == 2:
                color = colors['poor']

            fill = points[i].format.fill
            fill.solid()
            fill.fore_color.rgb = RGBColor(color['r'], color['g'], color['b'])
`

I implement it this way:

`def populate_cwv_slides(self):
        metrics = ['a', 'b', 'c']
        for metric in metrics:
            self.name_cwv_metric(metric)
            self.populate_cwv_slide(metric)
            self.populate_cwv_ranking_table(metric)

        self.add_pie_chart(9, self.data['dc']['a'])
        self.add_pie_chart(10, self.data['dc']['b'])
        self.add_pie_chart(11, self.data['dc']['c'])
        return
`

**Comment by scanny** [comment]
Leave out the part starting with `points = chart.plots[0].series[0].points` and see if that works. I suspect the way you're using `points` on a pie chart is causing a problem and this test would narrow it down.
