### ISSUE TITLE
MIME Type of saved presentation

### ISSUE THREAD

**Issue by muhammad-omer-dev** [scanny/python-pptx#700]
The mime type when we save a presentation is application/octet-stream is there any way we can change it to 
application/vnd.openxmlformats-officedocument.presentationml.presentation

**Comment by scanny** [comment]
MIME-type is not an attribute of a PPTX file. Look to the mechanism that is _identifying the filetype_ for this problem. You might need to specify the MIME-type in a call to your application server to serve a file download, for example, to get it to use the right one.
