### ISSUE TITLE
Can not read shapes having a formula 

### ISSUE THREAD

**Issue by seyong-um** [scanny/python-pptx#704]
If, there is a formula inside a shape such as a textbox, or a table - one cell of it
then the entire Shape is not read by python-pptx library.

<img width="335" alt="스크린샷 2021-04-29 오후 1 10 18" src="https://user-images.githubusercontent.com/10647558/116501628-40edb300-a8ec-11eb-879f-1ad03df4daa2.png">

        prs = Presentation('file.pptx')

            for slide in prs.slides:
                for shape in slide.shapes:
                     print(shape.text)
                     # Any of shape including a formula doesnt meet here

The code prints:

    I am a normal sentence.

only.

**Comment by scanny** [comment]
Please post support questions on StackOverflow with the `python-pptx` tag: https://stackoverflow.com/questions/tagged/python-pptx.
