### ISSUE TITLE
Dropping/keeping specific gridlines

### ISSUE THREAD

**Issue by AumkarG** [scanny/python-pptx#711]
Is there any way to drop (or keep) only certain gridlines. We can drop all major or minor gridlines of an axis 
Eg. for category axis :     category_axis.has_major_gridlines = False

Can I individually access gridlines like we can access points and drop/manipulate them?

**Comment by scanny** [comment]
Can you do that with the PowerPoint UI? If you can't then is very unlikely it can be done at all. My bet is that PowerPoint does not support this, but seeing with the UI can do is the place to start.

**Comment by AumkarG** [comment]
Checked PowerPoint UI, it doesn't allow editing of individual grid lines 👍🏻
