### ISSUE TITLE
Feature Request: Running PowerPoint macros via python-pptx

### ISSUE THREAD

**Issue by RyotaUshio** [scanny/python-pptx#714]
I have a .pptm file which has some macros defined in it.
Is there a way to run them via python-pptx?
If not, I would really appreciate it if that functionality would be implemented in the near future.

**Comment by MartinPacker** [comment]
You really have to understand what python-pptx actually is: It creates a pptx file and **doesn't** open it in Powerpoint.

It would be reasonable to want python-pptx to embed macros in the file; It wouldn't be reasonable to expect it to run them. There may well be other ways of automatically running a macro in your environment.

(I say the above as a highly experienced user of python-pptx, not as the author.)

**Comment by RyotaUshio** [comment]
@MartinPacker Thank you for giving me the essential information. I am very new to python-pptx so I've not realized that.
