### ISSUE TITLE
Fonts get reset to Arial on Google Drive/Slides

### ISSUE THREAD

**Issue by ryanjcarroll** [scanny/python-pptx#721]
When I use the python-pptx package to export a Presentation within a Google Colab/Drive environment, many of the fonts get reset to a default font (Arial).

I'm running this simple script to load in a .pptx file as a Presentation object and then export it to a .pptx file. The expected outcome is that it will essentially copy the slide deck and rename it. However, it is not retaining all of my font formattting, as can be seen in the attached image.

```
%pip install python-pptx
from pptx import Presentation

template = Presentation('/path_to_folder/Input.pptx')
template.save('/path_to_folder/Output.pptx')
```

This has been working as intended as recently as two weeks ago, so I'm not sure if it is the result of an update to python-pptx or Google Slides.

When I run the same script (minus the %pip install line) on my local machine, the output is generated as expected, with my original fonts/formatting intact.

[Image of font conversion issue](https://i.stack.imgur.com/q1ZPu.png)

**Comment by scanny** [comment]
@ryanjcarroll I see this question over on StackOverflow which is the right place for it. Addressing there, closing this one. In general, support questions should go on StackOverflow. If they escalate to a suspected bug (rare) they come over here.

**Comment by ryanjcarroll** [comment]
My bad - thanks!

Ryan
