### ISSUE TITLE
Support for font change using font files in python pptx

### ISSUE THREAD

**Issue by deveshl04** [scanny/python-pptx#722]
Is there any way of using the font files(ttf, otf or woff2) for changing the font of the pptx in python pptx?

**Comment by scanny** [comment]
A couple things:

1. You'll need to say more. Describe your situation, what you're trying to accomplish, what the challenges are, and what you've tried so far, including the minimal code.
2. Bring up this topic on StackOverflow using the `python-pptx` tag. This issues list is only for suspected bugs. Support questions go over there.

**Comment by liyao1520** [comment]
Reference the [pptx-embed-fonts](https://github.com/liyao1520/pptx-embed-fonts) library and implement support for embedding custom fonts in PPT, including **TTF**, **EOT**, and **WOFF** formats.
