### ISSUE TITLE
The default template is 9 years old

### ISSUE THREAD

**Issue by ialhashim** [scanny/python-pptx#723]
I suggest an update to the default slide template, maybe even better keeping the old one and adding a parameter to use the latest PowerPoint default template with wide screen sizes.

**Comment by MartinPacker** [comment]
I would suggest a few sample templates instead. Otherwise people will get unexpected changes.

(In md2pptx I use the default template - unless the user specifies another with a metadata item in the Markdown file - and wouldn't want that default behaviour to change.)

**Comment by barronh** [comment]
+1

It would be great to include a 16x9. I am constantly carrying around a template from project to project because modifying is so much work.

**Comment by barronh** [comment]
@ialhashim - I've made a pull request following your suggestion. I haven't added to this repo before. Hopefully, it will get picked up.

**Comment by ialhashim** [comment]
Thanks, hopefully it gets pulled.
