### ISSUE TITLE
kind of project status and half question

### ISSUE THREAD

**Issue by NathanTech7713** [scanny/python-pptx#725]
Hi,

First off, this is an amazing wrapper and exactly what I was looking for for a project.
Second, and to my issue. In the docs I was reading it states that slide reordering and slide deletion is on the books, but yet to be implemented.

Is this still correct?
Should I update to the github version v.s. the one through pip?

Secondly, and this may be a newbie thing but, if you wanted to delete a slide, why could you not just do:
prs.slides.remove(unwanted_slide)
similarly to reorder slides, would it break horribly if you just did:
slide1=prs.slides[0]
slide2=prs.slides[1]
slide3=prs.slides[2]
prs.slides=[slide3, slide2, slide1]

I've only really seriously started cranking into the project a day or two ago, so sorry if these are obvious questions.
Nathan

**Comment by scanny** [comment]
Hi Nathan. Support questions are best asked on StackOverflow using the `python-pptx` tag. Answers there are more likely to appear in search results and benefit more folks.

Slide reordering and slide deletion do not yet have API support.

Regarding the "would `prs.slides.remove(unwanted_slide)` work" question, no. That won't work. The API makes these look like lists or whatever, but underneath they are substantially more sophisticated. Any of the code statements you propose would not work. Some would raise an exception, others might just ignore you, but none of them would work. You can only use the API in the ways it is documented here: https://python-pptx.readthedocs.io/en/latest/index.html#api-documentation
