### ISSUE TITLE
feature: DataLabels to show percentage (%) symbol for data points properties

### ISSUE THREAD

**Issue by soumyand** [scanny/python-pptx#728]
while generating column stacked 100% chart.
if suppose series values are  (1, 8, 1). I would expect to see segments with data labels 10%, 80% and 10%.

However, with the code below I see 100%, 800% and 100%. 

below is code used.
       plot = chart.plots[0]
        plot.has_data_labels = True
      
        data_labels = chart.plots[0].data_labels
        data_labels.font.size = Pt(6)
        data_labels.number_format = '0%'
        data_labels.position = XL_LABEL_POSITION.CENTER

when data_labels.show_percentage=True is set instead of data_labels.number_format = '0%' it just shows number but not percentage symbol.

![image](https://user-images.githubusercontent.com/33153116/128702608-fbddd637-e879-4b77-9e71-ecf30df54a0f.png)

I want to show data labels with percentage like below
![image](https://user-images.githubusercontent.com/33153116/128703868-bd0d061c-d700-4c1d-a01e-3e97546ded59.png)

https://stackoverflow.com/questions/68711807/feature-datalabels-to-show-percentage-symbol-for-data-points-properties-72

**Comment by scanny** [comment]
Please do not duplicate StackOverflow questions here. Support questions should be posted on SO, reserving this issues list for suspected bugs and feature requests.
