### ISSUE TITLE
Delete series and category from chart

### ISSUE THREAD

**Issue by NathanTech7713** [scanny/python-pptx#735]
Hi,

So I'm not sure if this is a duplicate but I've not found any.
Would love to be able to delete series' and delete categories.
I'm pretty sure the former should be pretty easy, though I can't see much difficulty with the latter either considering charts can't contain hyperlinks or other stuff that would need clearing up.

Thanks

**Comment by scanny** [comment]
If you search around on Chart.replace_data() you'll see how to replace all the data for a chart. This can be used to do what you're looking for, it's just a somewhat different approach, like:

1. Discover all the series and category data
2. Use it to make a new ChartData object, but leaving out the series or category(s) no longer desired.
3. Use chart.replace_data() to change the data for the chart, now shorter by a series or category or whatever.
