### ISSUE TITLE
Changing scatter plot (XY) data

### ISSUE THREAD

**Issue by yahyademirbas** [scanny/python-pptx#738]
Hi! I am trying to change data of an existing scatter plot but I am facing an issue.
I have 3 scatter charts in a slide page and I am trying to replace their data with data from 3 separate excel sheets.

When I execute the code, all 3 datas are "append" one after another.
To be more clear, each excel sheet has 2375 rows. But in the end, all 3 charts are drawn based on data which has 2375*3 = 7125 rows.

> slide: https://www.screenpresso.com/=3YdOc
> btw don't mind the grids, I use powerpoint with grids open

> each table has 2375 rows: https://www.screenpresso.com/=8gzjf
> data of the third chart in the slide which is appended as I mentioned https://www.screenpresso.com/=P3kHc

      
      def replace_scatter_rsrp_cinr(self, slide_number, sheet_name):
              ws = self.wb[sheet_name]
              last_row = len(list(ws.rows)) + 1
              slide = self.prs.slides[slide_number - 1]
              chart_data = XyChartData()
      
              for shape in slide.shapes:
                  if shape.has_chart:
                      series_1 = chart_data.add_series("RSRP / CINR")

                      for i in range(2, last_row):
                          series_1.add_data_point(ws.cell(i, 4).value, ws.cell(i, 5).value)
                      shape.chart.replace_data(chart_data)

**Comment by scanny** [comment]
In future, please post support questions on StackOverflow using the `python-pptx` tag.

It looks like `python-pptx` is doing what you ask it to; the same code is executed for each chart encountered.

You're going to need to handle each chart separately, perhaps something like:

```python
def iter_charts(slide):
    return (shape.chart for shape in slide.shapes if shape.has_chart)

for i, chart in enumerate(iter_charts(slide)):
    ws = self.wb[i]
    last_row = len(list(ws.rows)) + 1
    chart_data = XyChartData()
    series_1 = chart_data.add_series("RSRP / CINR")
    for j in range(2, last_row):
        series_1.add_data_point(ws.cell(j, 4).value, ws.cell(j, 5).value)
    chart.replace_data(chart_data)
```

**Comment by yahyademirbas** [comment]
Sorry about that, it was my first issue for this library. I'll post on stackoverflow in the future.

The snippet you sent solved my problem flawlessly. Thanks for your support!

**Comment by scanny** [comment]
No worries @yahyademirbas, glad you got it working :)
