### ISSUE TITLE
Docs state that only Python 2.6, 2.7, 3.3, 3.4, or 3.6 are supported dependencies

### ISSUE THREAD

**Issue by istrupin** [scanny/python-pptx#746]
Under the "dependencies" section of the documentation, it is listed that there is a dependency on Python 2.6, 2.7, 3.3, 3.4, or 3.6, and that "The tests are run against 2.7 and 3.6 on Travis CI.":

![image](https://user-images.githubusercontent.com/18174517/135526584-193f5c41-9402-43f5-b43e-e552c3494c86.png)
 
However, looking into the `tox.ini` and `.travis.yml`, it looks like tests run against Python 3.8, so Python 3.8 seems to be supported:

https://github.com/scanny/python-pptx/blob/71d1ca0b2b3b9178d64cdab565e8503a25a54e0b/.travis.yml#L2-L5
https://github.com/scanny/python-pptx/blob/71d1ca0b2b3b9178d64cdab565e8503a25a54e0b/tox.ini#L14

I did some testing using Python 3.8, and things seem to work well -- I was wondering if we could update the docs to state that Python 3.8 is supported, and that Travis runs tests against 3.8.

Happy to submit a PR if you'd prefer that instead of just an open issue!

**Comment by scanny** [comment]
Yeah, I can do this next time I'm in there, but in general `python-pptx` is going to be forward compatible with all new Python versions, so you don't need to worry about it breaking when you move to Python 3.9 or whatever.

**Comment by istrupin** [comment]
That's awesome to hear, thanks for this great library!

**Comment by MartinPacker** [comment]
As corroboration, my project ([md2pptx](https://github.com/MartinPacker/md2pptx)) actually **requires** 3.8 or later and it runs fine - making heavy use of python-pptx.

**Comment by smturro2** [comment]
Hi, I would like to use this package in a python 3.9 project. Can you confirm that it is compatible and being tested on this version of python?

**Comment by scanny** [comment]
Fixed in version 0.6.22 circa Aug 20, 2023.
