### ISSUE TITLE
setup's `license` parameter should be a short string

### ISSUE THREAD

**Issue by sschuberth** [scanny/python-pptx#748]
Currently, setup's `license` is set to the full text of the MIT license as read from the `LICENSE` file:

https://github.com/scanny/python-pptx/blob/71d1ca0b2b3b9178d64cdab565e8503a25a54e0b/setup.py#L26
https://github.com/scanny/python-pptx/blob/71d1ca0b2b3b9178d64cdab565e8503a25a54e0b/setup.py#L41
https://github.com/scanny/python-pptx/blob/b31cf20fe31ff0f3fe0c919111f3562bb58f8b1e/setup.py#L77

This is wrong as "license" should be a [short string](https://docs.python.org/3/distutils/setupscript.html#additional-meta-data) and should just contain the name of the license (ideally as an [SPDX ID](https://spdx.org/licenses/); so here just "MIT"), not its text.

**Comment by scanny** [comment]
Sounds good to me. I'll fix that up next time I'm in there :)

**Comment by scanny** [comment]
Fixed in version 0.6.22 circa Aug 20, 2023.
