### ISSUE TITLE
Python 3.10 collections change breaks compat.__init__

### ISSUE THREAD

**Issue by Adriyst** [scanny/python-pptx#770]
The change to the collections library in python 3.10 breaks the compat.__init__ script, as reported in #750. The highlighted lines in that issue is actually the problem. From the collections documentation:

_Deprecated since version 3.3, will be removed in version 3.10: Moved Collections Abstract Base Classes to the collections.abc module. For backwards compatibility, they continue to be visible in this module through Python 3.9._

**Comment by kascodeo** [comment]
This issue is fixed in [python-pptx-fix](https://pypi.org/project/python-pptx-fix/)

**Comment by scanny** [comment]
Fixed in release 0.6.22 circa Aug 28, 2023.
