### ISSUE TITLE
BuildFreeform Method

### ISSUE THREAD

**Issue by maspireone** [scanny/python-pptx#81]
Hi Scanny,

Can you give me a hint that how can I add function like BuildFreeform Method in VBA to create curve through 4 points.
If I would like to create a function like that on top of your code, where should I start. Please help to let me know. Thank you.

The detail of the function is list below.
http://msdn.microsoft.com/en-us/library/office/aa212150(v=office.11).aspx

**Comment by stcmeh** [comment]
Hi there - any progress on this issue?
