### ISSUE TITLE
text direction: right to left

### ISSUE THREAD

**Issue by eladlavi** [scanny/python-pptx#851]
Within power point, under "paragraph", it is possible to set "Right-to-Left" text direction.
How can it be done with python pptx?
It isn't text alignment. Text alignment is something else.
So if my presentation contains Hebrew then the text gets messed up.
Thanks.

**Comment by eladlavi** [comment]
![image](https://user-images.githubusercontent.com/7921247/195977499-3252fb4c-22bc-4165-a378-66325ce509d9.png)

to be even more clear, I am attaching a screen shot from Power Point that emphasize the functionality that I'm looking in to controlling from python-pptx.
does anyone have any idea how to set this ?
is this a missing feature ?

**Comment by MartinPacker** [comment]
The usual "what does the XML look like?" question applies.

I don't use RTL myself but I might be able to provide sample code - if I knew what the XML looked like.

(As just another user of python-pptx and with very little spare time at the moment I can't promise anything, I'm afraid.)

**Comment by eladlavi** [comment]
I will appreciate it a lot. Can you provide information about working with XML so I can investigate it myself ? the Power Point file isn't an XML file obviously.

**Comment by MartinPacker** [comment]
It's possibly beyond your skill set but:

1. Create a pptx with RTL text in.
1. Change its fie extension to .zip.
1. Unzip it.
1. The appropriate part is probably a slide`x`.xml file. So throw these files into a text editor.
1. Examine them for hints of how the RTL was done.

**Comment by eladlavi** [comment]
here I created a one slide presentation, with title and subtitle, the title is "right to left" and the subtitle is not.
I can see this:
<a:pPr rtl="1"/> in slide1.xml right next to the title tag. this is probably it.
I am attaching the whole XML content.
but now that we see how rtl is represented, what change is required to the code to apply this let's say to a text box or to a paragraph or to a title ?




<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr><p:sp><p:nvSpPr><p:cNvPr id="2" name="Title 1"><a:extLst><a:ext uri="{FF2B5EF4-FFF2-40B4-BE49-F238E27FC236}"><a16:creationId xmlns:a16="http://schemas.microsoft.com/office/drawing/2014/main" id="{FA14368A-9949-9A1F-2B6E-E522A8DCA643}"/></a:ext></a:extLst></p:cNvPr><p:cNvSpPr><a:spLocks noGrp="1"/></p:cNvSpPr><p:nvPr><p:ph type="ctrTitle"/></p:nvPr></p:nvSpPr><p:spPr/><p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:pPr rtl="1"/><a:r><a:rPr lang="he-IL" dirty="0"/><a:t>כותרת ראשית</a:t></a:r><a:endParaRPr lang="en-US" dirty="0"/></a:p></p:txBody></p:sp><p:sp><p:nvSpPr><p:cNvPr id="3" name="Subtitle 2"><a:extLst><a:ext uri="{FF2B5EF4-FFF2-40B4-BE49-F238E27FC236}"><a16:creationId xmlns:a16="http://schemas.microsoft.com/office/drawing/2014/main" id="{E66D8400-EED9-AA8A-A176-419F76EED2B8}"/></a:ext></a:extLst></p:cNvPr><p:cNvSpPr><a:spLocks noGrp="1"/></p:cNvSpPr><p:nvPr><p:ph type="subTitle" idx="1"/></p:nvPr></p:nvSpPr><p:spPr/><p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:rPr lang="en-US"/><a:t>Some subtitle</a:t></a:r></a:p></p:txBody></p:sp></p:spTree><p:extLst><p:ext uri="{BB962C8B-B14F-4D97-AF65-F5344CB8AC3E}"><p14:creationId xmlns:p14="http://schemas.microsoft.com/office/powerpoint/2010/main" val="3032765064"/></p:ext></p:extLst></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sld>

**Comment by eladlavi** [comment]
I examined the difference in more details comparing to the none RTL content.
so the tag: <a:pPr rtl="1"/>   comes right after the <a:p> tag and before the <a:r> tag.
Is it possible to conclude what needs to be done from code in order to set this ?

**Comment by eladlavi** [comment]
@MartinPacker is there a chance you can guide me through this?
I think it is important feature that is missing.

**Comment by bowespublishing** [comment]
@eladlavi try this

`
import pptx
from lxml import etree
from pptx.oxml.xmlchemy import OxmlElement

def RtoL(shape):
    textb = shape.text_frame._txBody
    rId = textb.xpath('./a:p')[0]
    
    for bad in textb.xpath('./a:p/a:pPr'):
        bad.getparent().remove(bad)
    
    jj = OxmlElement("a:pPr")
    jj.set("algn","r")
    jj.set("rtl","1")
    rId.insert(0,jj)

    


prs = pptx.Presentation("test.pptx")
for slide in prs.slides:
    for shape in slide.shapes:
        if shape.has_text_frame:
            RtoL(shape)


prs.save('text2.pptx')`

**Comment by eladlavi** [comment]
ok thanks, so I checked it, and it is almost good.
I does change to RTL, so it works.
but what's missing is two things:
If I have more than one paragraph in a text frame, it only affects the first one, i.e if I did:
shapes.title.text_frame.add_paragraph()
your code affects only the first paragraph of the title.
second, the text frame loses it's design, so if I set a font size for example, it changes back to some default.

any idea how to improve your code to do that ?

**Comment by eladlavi** [comment]
I was able to improve your code with the first issue, of not handling all paragraphs in a text frame:

`def RtoL(shape):
    textb = shape.text_frame._txBody
    for bad in textb.xpath('./a:p/a:pPr'):
        bad.getparent().remove(bad)
    for rId in textb.xpath('./a:p'):
        jj = OxmlElement("a:pPr")
        jj.set("algn", "r")
        jj.set("rtl", "1")
        rId.insert(0, jj)`

I don't fully understand how it works with the XML but I kind of figured it out.
now I just need to handle the lost of design. I can guess it is caused by the code you wrote to "remove bad" so you "remove the bad" and insert a "good" one instead, but I guess in the removed XML element, it also stored the design.
by "design" I mean font size etc..

**Comment by eladlavi** [comment]
ok, I ended up with this simple code:

def RtoL(shape):
    textb = shape.text_frame._txBody
    for bad in textb.xpath('./a:p/a:pPr'):
        bad.set("rtl", "1")

so to compare to your code, instead of removing the element and then inserting a new one,
I just set the RTL to the existing element and it works!
so first, it handles multi-paragraph, second, it keeps the existing design.
I did remove the alignment line because this can be handles nicely already.
I just ask the developers to add support for this feature built in the library,
sense it solved that easily.

What is unfortunate is that this method forces you to save the pptx file and then,
reopen it and re-save it and it doesn't allow some paragraph to be RTL and some LTR.
Thanks.

**Comment by MartinPacker** [comment]
So what you're saying is there is some rendering action Powerpoint itself needs to take? I somehow doubt that is absolutely necessary. Perhaps Powerpoint is undertaking a repair action and (for once) not telling you.

Can you save the two versions of the .pptx and compare them?

**Comment by bowespublishing** [comment]
> ok, I ended up with this simple code:
> 
> def RtoL(shape): textb = shape.text_frame._txBody for bad in textb.xpath('./a:p/a:pPr'): bad.set("rtl", "1")
> 
> so to compare to your code, instead of removing the element and then inserting a new one, I just set the RTL to the existing element and it works! so first, it handles multi-paragraph, second, it keeps the existing design. I did remove the alignment line because this can be handles nicely already. I just ask the developers to add support for this feature built in the library, sense it solved that easily.
> 
> What is unfortunate is that this method forces you to save the pptx file and then, reopen it and re-save it and it doesn't allow some paragraph to be RTL and some LTR. Thanks.

Use something like - https://github.com/davecra/OpenXmlFileViewer

Compare the XML and edit as appropriate to get the result you desire
