### ISSUE TITLE
Pptx on python 3.11

### ISSUE THREAD

**Issue by RomanHnizdiukh** [scanny/python-pptx#863]
Hello, I've  installed new version of python 3.11,  and wanted to install pptx module, but it seams there is some issue which I' cant solve.
Not sure if pptx is available also within the new version of python ? 
![image](https://user-images.githubusercontent.com/56791559/206721046-0d93be5b-093f-4217-9f51-bb2c4de6d694.png)
![image](https://user-images.githubusercontent.com/56791559/206721190-bd1adcff-e376-4c78-9986-398c1eca475e.png)

**Comment by MartinPacker** [comment]
No, it's not ready for 3.11. There is an open issue for that, I believe. I think 3.9.x is the latest supported but I'd love to be proven wrong.

(Would help if you mentioned if there was some essential function in 3.10 or 3.x you actually need.)

**Comment by Kugeleis** [comment]
I found a hint here: https://github.com/ssine/pptx2md/issues/22#issuecomment-1000367136 and tried it and works in python 3.11

**Comment by robertmozwa** [comment]
I am a newbie in my Python knowIedge. I was having the same issue, I have Python 3.11 and couldn't solve it neither could chat GPT. I solved it by writing the statement 'import docx' and it worked for me.

**Comment by robertmozwa** [comment]
I am a newbie in my Python knowIedge. I was having an attribute error with the collections module I have Python 3.11 and couldn't solve it. I stumbled upon a solution by writing the statement 'import docx' and it worked for me. I have a text document that converts it to Powerpoint slides.

**Comment by scanny** [comment]
Fixed a while back.
