### ISSUE TITLE
Powerpoint needs to "repair" the file?

### ISSUE THREAD

**Issue by coleshaw** [scanny/python-pptx#87]
Hi Steve, this is an awesome library. I just started using it--apologies if my issue is simplistic or if I can find the answer elsewhere. I didn't see this in the docs or any previous issue--I am creating a pptx and serving it via Apache. I have the mimetype set to application/vnd.openxmlformats-officedocument.presentationml.presentation per one of your other issue comments. The file downloads fine from Chrome and FF, but when I open it, I get a "PowerPoint found a problem with content in the file...PowerPoint can attempt to repair the file. If you trust the source of this file, click Repair."

It's just a simple ppt with text and some images. Googling identifies a problem with "block / unblock" for Windows, but even after I unblock the file on Windows, PowerPoint still has an issue and wants to repair it (Mac and Windows 7 VM). 

Have you seen this issue before? My Python code follows your examples. Thanks!

**Comment by Narender1903** [comment]
when i remove shape i got this error.
