### ISSUE TITLE
MSO_LINE.ROUND_DOT not correct in xml

### ISSUE THREAD

**Issue by benaustin2000** [scanny/python-pptx#888]
Hi ,
When create charts in slides, MSO_LINE.ROUND_DOT does not proper display dot in slides. 
in dml.py  the ROUND_DOT val is dot, but following link below,
https://learn.microsoft.com/en-us/openspecs/office_standards/ms-docx/82325e66-8510-43a9-af4f-6c8970502474
 Should  use "sysDot" replace "dot"

**Comment by scanny** [comment]
Ah, yes, so it is. I've fixed that and it will show up in the next release. Thanks for letting us know :)
