### ISSUE TITLE
NotImplementedError: XML writer for chart type THREE_D_BAR_CLUSTERED (60) not yet implemented

### ISSUE THREAD

**Issue by pmoscol** [scanny/python-pptx#890]
Python 3.9.13 and python-pptx 0.6.21: Result NotImplementedError: XML writer for chart type THREE_D_BAR_CLUSTERED (60) not yet implemented in my script chart = slide.shapes.add_chart(
            XL_CHART_TYPE.THREE_D_BAR_CLUSTERED, Inches(0.5), Inches(3.5), Inches(8), Inches(4.5), chart_data
        ).chart

**Comment by scanny** [comment]
Yep. Don't try to use that one for creating. It still needs to be there for reading though.
