### ISSUE TITLE
Data Labels Not Found for Doughnut Chart

### ISSUE THREAD

**Issue by ssho25** [scanny/python-pptx#891]
![image](https://github.com/scanny/python-pptx/assets/135136026/577e6655-0ab9-4799-bbc5-b78509a1b4ee)
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/P3001388/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/P3001388/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">
<p> **showing the 'edit data' result from the doughnut chart in powerpoint** </p>

A1 | 7.8
-- | --
A2 | 23.1
A3 | 0
A4 | 9.4
B1 | 13.2
B2 | 24.7
B3 | 7.2

</body>

</html>

Data is populating a doughnut chart as shown but when using any of the following in Visual Studio Code:
- pptx.chart.point.CategoryPoints
- pptx.chart.point.Point
- data_label

The series appears blank (' '). A series is found containing the numerical values but not A1, A2, A3 etc.
I am trying to assign hex colours to A1, A2, A3 etc. and cannot assign them to the numerical values as these change throughout the year. Is this a weakness in the code?

**Comment by scanny** [comment]
A Donut chart is a stylized Pie Chart. A pie chart has `.categories` and a single `.series`.

I think you're looking for `chart.categories` which is where the A1, A2 bit comes from. This corresponds to the X-axis in a bar chart (column chart more precisely).
