### ISSUE TITLE
is there a way to "hide" information within slides?

### ISSUE THREAD

**Issue by nnako** [scanny/python-pptx#894]
Hi,

in an application using `python-pptx`, I want to store information which is not relevant for the presentation user but relevant for an additional tooling. that tooling is to read-in the presentation file and gather that information which is "hidden" from the user.

Currently, I use the `hyperlink` attribute of a specific pptx element to store those "internal values" which are later read-out by another tooling. For example I store the value "`ID_12345678`" within an image shape, located as `<slide>.<shape>.click_action.hyperlink.address`.

There are two major drawbacks when using the element's `hyperlink` in such a way:

- via `<MOUSE-OVER>`, the user might accidentally view these cryptic content and be confused
- there is no way to use "real" hyperlinks in case I want to jump into an URL

**Is there a way to store (and later read out) element-specific but "internal" information within a pptx file using `python-pptx`, so that a presentation user might not be confused and the `hyperlink` functionality might still be used for hyperlinking?**

**Comment by scanny** [comment]
I think you'll need to do your own research here and see what PowerPoint supports for this and perhaps what other folks have worked out.

It will vary based on what object(s) you want to annotate, like slide, shape, presentation, etc.

Rough ideas might be:
- shape alt-text
- could change shape name, I don't think anything uses that but might in outline view or something
- off-slide shapes
- custom XML
- might want to consult the XML schema in `spec/ISO-IEC-29500-4/xsd/pml.xsd` in the repo to see if there are any good candidate elements.
- searching Google on "add metadata to powerpoint shapes" shows something to with "custom tags" which might be an idea.
