### ISSUE TITLE
After opening the modified PPT, an error will be reported: there is a problem with the content, please fix it

### ISSUE THREAD

**Issue by DuskBelievers** [scanny/python-pptx#896]
I modified a bar chart with "python-pptx", and when I opened the PPT, I got an error: Something is wrong with the content, please fix it. However, after I click "Repair", the whole content of the slide disappeared, I only modified one bar chart in the whole slide and the other contents were not modified, I think this is not the problem of the code, the other slides I modified are fine, these slides include text boxes, line charts, bar charts and so on.
I wonder what the possible reasons are for this.

**Comment by scanny** [comment]
Not enough to go on here unfortunately. I'd start by opening the file with `python-pptx`, not making any changes, and saving it and see if you still get the problem.

If not it's something you did when you modified the chart, and you'd have to show the code you used to change it.
