### ISSUE TITLE
Font properties Bold Italic

### ISSUE THREAD

**Issue by mengdi** [scanny/python-pptx#90]
If I understand this correctly, we can set bold/italic for the whole paragraph like  paragraph.font.bold = True. And a new paragraph means a new line.
My question is how can I set bold/italic for only a part of a sentence? Like this in HTML: How < b>are</b > you. I don't want to create 3 paragraphs for this one-line sentence.

Thanks in advance for your reply.

**Comment by AyushSinghal9020** [comment]
I am currently working on a project which requires the text attribute from the shapes, the thing I am asking is can we have font attributes with the "add_textbox" attribute of shape, or we have to go for the paragraphs only
