### ISSUE TITLE
How to find pptx is None or having custom template path

### ISSUE THREAD

**Issue by Srini138** [scanny/python-pptx#905]
Hi
I am having custome theme powerpoint. If i wish to upload custom theme its going back and its getting as
`prs = Presentation('my_custom_theme.pptx')` otherwise it should be default `prs = Presentation()` How to find pptx has path of custom theme presentation file or None.Any suggestions very much helpful

**Comment by MartinPacker** [comment]
Are you asking about the existence of the file or its contents?

Former is not a python-pptx problem but standard Python.

**Comment by jesse-sealand** [comment]
@Srini138 , please clarify your question so it can be addressed.
