### ISSUE TITLE
How to judge whether a cell is merged with lower or right cell to convert table to html code incluing rowspan and colspan?

### ISSUE THREAD

**Issue by nissansz** [scanny/python-pptx#916]
How to judge whether a cell is merged with lower or right cell to convert table to html code incluing rowspan and colspan?

**Comment by scanny** [comment]
Have a look at the API documentation for `_Cell` here: https://python-pptx.readthedocs.io/en/latest/api/table.html#cell-objects

The attributes of interest are:
* `.is_merge_origin`
* `.span_height`
* `.span_width`
* and possibly `.is_spanned`
