### ISSUE TITLE
Change the theme colors

### ISSUE THREAD

**Issue by GYC-lab** [scanny/python-pptx#917]
Thanks for this useful library firstly!

My question is, how to change the theme colors?

As far as I know, the theme colors are related to MSO_THEME_COLOR.ACCENT_1, MSO_THEME_COLOR.ACCENT_2, ...

But how to change the detailed RGB values of these **MSO_THEME_COLOR**?

It would save a lot to time if there is a way to modify the RGB values of **MSO_THEME_COLOR**. Otherwise, I think I would have to match those color with theme colors and then change them. 

Looking forward to your reply!

**Comment by scanny** [comment]
Create an empty presentation with the theme you want and then use that as the starting place, like `prs = Presentation("my-template.pptx")`.

**Comment by GYC-lab** [comment]
> Create an empty presentation with the theme you want and then use that as the starting place, like `prs = Presentation("my-template.pptx")`.

Thank you for the in-time reply!

So the theme colors of the empty presentation which will be served as a template has to be set manully?

**Comment by scanny** [comment]
The theme colors are already in the "starting" presentation. So you just create one that looks the way you want and then those theme colors are available to you to select by name.

There's no current way to change the theme colors of an existing presentation, you'll be on your own for that.

The names `ACCENT_1` etc. are just slots for different colors. Each theme places their choice of colors in those slots.

**Comment by gitchrisqueen** [comment]
I was able to successfully change the theme colors of an already created Power Point Presentation using the following function:

```python

import os
from pptx import Presentation
from pptx.opc.constants import RELATIONSHIP_TYPE as RT
from lxml.etree import parse_xml, tostring

def set_ppt_theme_colors(ppt_path: str, theme_colors: dict = None) -> None:
    """
    Set the theme colors of a PowerPoint presentation.

    Args:
        ppt_path (str): Path to the PowerPoint file.
        theme_colors (dict, optional): Dictionary of theme color names and their hex values. Defaults to white colors.
    """
    # Load default theme colors if none provided
    if theme_colors is None:
        theme_colors = {
            "dk1": "ffffff",
            "lt1": "ffffff",
            "dk2": "ffffff",
            "lt2": "ffffff",
            "accent1": "ffffff",
            "accent2": "ffffff",
            "accent3": "ffffff",
            "accent4": "ffffff",
            "accent5": "ffffff",
            "accent6": "ffffff",
            "hlink": "ffffff",
            "folHlink": "ffffff"
        }

    # Load the presentation
    prs = Presentation(ppt_path)

    # Get the Slide Master and its part
    slide_master = prs.slide_master
    slide_master_part = slide_master.part

    # Get the Theme part
    theme_part = slide_master_part.part_related_by(RT.THEME)
    theme = parse_xml(theme_part.blob)  # theme here is an <a:theme> element

    # Update the color values in the theme
    for color_name, hex_value in theme_colors.items():
        if color_name:
            color_element = theme.xpath(f'a:themeElements/a:clrScheme/a:{color_name}/a:srgbClr')[0]
            color_element.set('val', hex_value.encode('utf-8'))

    # Serialize the modified XML back to the theme part
    theme_part._blob = tostring(theme)

    # Save the presentation
    prs.save(ppt_path)
```
