### ISSUE TITLE
New text box text starts on line 2 with first line being blank... cannot solve.

### ISSUE THREAD

**Issue by beauxapps** [scanny/python-pptx#918]
Help! 

Love the package. No issues except the following one -- creating a text frame in a shape with the following: 

```python
       text = text_small
       text_frame = box.text_frame
       text_frame.paragraphs[0].space_after = Pt(0)
       p = text_frame.add_paragraph()
       p.clear()
       p.text = "TODO"
       p.font.size = Pt(12)
       p.alignment = 1  # Center alignment
       p.font.name = font_name
       p.font.bold = True
       p.alignment = PP_ALIGN.CENTER
``` 
However, no matter what I try the text ends up on line 2 of the text frame with an empty line above it. 

Ideas?  

The following is what i've tried so far that has not helped... 

```python 
       text_frame.paragraphs[0].space_after = Pt(0)
       p = text_frame.add_paragraph()
       p.clear()
```

Here's the generated ppt

![image](https://github.com/scanny/python-pptx/assets/7648723/5ec496ea-f3d3-4af4-936b-c8b719a7d2de)
![image](https://github.com/scanny/python-pptx/assets/7648723/c0dfedd4-e2f3-48b7-ae8b-a4ed335ae7b8)

**Comment by scanny** [comment]
A text frame is born with a single empty paragraph. So you put your text there then only add a new paragraph if you need another.

**Comment by sammysignal** [comment]
For future devs: this means you can just grab the first paragraph and set the exact text you want there.

```
my_textbox = slide.shapes.add_textbox(Inches(2), Inches(1), Inches(6), Inches(1))
my_textbox.text_frame.paragraphs[0].text = "Hello, World!"
```

**Comment by MartinPacker** [comment]
I'm slightly surprised a paragraph has a font attribute; I expected that to be on the first run. Maybe this is a convenience shorthand.

**Comment by scanny** [comment]
@MartinPacker PPTX has the concept of "default text properties", `p:defRPr` I think, such the the style hierarchy will use default settings on the paragraph if not set in a run.

As I recall it only applies to certain text properties or is "spotty" in that it works some places and not others, but anyway that's why `.font` appears on `_Paragraph`.

From the docs:
> [Font](https://python-pptx.readthedocs.io/en/latest/api/text.html#pptx.text.text.Font) object containing default character properties for the runs in this paragraph.
>
> These character properties override default properties inherited from parent objects such as the text frame the paragraph is contained in and they may be overridden by character properties set at the run level.

**Comment by MartinPacker** [comment]
Thank you @scanny. My experience is generally in manipulating actual runs - which I think I'll continue to do - particularly as you used the word "spotty". 😀
