### ISSUE TITLE
replicate chart created by hand

### ISSUE THREAD

**Issue by Deusdeorum** [scanny/python-pptx#919]
I would post this question in the "discussion" section of this repository, but sadly, there's no discussion tab in this repository. For now, I have only used python-pptx to replace data in the charts so that the chart itself gets styled exactly how I want it to be styled beforehand.

However, let's consider a scenario where I have a stacked100 chart styled manually. Is it possible to replicate the chart with python-pptx so that it is identical to how I styled it in the GUI?

I'm not asking how to do it. I'm only asking if, in theory, it is possible.

**Comment by scanny** [comment]
If Stacked-100 is an option in `python-pptx` then I expect you could get quite close, possibly exactly, maybe needing to do a few XML patches if your formatting is fancy.

If Stacked-100 is _not_ an option there's probably a reason and then I'd be less optimistic. But it's all XML underneath so depending on your skill and desire anything is possible.

Like @MartinPacker says, the best answer is going to come from trying it, but overall I'd start with optimism :)
