### ISSUE TITLE
add_video Documentation Missing?

### ISSUE THREAD

**Issue by gaurav21r** [scanny/python-pptx#931]
@scanny First of all thanks a ton for this library 🙏🏼
I am creating app that automates adding video to a PPTX using ffmpeg and Electron JS...

I noticed there is a method called `add_video` here:
<img width="668" alt="image" src="https://github.com/scanny/python-pptx/assets/1716462/07d82a45-c477-468f-9619-211e8e2fbd80">

...but this seems to be missing in the docs (or Search is not working here)

<img width="629" alt="image" src="https://github.com/scanny/python-pptx/assets/1716462/c11b52cc-e638-4830-9b29-98d5287ac271">

I have some confusion regarding the second parameter called `shape_id`. Does this mean I need to first add a Shape and then use `add_video` as a child? How do I add the video data here? (Video File Path / Base64 representation?)

If you can just let me know how to do it here, I'd love to add this to the docs with a PR (unless its not been added voluntarily).

Kindly forgive if I've misunderstood anything here. New to Python & this Library!

**Comment by scanny** [comment]
Yeah, as a matter of convention we adhere to user-interface concept-naming in the API and XML element-naming in the XML-layer to reduce mental translation for users and developers.

Unfortunately those don't always line up exactly but still seems to be the best convention. An end-user is more likely to find what they're after using UI language, like Insert > Movie from the toolbar, and someone working on the XML uses code that matches the XML they are manipulating, like `.add_video()` adds a `<p:video>` element.
