### ISSUE TITLE
About how to extract media file and position?

### ISSUE THREAD

**Issue by newdee** [scanny/python-pptx#932]
when pptx has media info, how  to extract media file from  every slide?
any answer will be helpful

**Comment by scanny** [comment]
You haven't described your purposes, that is, "why" you want to do this, so there are many possible answers. One is you can unzip the `.pptx` file (which is a zip archive) and locate all the media files in there by extension or perhaps using the `filemagic` library.

**Comment by newdee** [comment]
Not the location in the folder, but which page and location in the ppt. If you want to extract the video and resume editing, is this function supported?
