### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'Container'

### ISSUE THREAD

**Issue by zchunter** [scanny/python-pptx#949]
I ran into an error when running through the hello world demo for PPTX. It appears that as of Python 3.10, there is an error of `AttributeError: module 'collections' has no attribute 'Container'` when attempting to run the line `from pptx import Presentation`

Looking into it, this can be resolved by adding:
```
import collections
import collections.abc
```

Sharing in case you want to update the hello world demo!

**Comment by scanny** [comment]
What version are you running @zchunter? Pretty sure that was fixed a while ago now.

**Comment by zchunter** [comment]
I'm sorry about that. I realized I had installed it previously when I
thought it would be used for a project. I was using 0.6.21. Updating to
0.6.23 resolved the issue.

Zachary Hunter

**Comment by scanny** [comment]
No worries Zach, glad you got it working :)
