### ISSUE TITLE
Convert PPT file to Python code

### ISSUE THREAD

**Issue by yhcao6** [scanny/python-pptx#952]
Thanks for your great work. May I ask if a parser or script exists to parse a PPT file to Python code that can reproduce the original PPT?

**Comment by nexuslux** [comment]
Trying taking a screenshot of the slide and the uploading it to multimodal LLM like ChatGPT 4. Prompt it to give you the indicative code for it that corresponds to this repo?

**Comment by scanny** [comment]
@yhcao6 I'm not aware of one.
