### ISSUE TITLE
python pptx not extracting all the text from the slide

### ISSUE THREAD

**Issue by vignesh0710** [scanny/python-pptx#955]
I am trying to use ```python-pptx``` to extract all the text in a given slide.

> But it is missing some text from some text boxes.

code:

    from pptx import Presentation
    
       def getPptContent(path):
         prs = Presentation(path)
         text_runs = []
         for slide in prs.slides:
             for shape in slide.shapes:
                 if not shape.has_text_frame:
                     continue
                 for paragraph in shape.text_frame.paragraphs:
                     for run in paragraph.runs:
                        text_runs.append(run.text)
         return text_runs

But it is missing some text, but when I try to ```print``` the contents of the slide 
from ```slide._element``` I can see the ```missing text``` in the ```xml```

Any suggestions will be helpful

**Comment by scanny** [comment]
A shape can be a group shape which can contain other shapes.

So you need to recursively descend into group shapes (which can be nested multiple layers deep).

Have a Google on "python-pptx traverse group shapes" and you should find what you need, this one for example: https://stackoverflow.com/questions/51701626/how-to-extract-text-from-a-text-shape-within-a-group-shape-in-powerpoint-using

**Comment by du-owen** [comment]
I think I found a bug where python-pptx does not extract all the shapes from a slide. I use the following code to get a flattened representation of shapes on a slide:

```python
def flattenGroups(shapes, flattened):
    # Depth-first traversal...
    maxDepth = 0
    for s in shapes:
        print(s.shape_type)
        if isinstance(s, GroupShape):
            _, childDepth = flattenGroups(s.shapes, flattened)
            maxDepth = max(maxDepth, childDepth)
        else:
            flattened.append(s)
    
    return flattened, maxDepth + 1
```
When printing the shapes, I get 3 text boxes and 4 auto shapes. When I use python COM interface using pywin32 I get the correct amount of shapes (19), which are just text boxes and auto shapes. Here is the example:
[test_shapes.pptx](https://github.com/user-attachments/files/17798055/test_shapes.pptx)

EDIT: I checked with my dataset of slides, and it seems it happens regularly that python pptx extracts fewer shapes than the python COM interface in Powerpoint

EDIT2: Seems like python pptx cannot extract special types like InkComment (23) and it also cannot extract a text box that contains latex formulas

**Comment by scanny** [comment]
Hmm, interesting. The situation with this particular deck appears to be related to the formulas. They are "wrapped" in `<mc:AlternateContent>` elements.

Looking into those elements, the alternate content (when the client cannot process MathML) is a single blank paragraph.

`python-pptx` does not support MathML (equations), so in this case at least this is the expected behavior.
