### ISSUE TITLE
Slide duplicate Microsoft office interprets python-pptx powerpoint files as corrupted

### ISSUE THREAD

**Issue by haoyjp** [scanny/python-pptx#961]
import copy
import pptx
def copy_slide(pres, slide_index):
    def _get_blank_slide_layout(pres):
         layout_items_count = [len(layout.placeholders) for layout in pres.slide_layouts]
         min_items = min(layout_items_count)
         blank_layout_id = layout_items_count.index(min_items)
         return pres.slide_layouts[blank_layout_id]

    blank_slide_layout = _get_blank_slide_layout(pres)
    source=pres.slides[slide_index]
    dest = pres.slides.add_slide(blank_slide_layout)
    rels = source.part.rels
    #for key, value in source.part.rels.items():
    for key, value in rels.items():
        # Make sure we don't copy a notesSlide relation as that won't exist
        if not "notesSlide" in value.reltype:
                dest.part.rels._add_relationship(value.reltype, value._target, False)

print(pptx.__version__)
prs=pptx.Presentation('old.pptx')
copy_slide(prs, 1)
prs.save("new.pptx")

**Comment by mdylan2** [comment]
Did you manage to solve this?

**Comment by a6708051** [comment]
hello, do you solve this question? how to solve it？
