### ISSUE TITLE
There is a bug for load image under the package "langchain.document_loaders import UnstructuredImageLoader"

### ISSUE THREAD

**Issue by whysirier** [scanny/python-pptx#980]
### my code:
from langchain.document_loaders.image import UnstructuredImageLoader
from PIL import Image
import io

image = Image.open("/mnt/data/spdi-code/paddlechat/pic/caigou.jpg") #local image path

loader = UnstructuredImageLoader(image )

data = loader.load() 
          
print("data", data)

### error
![企业微信截图_20240527155733](https://github.com/scanny/python-pptx/assets/142364107/50e1da90-0857-4bac-9229-9febdfabb018)

**Comment by scanny** [comment]
Closing as not related to `python-pptx`. Please open this issue on the `unstructured` project:
https://github.com/Unstructured-IO/unstructured/issues
