### ISSUE TITLE
auto_size not working

### ISSUE THREAD

**Issue by xlar8or** [scanny/python-pptx#982]
Hello, I'm creating a textbox and I want it to be sized so it fits the whole text in the TextFrame. I'm doing the following code:

```
textbox = slide.shapes.add_textbox(0, 0, Inches(3), Inches(1))
text_frame = textbox.text_frame
text_frame.text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
text_frame.auto_size = MSO_AUTO_SIZE.SHAPE_TO_FIT_TEXT
text_frame.word_wrap = True
```

This is what I get:

![image](https://github.com/scanny/python-pptx/assets/7469199/42360e79-a8a8-4f1e-bc26-5e56f5a9082d)

If i go to the Textbox properties I have the following:

![image](https://github.com/scanny/python-pptx/assets/7469199/2c335195-54c8-4fc7-bba5-eb6c33163de2)

If I click again on the Resize shape to fit text then I get the correct behavior:

![image](https://github.com/scanny/python-pptx/assets/7469199/9bdca35d-c042-4884-9405-0f5371f482cc)

FYI: I don't have PowerPoint, I'm using WPS, could that contribute to the problem?

**Comment by scanny** [comment]
Closing as not actionable. @xlar8or there is unlikely to be further work on auto_size and it entails partially implementing a renderer with is out-of-scope on principle for this library.

**Comment by kabalan-datapostie** [comment]
Thank you @scanny - the explanation is clear.

There therefore seems to be some conflicting info in the docs. Your answer and the [docs](https://python-pptx.readthedocs.io/en/latest/dev/analysis/txt-autofit-text.html?highlight=auto%20fit) @mszbot linked show that it's renderer-based and out-of-scope, but https://python-pptx.readthedocs.io/en/latest/user/text.html#applying-text-frame-level-formatting seems to indicate it's trivial. Are the latter docs out of date? Are there earlier versions of PowerPoint for which a simple `text_frame.auto_size = MSO_AUTO_SIZE.SHAPE_TO_FIT_TEXT` used to work?

**Comment by BastienGimbert** [comment]
Hello, https://github.com/scanny/python-pptx/pull/1107
